(() => {
  const cfg = window.GOYA_CONFIG || {};
  let sb = null;
  const state = { token:null, user:null, data:{}, adminData:{}, cart:[], prodCart:[], wasteCart:[], history:{}, historyKind:'orders', historyStatus:'', adminOrders:[], pwRows:[], inventoryRows:[], complaints:[], inventoryCache:{} };
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const fmtDate = v => { if(!v) return ''; const d=new Date(v); return isNaN(d)?String(v):d.toLocaleString('en-AE',{dateStyle:'medium',timeStyle:'short'}); };
  const isoMonth = () => new Date().toISOString().slice(0,7);
  const dateOnly = v => v ? String(v).slice(0,10) : '';
  const normalize = v => String(v||'').trim().toLowerCase();
  const sectionNames = ['Bar','Kitchen','Pastry','Packaging'];
  function toast(msg,error=false){ const t=document.createElement('div'); t.className='toast'+(error?' err':''); t.textContent=msg; document.body.appendChild(t); setTimeout(()=>t.remove(),3400); }
  function showView(id){ document.querySelectorAll('[data-view]').forEach(x=>x.classList.add('hidden')); $(id)?.classList.remove('hidden'); }
  function setNav(btn){ document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active')); btn?.classList.add('active'); }
  async function initClient(){ if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY) throw new Error('Supabase configuration is missing.'); if(!window.supabase?.createClient) throw new Error('Supabase library did not load.'); if(!sb) sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}}); return sb; }
  async function rpc(name,args={}){ await initClient(); const {data,error}=await sb.rpc(name,args); if(error) throw new Error(error.message); return data; }
  function downloadBlob(name,blob){ const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},600); }
  function csv(rows,headers,name){ const q=v=>`"${String(v??'').replace(/"/g,'""')}"`; const text=[headers.map(q).join(','),...rows.map(r=>headers.map(h=>q(r[h])).join(','))].join('\r\n'); downloadBlob(name,new Blob([text],{type:'text/csv;charset=utf-8'})); }
  function excel(rows,name,sheet='Report'){ if(!window.XLSX){toast('Excel library did not load.',true);return;} const ws=XLSX.utils.json_to_sheet(rows); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,sheet.slice(0,31)); XLSX.writeFile(wb,name); }
  function units(item){ return [...new Set([item.storage_unit,item.ingredient_unit].filter(Boolean))]; }
  function splitQty(item,unit,qty){ return normalize(unit)===normalize(item.storage_unit)?{storage_quantity:qty,ingredients_quantity:null}:{storage_quantity:null,ingredients_quantity:qty}; }
  function pill(status){ return `<span class="pill ${normalize(status).replace(/\s+/g,'-')}">${esc(status)}</span>`; }
  function sectionsChecked(cls){ return [...document.querySelectorAll('.'+cls+':checked')].map(x=>x.value); }
  function setSectionsChecked(cls,values=[]){ document.querySelectorAll('.'+cls).forEach(x=>x.checked=values.includes(x.value)); }

  // ---------- STAFF ----------
  async function staffLogin(){
    const pin=$('staffPin').value.trim(); if(!/^\d{4}$/.test(pin)){toast('Enter a 4-digit PIN.',true);return;}
    try{ const d=await rpc('staff_login',{p_pin:pin}); state.token=d.token; state.user=d; await staffLoad(); $('staffLogin').classList.add('hidden'); $('staffApp').classList.remove('hidden'); $('welcome').textContent=`Welcome, ${d.name}`; $('staffPin').value=''; toast(`Welcome, ${d.name}`); }
    catch(e){toast(e.message,true)}
  }
  async function staffLoad(){ state.data=await rpc('staff_bootstrap',{p_token:state.token}); const a=state.user.access||{}; $('navOrder').classList.toggle('hidden',!a.order); $('navProduction').classList.toggle('hidden',!a.production); $('navWastage').classList.toggle('hidden',!a.wastage); $('navInventory').classList.toggle('hidden',!a.inventory && !(state.data.inventory_sessions||[]).length); renderInfo(); renderInventorySessions(); await loadOperationalDrafts(); $('historyMonth').value=isoMonth(); await staffHistory(); if($('myAttDate'))$('myAttDate').value=new Date().toISOString().slice(0,10);if($('myAttMonth'))$('myAttMonth').value=isoMonth(); }
  function staffNav(btn,id){setNav(btn);showView(id);$('sidebar').classList.remove('open'); if(id==='staffInventory')renderInventorySessions();if(id==='staffMyAttendance')loadMyAttendance();}
  function mobileMenu(){ $('sidebar').classList.toggle('open'); }
  function searchMaster(){ const q=normalize($('orderSearch').value); const list=(state.data.master_items||[]).filter(x=>!q||normalize(x.name).includes(q)||normalize(x.sku).includes(q)).slice(0,40); $('orderResults').innerHTML=list.length?list.map(x=>`<div class="result" onclick="GoyaStaff.pickOrderItem('${esc(x.id)}')"><div><div class="name">${esc(x.name)}</div><div class="small muted">${esc(x.sku)} · ${esc(x.supplier||'No supplier')}</div></div><span class="tag">${esc(x.storage_unit)} / ${esc(x.ingredient_unit)}</span></div>`).join(''):'<div class="empty">No matching item.</div>'; }
  function pickOrderItem(id){ const x=(state.data.master_items||[]).find(y=>y.id===id); if(!x)return; state.selectedOrder=x; $('orderResults').innerHTML=''; $('orderSearch').value=''; $('orderSelected').classList.remove('hidden'); $('orderSelected').innerHTML=`<div class="card" style="box-shadow:none"><div class="section-title"><div><strong>${esc(x.name)}</strong><div class="small muted">${esc(x.sku)}</div></div><span class="tag">${esc(x.supplier||'No supplier')}</span></div><div class="form-grid"><div class="field"><label>Quantity</label><input id="orderQty" type="number" min="0.001" step="0.001"></div><div class="field"><label>Unit</label><select id="orderUnit">${units(x).map(u=>`<option>${esc(u)}</option>`).join('')}</select></div><div class="field"><label>Supplier</label><input value="${esc(x.supplier||'')}" disabled></div><div class="field" style="align-self:end"><button class="btn" onclick="GoyaStaff.addOrderLine()">Add to cart</button></div></div></div>`; }
  function addOrderLine(){ const x=state.selectedOrder,qty=Number($('orderQty').value),unit=$('orderUnit').value; if(!x)return; if(!qty||qty<=0){toast('Enter a valid quantity.',true);return;} if(state.cart.some(r=>r.sku===x.sku)){toast('Same item is already in the cart.',true);return;} state.cart.push({name:x.name,sku:x.sku,quantity:qty,unit,supplier:x.supplier||'',notes:''}); state.selectedOrder=null; $('orderSelected').classList.add('hidden'); renderOrderCart(); }
  function renderOrderCart(){ $('orderCartBody').innerHTML=state.cart.length?state.cart.map((x,i)=>`<tr><td>${esc(x.name)}<div class="small muted">${esc(x.sku)}</div></td><td>${x.quantity}</td><td>${esc(x.unit)}</td><td>${esc(x.supplier)}</td><td><input type="text" value="${esc(x.notes)}" placeholder="Optional note" oninput="GoyaStaff.setOrderNote(${i},this.value)"></td><td><button class="btn danger tiny" onclick="GoyaStaff.removeOrder(${i})">Remove</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">Your cart is empty.</td></tr>'; $('submitOrder').disabled=!state.cart.length; }
  function setOrderNote(i,v){ if(state.cart[i])state.cart[i].notes=v; }
  function removeOrder(i){state.cart.splice(i,1);renderOrderCart();}
  function groupedOrderText(items,staff){ const groups={}; items.forEach(x=>{const k=x.supplier||'Unassigned';(groups[k]??=[]).push(x)}); let out='=== NEW PURCHASE ORDER ===\n\n'; Object.entries(groups).sort(([a],[b])=>a.localeCompare(b)).forEach(([supplier,rows],idx)=>{ if(idx)out+='\n'; out+=`Supplier: ${supplier}\n`; rows.forEach(r=>{out+=`- ${r.name}: ${r.quantity} ${r.unit}${r.notes?.trim()?` (${r.notes.trim()})`:''}\n`;}); }); out+=`\nSubmitted By: ${staff}\nDate & Time: ${new Date().toLocaleString('en-AE',{dateStyle:'short',timeStyle:'medium'})}\n\nGenareted via Goya Smart Portal`; return out; }
  async function submitOrder(){ if(!state.cart.length)return; const submitted=state.cart.map(x=>({...x})); try{ const r=await rpc('submit_order',{p_token:state.token,p_notes:null,p_items:submitted}); await clearOperationalDraft('order'); const body=groupedOrderText(submitted,state.user.name); const subject=`📦 New Goya Purchase Order Submitted by ${state.user.name}`; state.cart=[];renderOrderCart();$('lastOrderActions').classList.remove('hidden');$('lastOrderNo').textContent=r.order_no; $('waOrder').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent(body),'_blank'); $('emailOrder').onclick=()=>{const to='mehedi.src@gmail.com'; window.location.href=`mailto:${to}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;}; toast('Order submitted successfully.'); await staffHistory(); }catch(e){toast(e.message,true)} }
  function searchItems(kind){ const input=$(kind==='production'?'prodSearch':'wasteSearch'),box=$(kind==='production'?'prodResults':'wasteResults'),q=normalize(input.value); const list=(state.data.internal_items||[]).filter(x=>!q||normalize(x.name).includes(q)||normalize(x.sku).includes(q)).slice(0,40); box.innerHTML=list.length?list.map(x=>`<div class="result" onclick="GoyaStaff.pickItem('${kind}','${esc(x.id)}')"><div><div class="name">${esc(x.name)}</div><div class="small muted">${esc(x.sku)} · ${esc(x.items_type)}</div></div><span class="tag">${esc(x.storage_unit)} / ${esc(x.ingredient_unit)}</span></div>`).join(''):'<div class="empty">No matching item.</div>'; }
  function pickItem(kind,id){ const x=(state.data.internal_items||[]).find(y=>y.id===id); if(!x)return; state.selectedInternal={kind,item:x}; const box=$(kind==='production'?'prodSelected':'wasteSelected'); box.classList.remove('hidden'); box.innerHTML=`<div class="card" style="box-shadow:none"><div class="section-title"><div><strong>${esc(x.name)}</strong><div class="small muted">${esc(x.sku)}</div></div><span class="tag">${esc(x.items_type)}</span></div><div class="form-grid"><div class="field"><label>Quantity</label><input id="${kind}Qty" type="number" min="0.001" step="0.001"></div><div class="field"><label>Unit</label><select id="${kind}Unit">${units(x).map(u=>`<option>${esc(u)}</option>`).join('')}</select></div>${kind==='wastage'?'<div class="field"><label>Reason / note</label><input id="wasteReason" placeholder="Type reason…"></div>':''}<div class="field" style="align-self:end"><button class="btn" onclick="GoyaStaff.addLine('${kind}')">Add to review list</button></div></div></div>`; $(kind==='production'?'prodResults':'wasteResults').innerHTML=''; $(kind==='production'?'prodSearch':'wasteSearch').value=''; }
  function addLine(kind){ const s=state.selectedInternal;if(!s||s.kind!==kind)return;const x=s.item,qty=Number($(kind+'Qty').value),unit=$(kind+'Unit').value;if(!qty||qty<=0){toast('Enter a valid quantity.',true);return;} const arr=kind==='production'?state.prodCart:state.wasteCart;if(arr.some(r=>r.sku===x.sku)){toast('Same item is already in the list.',true);return;} const row={name:x.name,sku:x.sku,quantity:qty,unit,...splitQty(x,unit,qty)}; if(kind==='wastage'){row.reason=$('wasteReason').value.trim();if(!row.reason){toast('Type a wastage reason.',true);return;}} arr.push(row); state.selectedInternal=null; $(kind==='production'?'prodSelected':'wasteSelected').classList.add('hidden'); renderStaffCart(kind); }
  function renderStaffCart(kind){ const arr=kind==='production'?state.prodCart:state.wasteCart,body=$(kind==='production'?'productionCartBody':'wastageCartBody'); body.innerHTML=arr.length?arr.map((x,i)=>`<tr><td>${esc(x.name)}<div class="small muted">${esc(x.sku)}</div></td><td>${x.quantity}</td><td>${esc(x.unit)}</td>${kind==='wastage'?`<td>${esc(x.reason)}</td>`:''}<td><button class="btn danger tiny" onclick="GoyaStaff.removeLine('${kind}',${i})">Remove</button></td></tr>`).join(''):`<tr><td colspan="${kind==='wastage'?5:4}" class="empty">Nothing added yet.</td></tr>`; $(kind==='production'?'submitProduction':'submitWastage').disabled=!arr.length; }
  async function loadOperationalDrafts(){try{const d=await rpc('staff_draft_get',{p_token:state.token});state.cart=Array.isArray(d?.order)?d.order:[];state.prodCart=Array.isArray(d?.production)?d.production:[];state.wasteCart=Array.isArray(d?.wastage)?d.wastage:[];renderOrderCart();renderStaffCart('production');renderStaffCart('wastage');}catch(e){console.warn('Draft load failed',e);}}
  function operationalDraftItems(kind){return kind==='order'?state.cart:(kind==='production'?state.prodCart:state.wasteCart);}
  async function saveOperationalDraft(kind){const items=operationalDraftItems(kind);if(!items.length){toast('Add at least one item before saving a draft.',true);return;}try{await rpc('staff_draft_save',{p_token:state.token,p_kind:kind,p_items:items});toast(`${kind==='order'?'Order':kind==='production'?'Production':'Wastage'} draft saved. You can continue later.`);}catch(e){toast(e.message,true)}}
  async function clearOperationalDraft(kind){try{await rpc('staff_draft_clear',{p_token:state.token,p_kind:kind});}catch(e){console.warn('Draft clear failed',e);}}
  function removeLine(kind,i){(kind==='production'?state.prodCart:state.wasteCart).splice(i,1);renderStaffCart(kind);}
  async function submitProduction(){try{const r=await rpc('submit_production',{p_token:state.token,p_items:state.prodCart});await clearOperationalDraft('production');state.prodCart=[];renderStaffCart('production');toast(`Production submitted (${r.count}).`);await staffHistory();}catch(e){toast(e.message,true)}}
  async function submitWastage(){try{const r=await rpc('submit_wastage',{p_token:state.token,p_items:state.wasteCart});await clearOperationalDraft('wastage');state.wasteCart=[];renderStaffCart('wastage');toast(`Wastage submitted (${r.count}).`);await staffHistory();}catch(e){toast(e.message,true)}}
  async function staffHistory(){ if(!state.token)return; try{const m=$('historyMonth').value||isoMonth();state.history=await rpc('staff_history',{p_token:state.token,p_month:m+'-01'}); populateHistorySuppliers();renderHistory();}catch(e){toast(e.message,true)} }
  function historyTab(btn,kind){document.querySelectorAll('#historyTabs button').forEach(b=>{b.classList.remove('active');b.classList.add('secondary')});btn.classList.add('active');btn.classList.remove('secondary');state.historyKind=kind;state.historyStatus='';renderHistory();}
  function populateHistorySuppliers(){const sel=$('histSupplier'),cur=sel.value;const vals=[...new Set((state.data.suppliers||[]).filter(x=>x.active!==false).map(x=>x.name).filter(Boolean))].sort((a,b)=>a.localeCompare(b));sel.innerHTML='<option value="">All suppliers</option>'+vals.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(vals.includes(cur))sel.value=cur;}
  function statusCardClick(status){state.historyStatus=state.historyStatus===status?'':status;renderHistory();}
  function renderHistory(){const kind=state.historyKind;const tools=$('orderHistoryTools');tools.classList.toggle('hidden',kind!=='orders');let rows=state.history[kind]||[];let cols,title;if(kind==='orders'){title='Order History';const statuses=['Pending','Ordered','Received','Not Received'];$('orderStatusCards').innerHTML=statuses.map(s=>`<div class="stat-card ${state.historyStatus===s?'active':''}" onclick="GoyaStaff.statusCard('${s}')"><span>${esc(s)}</span><strong>${rows.filter(x=>x.status===s).length}</strong></div>`).join('');const q=normalize($('histOrderSearch').value),od=$('histOrderDate').value,rd=$('histReceivedDate').value,sp=$('histSupplier').value;rows=rows.filter(x=>(!state.historyStatus||x.status===state.historyStatus)&&(!q||normalize(x.name).includes(q)||normalize(x.sku).includes(q))&&(!od||dateOnly(x.created_at)===od)&&(!rd||dateOnly(x.received_date)===rd)&&(!sp||x.supplier===sp));cols=['order_no','name','quantity','unit','supplier','status','received_date','notes','logged_by','created_at'];}else if(kind==='production'){title='Production History';cols=['name','sku','quantity','unit','logged_by','created_at'];}else if(kind==='wastage'){title='Wastage History';cols=['name','sku','quantity','unit','reason','logged_by','created_at'];}else{title='Inventory History';cols=['item_name','sku','section','storage_quantity','ingredients_quantity','counted_by','counted_at'];} $('historyTitle').textContent=title;$('historyHead').innerHTML=cols.map(c=>`<th>${esc(c.replaceAll('_',' '))}</th>`).join('');$('historyBody').innerHTML=rows.length?rows.map(r=>{const item=kind==='inventory'?((state.data.master_items||[]).find(i=>i.sku===r.sku)||(state.data.internal_items||[]).find(i=>i.sku===r.sku)||{}):{};return `<tr>${cols.map(c=>{let v=r[c];if(kind==='inventory'&&c==='storage_quantity')v=`${r[c]??''}${item.storage_unit?' '+item.storage_unit:''}`;if(kind==='inventory'&&c==='ingredients_quantity')v=`${r[c]??''}${item.ingredient_unit?' '+item.ingredient_unit:''}`;return `<td>${esc(c.includes('date')||c.includes('_at')||c==='created_at'?fmtDate(r[c]):v)}</td>`}).join('')}</tr>`}).join(''):`<tr><td colspan="${cols.length}" class="empty">No records.</td></tr>`;}
  function renderInfo(){const pages=state.data.info_pages||[];$('navInfo').classList.toggle('hidden',!pages.length);$('infoBody').innerHTML=pages.map(p=>`<div class="card"><div class="info-link"><div><h3>${esc(p.title)}</h3>${p.body?`<div style="margin-top:8px">${esc(p.body).replace(/\n/g,'<br>')}</div>`:''}</div>${p.url?`<a class="btn" href="${esc(p.url)}" target="_blank" rel="noopener">Open Page</a>`:''}</div></div>`).join('')||'<div class="empty">No active pages.</div>';}
  async function submitComplaint(){const type=$('complaintType').value,details=$('complaintDetails').value.trim(),hide=$('hideIdentity').checked;if(!details){toast('Write complaint/feedback details.',true);return;}try{await rpc('submit_complaint_feedback',{p_token:state.token,p_type:type,p_details:details,p_hide_identity:hide});$('complaintDetails').value='';$('hideIdentity').checked=false;toast('Submitted successfully.');}catch(e){toast(e.message,true)}}

  function allowedInventorySections(s){const mine=state.user.access?.sections||[];const listed=s.sections||[];return listed.filter(x=>mine.includes(x));}
  async function renderInventorySessions(){const box=$('inventoryBody'),sessions=state.data.inventory_sessions||[];if(!sessions.length){box.innerHTML='<div class="card empty">No active inventory count assigned to you.</div>';return;}box.innerHTML=sessions.map(s=>`<div class="card"><div class="section-title"><div><h3>${esc(s.title||'Inventory Count')}</h3><div class="small muted">${esc(s.month)} · Sections: ${esc((s.sections||[]).join(', '))}</div></div><span id="invStatus-${s.id}" class="pill received">Active</span></div>${s.notice_text?`<div class="notice-wrap"><div class="notice-marquee"><span>${esc(s.notice_text)}</span></div></div>`:''}<div class="field"><label>Section</label><select id="invsec-${s.id}" onchange="GoyaStaff.loadInventory('${s.id}')">${allowedInventorySections(s).map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div id="invwork-${s.id}" style="margin-top:12px"><div class="empty">Loading…</div></div></div>`).join('');for(const s of sessions){if(allowedInventorySections(s).length)await loadInventory(s.id);else $('invwork-'+s.id).innerHTML='<div class="empty">No matching assigned section.</div>';}}
  async function loadInventory(sessionId){const section=$('invsec-'+sessionId)?.value;if(!section)return;const key=sessionId+'|'+section;try{const d=await rpc('inventory_work',{p_token:state.token,p_session_id:sessionId,p_section:section});state.inventoryCache[key]=d;renderInventoryWork(sessionId,section,d);}catch(e){$('invwork-'+sessionId).innerHTML=`<div class="empty">${esc(e.message)}</div>`;}}
  function renderInventoryWork(sessionId,section,d){const target=$('invwork-'+sessionId);if(d.done){$('invStatus-'+sessionId).textContent='Done';$('invStatus-'+sessionId).className='pill done';target.innerHTML=`<div class="done-box">✓ Done — submitted ${esc(fmtDate(d.submitted_at))}</div>`;return;}$('invStatus-'+sessionId).textContent=d.draft?.length?'Draft':'Active';const vals=Object.fromEntries((d.draft||[]).map(x=>[x.sku,x]));target.innerHTML=`<div class="field"><label>Search items</label><input id="invSearch-${sessionId}" placeholder="Search item or SKU…" oninput="GoyaStaff.filterInventoryRows('${sessionId}')"></div><div class="table-wrap" style="margin-top:10px"><table class="table"><thead><tr><th>Item</th><th>SKU</th><th>Storage Qty</th><th>Ingredients Qty</th></tr></thead><tbody id="invRows-${sessionId}">${(d.items||[]).map(x=>{const v=vals[x.sku]||{};return `<tr data-invrow="${sessionId}" data-search="${esc((x.name+' '+x.sku).toLowerCase())}"><td>${esc(x.name)}<div class="small muted">${esc(x.source)}</div></td><td>${esc(x.sku)}</td><td><input data-sku="${esc(x.sku)}" data-kind="storage" type="number" min="0" step="0.001" value="${esc(v.storage_quantity??'')}"><span class="unit-hint">${esc(x.storage_unit||'')}</span></td><td><input data-sku="${esc(x.sku)}" data-kind="ingredient" type="number" min="0" step="0.001" value="${esc(v.ingredients_quantity??'')}"><span class="unit-hint">${esc(x.ingredient_unit||'')}</span></td></tr>`}).join('')}</tbody></table></div><div class="toolbar" style="margin-top:12px"><span class="small muted">All items must have both values before final submission. Zero is allowed.</span><span class="right"></span><button class="btn secondary" onclick="GoyaStaff.saveDraft('${sessionId}')">Save Draft</button><button class="btn ok" onclick="GoyaStaff.reviewInventory('${sessionId}')">Final Review & Submit</button></div>`;}
  function filterInventoryRows(sessionId){const q=normalize($('invSearch-'+sessionId).value);document.querySelectorAll(`[data-invrow="${sessionId}"]`).forEach(tr=>tr.classList.toggle('hidden',q&&!tr.dataset.search.includes(q)));}
  function collectInventory(sessionId){const section=$('invsec-'+sessionId).value,key=sessionId+'|'+section,d=state.inventoryCache[key],items=(d?.items||[]).map(x=>{const root=$('invRows-'+sessionId),s=root?.querySelector(`input[data-sku="${CSS.escape(x.sku)}"][data-kind="storage"]`),i=root?.querySelector(`input[data-sku="${CSS.escape(x.sku)}"][data-kind="ingredient"]`);return {item_name:x.name,sku:x.sku,section,source:x.source,storage_quantity:s?.value??'',ingredients_quantity:i?.value??''};});return {section,items};}
  async function saveDraft(sessionId){const {section,items}=collectInventory(sessionId);try{await rpc('inventory_save_draft',{p_token:state.token,p_session_id:sessionId,p_section:section,p_items:items});toast('Draft saved. You can continue later.');await loadInventory(sessionId);}catch(e){toast(e.message,true)}}
  function reviewInventory(sessionId){const {section,items}=collectInventory(sessionId),missing=items.filter(x=>x.storage_quantity===''||x.ingredients_quantity==='');if(missing.length){toast(`Complete all values first. ${missing.length} item(s) are incomplete.`,true);return;}state.pendingInventory={sessionId,section,items};$('reviewSummary').innerHTML=`Section: <strong>${esc(section)}</strong><br>Items: <strong>${items.length}</strong><br>Please confirm all quantities are final.`;$('reviewModal').classList.remove('hidden');$('confirmInventoryBtn').onclick=submitInventoryFinal;}
  function closeReview(){$('reviewModal').classList.add('hidden');state.pendingInventory=null;}
  async function submitInventoryFinal(){const p=state.pendingInventory;if(!p)return;try{await rpc('inventory_submit_final',{p_token:state.token,p_session_id:p.sessionId,p_section:p.section,p_items:p.items});closeReview();toast('Inventory submitted successfully. Done.');await loadInventory(p.sessionId);await staffHistory();}catch(e){toast(e.message,true)}}
  function myAttendanceToggle(){const off=$('myAttDayType')?.value==='Day Off';document.querySelectorAll('.my-att-duty').forEach(x=>x.classList.toggle('hidden',off));if(off){$('myAttSplit').checked=false;mySplitToggle();}}
  function mySplitToggle(){const split=!!$('myAttSplit')?.checked;document.querySelectorAll('.my-normal-shift').forEach(x=>x.classList.toggle('hidden',split));document.querySelectorAll('.my-split-shift').forEach(x=>x.classList.toggle('hidden',!split));}
  function minsLabel(m){m=Math.max(0,Number(m)||0);return `${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`;}
  function attTime(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?String(v).slice(11,16):d.toLocaleTimeString('en-AE',{hour:'numeric',minute:'2-digit'});}
  function staffAttendanceTs(date,time,isOut){if(!date||!time)return null;let d=date;if(isOut){const [h,m]=time.split(':').map(Number);if((h*60+m)<=120){const x=new Date(date+'T12:00:00');x.setDate(x.getDate()+1);d=x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-'+String(x.getDate()).padStart(2,'0')}}return d+'T'+time+':00'}
  async function submitMyAttendance(){const date=$('myAttDate').value,type=$('myAttDayType').value,off=type==='Day Off',split=!off&&!!$('myAttSplit')?.checked;if(!date)return toast('Select duty date.',true);let pin=null,pout=null,s2in=null,s2out=null;if(!off){if(split){const a=$('myAttS1In').value,b=$('myAttS1Out').value,c=$('myAttS2In').value,d=$('myAttS2Out').value;if(!a||!b||!c||!d)return toast('Complete both Split Shift time periods.',true);pin=staffAttendanceTs(date,a,false);pout=staffAttendanceTs(date,b,true);s2in=staffAttendanceTs(date,c,false);s2out=staffAttendanceTs(date,d,true);}else{const a=$('myAttIn').value,b=$('myAttOut').value;if(!a||!b)return toast('Duty Joined and Duty Finished are required.',true);pin=staffAttendanceTs(date,a,false);pout=staffAttendanceTs(date,b,true);}}try{await rpc('staff_attendance_submit_v10',{p_token:state.token,p_operational_date:date,p_punch_in:pin,p_punch_out:pout,p_break_taken:$('myAttBreak').value==='true',p_day_off:off,p_note:$('myAttNote').value.trim()||null,p_split_shift:split,p_shift2_in:s2in,p_shift2_out:s2out});toast('Attendance submitted and saved in your history.');$('myAttNote').value='';$('myAttMonth').value=date.slice(0,7);await loadMyAttendance();}catch(e){toast(e.message,true)}}
  async function loadMyAttendance(){if(!$('myAttMonth')||!state.token)return;const month=$('myAttMonth').value||isoMonth();try{const d=await rpc('staff_attendance_month_v10',{p_token:state.token,p_month:month+'-01'});state.myAttendance=d;const finals=d.records||[],subs=d.submissions||[];const finalMap=new Map(finals.map(x=>[x.operational_date,x]));const latestSub=new Map();for(const s of subs){if(!latestSub.has(s.operational_date))latestSub.set(s.operational_date,s)}const dates=[...new Set([...finals.map(x=>x.operational_date),...subs.map(x=>x.operational_date)])].sort();const rows=dates.map(date=>{const f=finalMap.get(date),s=latestSub.get(date);return {date,display:s||f,final:f,submission:s,recordType:s?(s.status==='Finalized'?'Finalized':'Submitted'):'Final'}});const calc=rows.map(x=>x.final).filter(Boolean),dayOff=rows.filter(x=>(x.display?.day_off)).length,presence=calc.reduce((a,x)=>a+(x.presence_minutes||0),0),net=calc.reduce((a,x)=>a+(x.net_work_minutes||0),0),ot=calc.reduce((a,x)=>a+(x.additional_minutes||0),0),late=calc.filter(x=>x.late_minutes>0).length;$('myAttSummary').textContent=`Records: ${rows.length} · Day Off: ${dayOff} · Final Net: ${minsLabel(net)} · Final OT: ${minsLabel(ot)} · Late days: ${late}`;const work=r=>{if(!r)return '—';if(r.day_off)return 'Day Off';const a=`${attTime(r.punch_in)} – ${attTime(r.punch_out)}`;return r.split_shift?`${a} / ${attTime(r.shift2_in)} – ${attTime(r.shift2_out)}`:a};const status=r=>!r?'—':r.day_off?'Day Off':(!r.punch_in?'Missing In':(!r.punch_out?'Missing Out':(r.split_shift&&(!r.shift2_in||!r.shift2_out)?'Missing Split Punch':'Duty')));$('myAttRows').innerHTML=rows.length?rows.map(x=>{const r=x.display,f=x.final;return `<tr><td>${esc(x.date)}</td><td>${esc(work(r))}</td><td>${f?esc(minsLabel(f.net_work_minutes)):'—'}</td><td>${f?.additional_minutes?`+${esc(minsLabel(f.additional_minutes))}`:'—'}</td><td>${f?.late_minutes?esc(f.late_minutes+' min'):'—'}</td><td>${r?.day_off?'—':(r?.break_taken?'Yes':'No')}</td><td>${esc(status(r))}</td><td>${esc(x.recordType)}</td></tr>`}).join(''):'<tr><td colspan="8" class="empty">No attendance records for this month.</td></tr>';$('myAttCards').innerHTML=rows.length?rows.map(x=>{const r=x.display,f=x.final;return `<div class="my-att-card"><div class="row"><strong>${esc(x.date)}</strong><span>${esc(x.recordType)}</span></div><div class="row"><span>Working Time</span><b>${esc(work(r))}</b></div><div class="row"><span>Final Net</span><b>${f?esc(minsLabel(f.net_work_minutes)):'—'}</b></div><div class="row"><span>Final Overtime</span><b class="ot">${f?.additional_minutes?`+${esc(minsLabel(f.additional_minutes))}`:'—'}</b></div></div>`}).join(''):'<div class="notice">No attendance records for this month.</div>';}catch(e){toast(e.message,true)}}
  function myAttendanceShareMode(){const mode=$('myAttShareMode')?.value||'month',p=$('myAttSharePicker');if(!p)return;p.type=mode==='day'?'date':'month';p.value=mode==='day'?new Date().toISOString().slice(0,10):($('myAttMonth')?.value||isoMonth())}
  function staffShareRows(){const d=state.myAttendance||{},mode=$('myAttShareMode')?.value||'month',pick=$('myAttSharePicker')?.value||($('myAttMonth')?.value||isoMonth()),finals=d.records||[],subs=d.submissions||[];const fm=new Map(finals.map(x=>[x.operational_date,x]));const sm=new Map();for(const s of subs){if(!sm.has(s.operational_date))sm.set(s.operational_date,s)}const dates=[...new Set([...finals.map(x=>x.operational_date),...subs.map(x=>x.operational_date)])].sort().filter(x=>mode==='day'?x===pick:x.startsWith(pick));return dates.map(date=>({date,display:sm.get(date)||fm.get(date),final:fm.get(date)}))}
  async function shareMyAttendanceWhatsApp(){if(!state.myAttendance)await loadMyAttendance();const rows=staffShareRows();if(!rows.length)return toast('No attendance found for selected period.',true);const work=r=>{if(r.day_off)return 'Day Off';const a=`${attTime(r.punch_in)} - ${attTime(r.punch_out)}`;return r.split_shift?`${a} / ${attTime(r.shift2_in)} - ${attTime(r.shift2_out)}`:a};let ot=0;const lines=rows.map(x=>{ot+=x.final?.additional_minutes||0;return `${x.date} | ${work(x.display)} | OT ${x.final?.additional_minutes?minsLabel(x.final.additional_minutes):'—'}`});const label=$('myAttSharePicker')?.value||$('myAttMonth').value;const msg=`GOYA - Staff Attendance
Staff: ${state.user.name}
Period: ${label}

${lines.join('\n')}

Total OT: ${minsLabel(ot)}`;window.open('https://wa.me/?text='+encodeURIComponent(msg),'_blank')}
  async function shareMyAttendance(){if(!state.myAttendance)await loadMyAttendance();const rows=staffShareRows();if(!rows.length)return toast('No attendance found for selected period.',true);if(!window.jspdf?.jsPDF)return toast('PDF library is still loading. Please try again.',true);const work=r=>{if(r.day_off)return 'Day Off';const a=`${attTime(r.punch_in)} - ${attTime(r.punch_out)}`;return r.split_shift?`${a} / ${attTime(r.shift2_in)} - ${attTime(r.shift2_out)}`:a};const ot=rows.reduce((a,x)=>a+(x.final?.additional_minutes||0),0),net=rows.reduce((a,x)=>a+(x.final?.net_work_minutes||0),0),label=$('myAttSharePicker')?.value||$('myAttMonth').value;const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(17);doc.text('GOYA - Staff Attendance Report',14,18);doc.setFontSize(11);doc.text(`Staff: ${state.user.name}`,14,27);doc.text(`Period: ${label}`,14,34);doc.text(`Final Net Working: ${minsLabel(net)}    Total Overtime: ${minsLabel(ot)}`,14,41);doc.autoTable({startY:48,head:[['Date','Working Time','Overtime']],body:rows.map(x=>[x.date,work(x.display),x.final?.additional_minutes?minsLabel(x.final.additional_minutes):'—']),foot:[['','Total Overtime',minsLabel(ot)]],styles:{fontSize:10,cellPadding:3},headStyles:{fillColor:[38,59,52]},footStyles:{fontStyle:'bold'}});const name=`Goya_Attendance_${state.user.name.replace(/[^a-z0-9]+/gi,'_')}_${label}.pdf`;doc.save(name);toast('PDF downloaded.')}
  async function staffLogout(){try{if(state.token)await rpc('logout',{p_token:state.token});}catch{} state.token=null;state.user=null;location.reload();}

  window.GoyaStaff={staffLogin,nav:staffNav,mobileMenu,searchMaster,pickOrderItem,addOrderLine,setOrderNote,removeOrder,submitOrder,searchItems,pickItem,addLine,removeLine,submitProduction,submitWastage,staffHistory,historyTab,renderHistory,statusCard:statusCardClick,submitComplaint,loadInventory,filterInventoryRows,saveDraft,reviewInventory,closeReview,saveOperationalDraft,myAttendanceToggle,mySplitToggle,myAttendanceShareMode,submitMyAttendance,loadMyAttendance,shareMyAttendanceWhatsApp,shareMyAttendance,staffLogout};

  // ---------- ADMIN ----------
  async function adminLogin(){const pin=$('adminPin').value.trim();if(!/^\d{4,12}$/.test(pin)){toast('Enter your Admin PIN.',true);return;}try{const d=await rpc('admin_login',{p_pin:pin});state.token=d.token;await adminLoad();$('adminLogin').classList.add('hidden');$('adminApp').classList.remove('hidden');$('adminPin').value='';toast('Admin panel unlocked.');}catch(e){toast(e.message,true)}}
  async function adminLoad(){state.adminData=await rpc('admin_bootstrap',{p_token:state.token});renderAdminAll();await loadAdminOrders();await refreshDashboard();}
  function adminNav(btn,id){setNav(btn);showView(id);$('sidebar').classList.remove('open');if(id==='adminComplaints')loadComplaints();if(id==='adminPW')loadPW();if(id==='adminInventory')loadInventoryCounts();}
  function adminMobile(){ $('sidebar').classList.toggle('open'); }
  function renderAdminAll(){renderMaster();renderInternal();renderSuppliers();renderStaff();renderInventoryAdmin();renderInfoAdmin();renderSettings();$('statItems').textContent=(state.adminData.master_items||[]).length;$('statInternal').textContent=(state.adminData.internal_items||[]).length;$('statStaff').textContent=(state.adminData.staff||[]).filter(x=>x.active).length;$('statSuppliers').textContent=(state.adminData.suppliers||[]).filter(x=>x.active).length;populateAdminSelects();}
  async function refreshDashboard(){try{const orders=state.adminOrders||[];const countStatus=s=>orders.filter(x=>normalize(x.status)===normalize(s)).length;$('dashOrderPending').textContent=countStatus('Pending');$('dashOrderOrdered').textContent=countStatus('Ordered');$('dashOrderReceived').textContent=countStatus('Received');$('dashOrderNotReceived').textContent=countStatus('Not Received');$('dashInventoryActive').textContent=(state.adminData.inventory_sessions||[]).filter(x=>x.active).length;const recent=orders.slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,8);$('dashRecentOrders').innerHTML=recent.length?recent.map(x=>`<tr><td>${esc(x.order_no)}</td><td>${esc(x.name)}</td><td>${esc(x.supplier||'')}</td><td>${pill(x.status)}</td><td>${esc(x.logged_by||'')}</td><td>${esc(fmtDate(x.created_at))}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No recent orders.</td></tr>';const now=new Date(),from=new Date(now.getFullYear(),now.getMonth(),1).toISOString(),to=new Date(now.getFullYear(),now.getMonth()+1,1).toISOString();const [prod,waste,complaints]=await Promise.all([rpc('admin_production_wastage',{p_token:state.token,p_kind:'production',p_from:from,p_to:to,p_status:'Pending'}),rpc('admin_production_wastage',{p_token:state.token,p_kind:'wastage',p_from:from,p_to:to,p_status:'Pending'}),rpc('admin_complaints',{p_token:state.token,p_month:isoMonth()+'-01'})]);$('dashProdPending').textContent=(prod||[]).length;$('dashWastePending').textContent=(waste||[]).length;$('dashComplaints').textContent=(complaints||[]).length;}catch(e){console.warn('Dashboard refresh failed',e);}}
  function populateAdminSelects(){const suppliers=(state.adminData.suppliers||[]).filter(x=>x.active!==false);$('orderSupplierFilter').innerHTML='<option value="">All suppliers</option>'+suppliers.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');const ms=$('masterSupplier');if(ms){const cur=ms.value;ms.innerHTML='<option value="">Select supplier</option>'+suppliers.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');if([...ms.options].some(o=>o.value===cur))ms.value=cur;}const mf=$('masterListSupplier');if(mf){const cur=mf.value;mf.innerHTML='<option value="">All suppliers</option>'+suppliers.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');if([...mf.options].some(o=>o.value===cur))mf.value=cur;}$('invAssigned').innerHTML=(state.adminData.staff||[]).filter(x=>x.active).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');}
  function renderMaster(){const q=normalize($('masterListSearch')?.value),sp=$('masterListSupplier')?.value||'',tp=$('masterListType')?.value||'';const all=state.adminData.master_items||[];const rows=all.filter(x=>(!q||normalize(x.name).includes(q)||normalize(x.sku).includes(q))&&(!sp||x.supplier===sp)&&(!tp||normalize(x.items_type)===normalize(tp)));if($('masterFilterCount'))$('masterFilterCount').textContent=`Showing ${rows.length} of ${all.length}`;$('masterBody').innerHTML=rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.sku)}</td><td>${esc(x.storage_unit)}</td><td>${esc(x.ingredient_unit)}</td><td>${esc(x.supplier||'')}</td><td>${esc(x.items_type)}</td><td><div class="toolbar"><button class="btn secondary tiny" onclick="GoyaAdmin.editMaster('${x.id}')">Edit</button><button class="btn danger tiny" onclick="GoyaAdmin.deleteItem('master_items','${x.id}')">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No matching master items.</td></tr>';}
  function editMaster(id){const x=(state.adminData.master_items||[]).find(y=>y.id===id);if(!x)return;$('masterId').value=x.id;$('masterName').value=x.name;$('masterSku').value=x.sku;$('masterStorage').value=x.storage_unit;$('masterIngredient').value=x.ingredient_unit;$('masterSupplier').value=x.supplier||'';$('masterType').value=sectionNames.find(s=>normalize(s)===normalize(x.items_type))||'Bar';$('masterFormTitle').textContent='Edit Master Item';}
  function resetMasterForm(){['masterId','masterName','masterSku','masterStorage','masterIngredient','masterSupplier'].forEach(id=>$(id).value='');$('masterType').value='Bar';$('masterFormTitle').textContent='Add Master Item';}
  async function saveMasterItem(){const row={id:$('masterId').value||null,name:$('masterName').value.trim(),sku:$('masterSku').value.trim(),storage_unit:$('masterStorage').value.trim(),ingredient_unit:$('masterIngredient').value.trim(),supplier:$('masterSupplier').value.trim(),items_type:$('masterType').value};if(!row.name||!row.sku||!row.storage_unit||!row.ingredient_unit){toast('Name, SKU and both units are required.',true);return;}try{await rpc('admin_save_master_item',{p_token:state.token,p_row:row});resetMasterForm();await adminLoad();toast('Master item saved.');}catch(e){toast(e.message,true)}}
  function renderInternal(){const q=normalize($('internalListSearch')?.value),tp=$('internalListType')?.value||'';const all=state.adminData.internal_items||[];const rows=all.filter(x=>(!q||normalize(x.name).includes(q)||normalize(x.sku).includes(q))&&(!tp||normalize(x.items_type)===normalize(tp)));if($('internalFilterCount'))$('internalFilterCount').textContent=`Showing ${rows.length} of ${all.length}`;$('internalBody').innerHTML=rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.sku)}</td><td>${esc(x.storage_unit)}</td><td>${esc(x.ingredient_unit)}</td><td>${esc(x.items_type)}</td><td><div class="toolbar"><button class="btn secondary tiny" onclick="GoyaAdmin.editInternal('${x.id}')">Edit</button><button class="btn danger tiny" onclick="GoyaAdmin.deleteItem('internal_items','${x.id}')">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No matching internal items.</td></tr>';}
  function editInternal(id){const x=(state.adminData.internal_items||[]).find(y=>y.id===id);if(!x)return;$('internalId').value=x.id;$('internalName').value=x.name;$('internalSku').value=x.sku;$('internalStorage').value=x.storage_unit;$('internalIngredient').value=x.ingredient_unit;$('internalType').value=sectionNames.find(s=>normalize(s)===normalize(x.items_type))||'Bar';$('internalFormTitle').textContent='Edit Internal Item';}
  function resetInternalForm(){['internalId','internalName','internalSku','internalStorage','internalIngredient'].forEach(id=>$(id).value='');$('internalType').value='Bar';$('internalFormTitle').textContent='Add Internal Item';}
  async function saveInternalItem(){const row={id:$('internalId').value||null,name:$('internalName').value.trim(),sku:$('internalSku').value.trim(),storage_unit:$('internalStorage').value.trim(),ingredient_unit:$('internalIngredient').value.trim(),items_type:$('internalType').value};if(!row.name||!row.sku||!row.storage_unit||!row.ingredient_unit){toast('Name, SKU and both units are required.',true);return;}try{await rpc('admin_save_internal_item',{p_token:state.token,p_row:row});resetInternalForm();await adminLoad();toast('Internal item saved.');}catch(e){toast(e.message,true)}}
  async function deleteItem(table,id){if(!confirm('Delete this item?'))return;try{await rpc('admin_delete_item',{p_token:state.token,p_table:table,p_id:id});await adminLoad();toast('Item deleted.');}catch(e){toast(e.message,true)}}
  function renderSuppliers(){$('supplierBody').innerHTML=(state.adminData.suppliers||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone||'')}</td><td>${esc(x.email||'')}</td><td>${x.active?'Yes':'No'}</td><td><div class="toolbar"><button class="btn secondary tiny" onclick="GoyaAdmin.editSupplier('${x.id}')">Edit</button><button class="btn danger tiny" onclick="GoyaAdmin.deleteSupplier('${x.id}')">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No suppliers.</td></tr>';}
  function editSupplier(id){const x=(state.adminData.suppliers||[]).find(y=>y.id===id);if(!x)return;$('supplierId').value=x.id;$('supplierName').value=x.name;$('supplierPhone').value=x.phone||'';$('supplierEmail').value=x.email||'';}
  function resetSupplierForm(){['supplierId','supplierName','supplierPhone','supplierEmail'].forEach(id=>$(id).value='');}
  async function saveSupplier(){const row={id:$('supplierId').value||null,name:$('supplierName').value.trim(),phone:$('supplierPhone').value.trim(),email:$('supplierEmail').value.trim(),active:true};if(!row.name){toast('Supplier name required.',true);return;}try{await rpc('admin_save_supplier',{p_token:state.token,p_row:row});resetSupplierForm();await adminLoad();toast('Supplier saved.');}catch(e){toast(e.message,true)}}
  async function deleteSupplier(id){if(!confirm('Delete this supplier?'))return;try{await rpc('admin_delete_supplier',{p_token:state.token,p_id:id});await adminLoad();toast('Supplier deleted.');}catch(e){toast(e.message,true)}}
  function renderStaff(){$('staffBody').innerHTML=(state.adminData.staff||[]).map(x=>`<tr><td>${esc(x.name)}</td><td><strong>${esc(x.pin_code||'Reset PIN')}</strong></td><td>${x.active?'Active':'Inactive'}</td><td>${x.can_order?'✓':'—'}</td><td>${x.can_production?'✓':'—'}</td><td>${x.can_wastage?'✓':'—'}</td><td>${x.can_inventory?'✓':'—'}</td><td>${esc((x.sections||[]).join(', '))}</td><td><div class="toolbar"><button class="btn secondary tiny" onclick="GoyaAdmin.editStaff('${x.id}')">Edit</button><button class="btn danger tiny" onclick="GoyaAdmin.deleteStaff('${x.id}')">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No staff.</td></tr>';}
  function editStaff(id){const x=(state.adminData.staff||[]).find(y=>y.id===id);if(!x)return;$('staffId').value=x.id;$('staffName').value=x.name;$('staffPinNew').value=x.pin_code||'';$('staffActive').checked=x.active;$('canOrder').checked=x.can_order;$('canProd').checked=x.can_production;$('canWaste').checked=x.can_wastage;$('canInv').checked=x.can_inventory;setSectionsChecked('staffSection',x.sections||[]);}
  function resetStaffForm(){['staffId','staffName','staffPinNew'].forEach(id=>$(id).value='');$('staffActive').checked=true;$('canOrder').checked=true;$('canProd').checked=true;$('canWaste').checked=true;$('canInv').checked=false;setSectionsChecked('staffSection',[]);}
  async function saveStaff(){const row={id:$('staffId').value||null,name:$('staffName').value.trim(),pin:$('staffPinNew').value.trim(),active:$('staffActive').checked,can_order:$('canOrder').checked,can_production:$('canProd').checked,can_wastage:$('canWaste').checked,can_inventory:$('canInv').checked,sections:sectionsChecked('staffSection')};if(!row.name||!/^\d{4}$/.test(row.pin)){toast('Staff name and 4-digit PIN are required.',true);return;}try{await rpc('admin_save_staff',{p_token:state.token,p_row:row});resetStaffForm();await adminLoad();toast('Staff saved.');}catch(e){toast(e.message,true)}}
  async function deleteStaff(id){if(!confirm('Delete this staff?'))return;try{await rpc('admin_delete_staff',{p_token:state.token,p_id:id});await adminLoad();toast('Staff deleted.');}catch(e){toast(e.message,true)}}

  async function loadAdminOrders(){try{const from=$('orderFrom')?.value||null,to=$('orderTo')?.value?new Date($('orderTo').value+'T23:59:59').toISOString():null;state.adminOrders=await rpc('admin_orders',{p_token:state.token,p_from:from,p_to:to,p_status:$('orderStatusFilter')?.value||null,p_supplier:$('orderSupplierFilter')?.value||null,p_search:$('orderAdminSearch')?.value.trim()||null});renderAdminOrders();}catch(e){toast(e.message,true)}}
  function renderAdminOrders(){$('adminOrdersBody').innerHTML=state.adminOrders.length?state.adminOrders.map(x=>`<tr><td><input class="orderCheck" type="checkbox" value="${x.id}" onchange="GoyaAdmin.updateSelectionCount('orderCheck')"></td><td>${esc(x.order_no)}</td><td>${esc(x.name)}<div class="small muted">${esc(x.sku)}</div></td><td><div class="qty-edit"><input id="orderQtyEdit-${x.id}" type="number" min="0.001" step="0.001" value="${esc(x.quantity)}" aria-label="Quantity for ${esc(x.name)}"><button class="btn secondary tiny" onclick="GoyaAdmin.updateOrderQuantity(${x.id})">Save</button></div></td><td>${esc(x.unit)}</td><td>${esc(x.supplier||'')}</td><td>${pill(x.status)}</td><td>${esc(x.received_date||'')}</td><td>${esc(x.logged_by)}</td><td>${esc(fmtDate(x.created_at))}</td><td>${esc(x.notes||'')}</td></tr>`).join(''):'<tr><td colspan="11" class="empty">No orders.</td></tr>';updateSelectionCount('orderCheck');}
  function selectedChecks(cls){return [...document.querySelectorAll('.'+cls+':checked')].map(x=>x.value);}
  function selectionCounterId(cls){return {orderCheck:'orderSelectedCount',pwCheck:'pwSelectedCount',invCountCheck:'invSelectedCount',complaintCheck:'complaintSelectedCount'}[cls]||null;}
  function updateSelectionCount(cls){const id=selectionCounterId(cls),el=id?$(id):null;if(el)el.textContent=`Selected: ${selectedChecks(cls).length}`;}
  function toggleChecks(cls,val){document.querySelectorAll('.'+cls).forEach(x=>x.checked=val);updateSelectionCount(cls);}
  async function bulkOrderStatus(){const ids=selectedChecks('orderCheck').map(Number);if(!ids.length){toast('Select order rows first.',true);return;}try{await rpc('admin_update_orders',{p_token:state.token,p_ids:ids,p_status:$('bulkStatus').value,p_notes:$('bulkNotes').value.trim()||null});await loadAdminOrders();toast('Order status updated.');}catch(e){toast(e.message,true)}}
  async function deleteSelectedOrders(){const ids=selectedChecks('orderCheck').map(Number);if(!ids.length)return toast('Select order rows first.',true);if(!confirm('Delete selected order rows?'))return;try{await rpc('admin_delete_orders',{p_token:state.token,p_ids:ids});await loadAdminOrders();toast('Deleted.');}catch(e){toast(e.message,true)}}
  async function updateOrderQuantity(id){const el=$('orderQtyEdit-'+id),quantity=Number(el?.value);if(!Number.isFinite(quantity)||quantity<=0){toast('Quantity must be greater than zero.',true);return;}try{await rpc('admin_update_order_quantity',{p_token:state.token,p_id:id,p_quantity:quantity});await loadAdminOrders();toast('Order quantity updated.');}catch(e){toast(e.message,true)}}
  function clearOrderFilters(){['orderAdminSearch','orderFrom','orderTo'].forEach(id=>$(id).value='');$('orderStatusFilter').value='';$('orderSupplierFilter').value='';loadAdminOrders();}
  function exportOrdersFoodics(){const masters=state.adminData.master_items||[];const rows=state.adminOrders.map(x=>{const m=masters.find(z=>z.sku===x.sku)||{};return {name:x.name,sku:x.sku,order_quantity:x.quantity,storage_quantity:normalize(x.unit)===normalize(m.storage_unit)?x.quantity:'',total_cost:''}});csv(rows,['name','sku','order_quantity','storage_quantity','total_cost'],'purchase_order.csv');}
  function whatsappSupplier(){const rows=state.adminOrders;if(!rows.length)return toast('No filtered orders.',true);const groups={};rows.forEach(x=>{const k=x.supplier||'Unassigned';(groups[k]??=[]).push(x)});const msg=Object.entries(groups).map(([s,rs])=>`Supplier: ${s}\n`+rs.map(r=>`- ${r.name}: ${r.quantity} ${r.unit}${r.notes&&r.notes.trim()?` (${r.notes.trim()})`:''}`).join('\n')).join('\n\n');window.open('https://wa.me/?text='+encodeURIComponent(msg),'_blank');}

  async function loadPW(){try{const from=$('pwFrom').value||null,to=$('pwTo').value?new Date($('pwTo').value+'T23:59:59').toISOString():null;state.pwRows=await rpc('admin_production_wastage',{p_token:state.token,p_kind:$('pwKind').value,p_from:from,p_to:to,p_status:$('pwStatusFilter').value||null});renderPW();}catch(e){toast(e.message,true)}}
  function renderPW(){$('pwBody').innerHTML=state.pwRows.length?state.pwRows.map(x=>`<tr><td><input class="pwCheck" type="checkbox" value="${x.id}" onchange="GoyaAdmin.updateSelectionCount('pwCheck')"></td><td>${esc(x.name)}</td><td>${esc(x.sku)}</td><td>${x.storage_quantity==null?'':esc(x.storage_quantity)+' '+esc(x.unit||'')}</td><td>${x.ingredients_quantity==null?'':esc(x.ingredients_quantity)+' '+esc(x.unit||'')}</td><td>${esc(x.reason||'')}</td><td>${esc(x.logged_by)}</td><td>${esc(fmtDate(x.created_at))}</td><td>${pill(x.admin_status||'Pending')}</td></tr>`).join(''):'<tr><td colspan="9" class="empty">No records.</td></tr>';updateSelectionCount('pwCheck');}
  async function bulkPWStatus(){const ids=selectedChecks('pwCheck').map(Number);if(!ids.length)return toast('Select rows first.',true);try{await rpc('admin_update_pw_status',{p_token:state.token,p_kind:$('pwKind').value,p_ids:ids,p_status:$('pwBulkStatus').value});await loadPW();toast('Processing status updated.');}catch(e){toast(e.message,true)}}
  async function deleteSelectedPW(){const ids=selectedChecks('pwCheck').map(Number);if(!ids.length)return toast('Select rows first.',true);if(!confirm('Permanently delete the selected history records?'))return;try{await rpc('admin_delete_history_rows',{p_token:state.token,p_kind:$('pwKind').value,p_ids:ids});await loadPW();await refreshDashboard();toast('Selected history deleted.');}catch(e){toast(e.message,true)}}
  function exportPWFoodics(){const grouped=new Map();state.pwRows.forEach(x=>{const key=normalize(x.sku)||normalize(x.name);if(!grouped.has(key))grouped.set(key,{name:x.name,sku:x.sku,storage_quantity:0,ingredients_quantity:0,hasStorage:false,hasIngredients:false});const r=grouped.get(key);const s=Number(x.storage_quantity),i=Number(x.ingredients_quantity);if(x.storage_quantity!==null&&x.storage_quantity!==''&&Number.isFinite(s)){r.storage_quantity+=s;r.hasStorage=true;}if(x.ingredients_quantity!==null&&x.ingredients_quantity!==''&&Number.isFinite(i)){r.ingredients_quantity+=i;r.hasIngredients=true;}});const rows=[...grouped.values()].map(r=>({name:r.name,sku:r.sku,storage_quantity:r.hasStorage?r.storage_quantity:'',ingredients_quantity:r.hasIngredients?r.ingredients_quantity:''}));csv(rows,['name','sku','storage_quantity','ingredients_quantity'],`${$('pwKind').value}.csv`);}

  function renderInventoryAdmin(){$('inventorySessionBody').innerHTML=(state.adminData.inventory_sessions||[]).map(x=>`<tr><td>${esc(x.month)}</td><td>${esc(x.title||'')}</td><td>${x.active?'Active':'Inactive'}</td><td>${esc((x.sections||[]).join(', '))}</td><td>${esc((x.assigned_names||[]).join(', '))}</td><td>${esc(x.notice_text||'')}</td><td><div class="toolbar"><button class="btn secondary tiny" onclick="GoyaAdmin.editInventory('${x.id}')">Edit</button><button class="btn danger tiny" onclick="GoyaAdmin.deleteInventory('${x.id}')">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No sessions.</td></tr>';populateInventoryResetSelectors();}
  function populateInventoryResetSelectors(){const el=$('invResetSession');if(!el)return;const cur=el.value;const sessions=state.adminData.inventory_sessions||[];el.innerHTML='<option value="">Select session</option>'+sessions.map(x=>`<option value="${x.id}">${esc(x.title||'Inventory Count')} — ${esc(String(x.month).slice(0,7))}</option>`).join('');if(sessions.some(x=>x.id===cur))el.value=cur;refreshInventoryResetOptions();}
  function refreshInventoryResetOptions(){const sid=$('invResetSession')?.value,staffEl=$('invResetStaff'),secEl=$('invResetSection');if(!staffEl||!secEl)return;const session=(state.adminData.inventory_sessions||[]).find(x=>x.id===sid);if(!session){staffEl.innerHTML='<option value="">Select staff</option>';secEl.innerHTML='<option value="">Select section</option>';return;}const assigned=session.assigned_staff_ids||[];let staff=(state.adminData.staff||[]).filter(x=>x.active!==false);if(assigned.length)staff=staff.filter(x=>assigned.includes(x.id));staffEl.innerHTML='<option value="">Select staff</option>'+staff.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');secEl.innerHTML='<option value="">Select section</option>'+((session.sections||[]).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join(''));}
  async function resetInventorySubmission(){const sessionId=$('invResetSession')?.value,staffId=$('invResetStaff')?.value,section=$('invResetSection')?.value;if(!sessionId||!staffId||!section){toast('Select inventory session, staff and section.',true);return;}const staff=(state.adminData.staff||[]).find(x=>x.id===staffId),session=(state.adminData.inventory_sessions||[]).find(x=>x.id===sessionId);if(!confirm(`Reset and reopen ${section} inventory count for ${staff?.name||'this staff'} in ${session?.title||'this session'}? Existing count rows and draft for this staff/section will be cleared.`))return;try{await rpc('admin_inventory_reset_count',{p_token:state.token,p_session_id:sessionId,p_staff_id:staffId,p_section:section});await adminLoad();await loadInventoryCounts();toast('Inventory count reopened. Staff can submit again.');}catch(e){toast(e.message,true)}}
  function editInventory(id){const x=(state.adminData.inventory_sessions||[]).find(y=>y.id===id);if(!x)return;$('invId').value=x.id;$('invSessionMonth').value=String(x.month).slice(0,7);$('invTitle').value=x.title||'';$('invNotice').value=x.notice_text||'';$('invActive').checked=x.active;setSectionsChecked('invSection',x.sections||[]);[...$('invAssigned').options].forEach(o=>o.selected=(x.assigned_staff_ids||[]).includes(o.value));}
  function resetInventoryForm(){['invId','invTitle','invNotice'].forEach(id=>$(id).value='');$('invSessionMonth').value=isoMonth();$('invActive').checked=false;setSectionsChecked('invSection',[]);[...$('invAssigned').options].forEach(o=>o.selected=false);}
  async function saveInventorySession(){const month=$('invSessionMonth').value,row={id:$('invId').value||null,month:month?month+'-01':null,title:$('invTitle').value.trim(),notice_text:$('invNotice').value.trim(),active:$('invActive').checked,sections:sectionsChecked('invSection'),assigned_staff_ids:[...$('invAssigned').selectedOptions].map(o=>o.value)};if(!row.month||!row.sections.length){toast('Choose month and at least one section.',true);return;}try{await rpc('admin_inventory_save_session',{p_token:state.token,p_row:row});resetInventoryForm();await adminLoad();toast('Inventory session saved.');}catch(e){toast(e.message,true)}}
  async function deleteInventory(id){if(!confirm('Delete this inventory session?'))return;try{await rpc('admin_delete_inventory_session',{p_token:state.token,p_id:id});await adminLoad();toast('Deleted.');}catch(e){toast(e.message,true)}}
  async function loadInventoryCounts(){try{const m=$('invCountMonth').value||isoMonth();state.inventoryRows=await rpc('admin_inventory_counts',{p_token:state.token,p_month:m+'-01',p_section:$('invCountSection').value||null});$('inventoryCountsBody').innerHTML=state.inventoryRows.length?state.inventoryRows.map(x=>{const item=(state.adminData.master_items||[]).find(i=>i.sku===x.sku)||(state.adminData.internal_items||[]).find(i=>i.sku===x.sku)||{};return `<tr><td><input class="invCountCheck" type="checkbox" value="${x.id}" onchange="GoyaAdmin.updateSelectionCount('invCountCheck')"></td><td>${esc(x.item_name)}</td><td>${esc(x.sku)}</td><td>${esc(x.section)}</td><td>${esc(x.storage_quantity??'')} ${esc(item.storage_unit||'')}</td><td>${esc(x.ingredients_quantity??'')} ${esc(item.ingredient_unit||'')}</td><td>${esc(x.counted_by||'')}</td><td>${esc(fmtDate(x.counted_at))}</td></tr>`}).join(''):'<tr><td colspan="8" class="empty">No inventory counts.</td></tr>';updateSelectionCount('invCountCheck');}catch(e){toast(e.message,true)}}
  function exportInventoryFoodics(){const rows=state.inventoryRows.map(x=>({'Inventory Item Name':x.item_name,'Inventory Item SKU':x.sku,'Storage quantity':x.storage_quantity??'','Ingredients quantity':x.ingredients_quantity??'','Inventory Count ID':''}));csv(rows,['Inventory Item Name','Inventory Item SKU','Storage quantity','Ingredients quantity','Inventory Count ID'],'foodics-inventory-count.csv');}
  async function deleteSelectedInventoryCounts(){const ids=selectedChecks('invCountCheck').map(Number);if(!ids.length)return toast('Select inventory history rows first.',true);if(!confirm('Permanently delete the selected inventory history records?'))return;try{await rpc('admin_delete_history_rows',{p_token:state.token,p_kind:'inventory',p_ids:ids});await loadInventoryCounts();toast('Selected inventory history deleted.');}catch(e){toast(e.message,true)}}

  async function loadComplaints(){try{const m=$('complaintMonth').value||isoMonth();state.complaints=await rpc('admin_complaints',{p_token:state.token,p_month:m+'-01'});renderComplaints();}catch(e){toast(e.message,true)}}
  function filteredComplaints(){const t=$('complaintAdminType').value,q=normalize($('complaintAdminSearch').value);return state.complaints.filter(x=>(!t||x.type===t)&&(!q||normalize(x.details).includes(q)||normalize(x.staff_name).includes(q)));}
  function renderComplaints(){const rows=filteredComplaints();$('complaintAdminBody').innerHTML=rows.length?rows.map(x=>`<tr><td><input class="complaintCheck" type="checkbox" value="${x.id}" onchange="GoyaAdmin.updateSelectionCount('complaintCheck')"></td><td>${pill(x.type)}</td><td style="min-width:320px;white-space:pre-wrap">${esc(x.details)}</td><td>${esc(x.staff_name)}</td><td>${x.hide_identity?'Yes':'No'}</td><td>${esc(fmtDate(x.created_at))}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No records.</td></tr>';updateSelectionCount('complaintCheck');}
  function exportComplaintsExcel(){const rows=filteredComplaints().map(x=>({Type:x.type,Details:x.details,'Submitted By':x.staff_name,'Hide identify':x.hide_identity?'Yes':'No','Date & Time':fmtDate(x.created_at)}));excel(rows,`Goya_Complain_Feedback_${$('complaintMonth').value||'month'}.xlsx`,'Complain Feedback');}
  async function deleteSelectedComplaints(){const ids=selectedChecks('complaintCheck').map(Number);if(!ids.length)return toast('Select complaint/feedback rows first.',true);if(!confirm('Permanently delete the selected complaint/feedback history?'))return;try{await rpc('admin_delete_history_rows',{p_token:state.token,p_kind:'complaints',p_ids:ids});await loadComplaints();await refreshDashboard();toast('Selected records deleted.');}catch(e){toast(e.message,true)}}

  function renderInfoAdmin(){$('infoAdminBody').innerHTML=(state.adminData.info_pages||[]).map(x=>`<tr><td>${esc(x.title)}</td><td>${x.url?`<a href="${esc(x.url)}" target="_blank">Open</a>`:''}</td><td>${x.active?'Yes':'No'}</td><td>${x.sort_order}</td><td><div class="toolbar"><button class="btn secondary tiny" onclick="GoyaAdmin.editInfo('${x.id}')">Edit</button><button class="btn danger tiny" onclick="GoyaAdmin.deleteInfo('${x.id}')">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No pages.</td></tr>';}
  function editInfo(id){const x=(state.adminData.info_pages||[]).find(y=>y.id===id);if(!x)return;$('infoId').value=x.id;$('infoTitle').value=x.title;$('infoUrl').value=x.url||'';$('infoBodyText').value=x.body||'';$('infoSort').value=x.sort_order;$('infoActive').checked=x.active;}
  function resetInfoForm(){['infoId','infoTitle','infoUrl','infoBodyText'].forEach(id=>$(id).value='');$('infoSort').value=0;$('infoActive').checked=true;}
  async function saveInfo(){const row={id:$('infoId').value||null,title:$('infoTitle').value.trim(),url:$('infoUrl').value.trim(),body:$('infoBodyText').value,sort_order:Number($('infoSort').value||0),active:$('infoActive').checked};if(!row.title){toast('Title required.',true);return;}try{await rpc('admin_save_info_page',{p_token:state.token,p_row:row});resetInfoForm();await adminLoad();toast('Additional page saved.');}catch(e){toast(e.message,true)}}
  async function deleteInfo(id){if(!confirm('Delete this page?'))return;try{await rpc('admin_delete_info_page',{p_token:state.token,p_id:id});await adminLoad();toast('Deleted.');}catch(e){toast(e.message,true)}}
  function renderSettings(){const s=state.adminData.settings||{};$('managerEmail').value=s.admin?.email||cfg.MANAGER_EMAIL||'mehedi.src@gmail.com';$('waPhone').value=s.whatsapp?.phone||'';}
  async function saveSettings(){try{await rpc('admin_save_settings',{p_token:state.token,p_settings:{admin:{email:$('managerEmail').value.trim()},whatsapp:{phone:$('waPhone').value.trim()}}});await adminLoad();toast('Settings saved.');}catch(e){toast(e.message,true)}}
  async function changeAdminPin(){const current=$('adminPinCurrent').value.trim(),next=$('adminPinNew').value.trim(),confirmPin=$('adminPinConfirm').value.trim();if(!/^\d{4,12}$/.test(next)||next!==confirmPin){toast('New PIN must match and be 4–12 digits.',true);return;}try{await rpc('admin_change_pin',{p_token:state.token,p_current_pin:current,p_new_pin:next});['adminPinCurrent','adminPinNew','adminPinConfirm'].forEach(id=>$(id).value='');toast('Admin PIN changed. Use the new PIN next login.');}catch(e){toast(e.message,true)}}

  function normalizeImportRow(kind,r){const get=(...names)=>{for(const n of names){const k=Object.keys(r).find(x=>normalize(x).replace(/[\s_]/g,'')===normalize(n).replace(/[\s_]/g,''));if(k!==undefined)return r[k]}return ''};return {name:String(get('Name')).trim(),sku:String(get('SKU')).trim(),storage_unit:String(get('Storage Unit')).trim(),ingredient_unit:String(get('Ingredient Unit','Ingredients Unit')).trim(),supplier:kind==='master'?String(get('Supplier')).trim():undefined,items_type:String(get('Items Type','Item Type','Section')).trim()||'Bar'};}
  function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(x=>x!==''))rows.push(row);row=[];continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const h=rows.shift()||[];return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]??''])));}
  function handleUpload(kind,file,mode='upsert'){if(!file)return;const reader=new FileReader();reader.onload=async e=>{try{let rows;if(file.name.toLowerCase().endsWith('.csv'))rows=parseCSV(new TextDecoder().decode(e.target.result));else{const wb=XLSX.read(e.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{defval:''});}const nrows=rows.map(r=>normalizeImportRow(kind,r)).filter(x=>x.name&&x.sku);if(!nrows.length)throw new Error('No valid rows. Check template headers.');const label=kind==='master'?'Master Items':'Internal Items';if(mode==='replace'){if(!confirm(`REPLACE ALL ${label}? This will delete the current ${label} list and replace it with ${nrows.length} imported item(s). This cannot be undone.`))return;}else if(!confirm(`Import ${nrows.length} item(s) into ${label}? Same SKU = update, new SKU = add. Existing items not in this file will stay.`))return;const fn=mode==='replace'?(kind==='master'?'admin_replace_master_items':'admin_replace_internal_items'):(kind==='master'?'admin_upsert_master_items':'admin_upsert_internal_items');const r=await rpc(fn,{p_token:state.token,p_rows:nrows});await adminLoad();if(mode==='replace')toast(`Replaced list with ${r} row(s).`);else toast(`Import complete: ${r.inserted||0} added, ${r.updated||0} updated.`);}catch(err){toast(err.message,true)}};reader.readAsArrayBuffer(file);}
  function downloadTemplate(kind){const row=kind==='master'?{'Name':'','SKU':'','Storage Unit':'','Ingredient Unit':'','Supplier':'','Items Type':''}:{'Name':'','SKU':'','Storage Unit':'','Ingredient Unit':'','Section':''};csv([row],Object.keys(row),kind==='master'?'Master_Items_Template.csv':'Internal_Items_Template.csv');}
  function toggleExportMonth(){$('exportMonthField').classList.toggle('hidden',$('exportRange').value!=='month');}
  async function exportManagementData(){const dataset=$('exportDataset').value,month=$('exportRange').value==='month'?($('exportMonth').value?$('exportMonth').value+'-01':null):null;if($('exportRange').value==='month'&&!month){toast('Select a month.',true);return;}try{const rows=await rpc('admin_export_dataset',{p_token:state.token,p_dataset:dataset,p_month:month});excel(rows,`Goya_${dataset}_${month?month.slice(0,7):'ALL'}.xlsx`,dataset);}catch(e){toast(e.message,true)}}
  async function adminLogout(){try{if(state.token)await rpc('logout',{p_token:state.token});}catch{}state.token=null;location.reload();}

  window.GoyaAdmin={adminLogin,nav:adminNav,mobileMenu:adminMobile,renderMaster,renderInternal,renderComplaints,loadComplaints,exportComplaintsExcel,deleteSelectedComplaints,editMaster,resetMasterForm,saveMasterItem,editInternal,resetInternalForm,saveInternalItem,deleteItem,editSupplier,resetSupplierForm,saveSupplier,deleteSupplier,editStaff,resetStaffForm,saveStaff,deleteStaff,loadAdminOrders,clearOrderFilters,bulkOrderStatus,deleteSelectedOrders,updateOrderQuantity,exportOrdersFoodics,whatsappSupplier,toggleChecks,updateSelectionCount,loadPW,bulkPWStatus,deleteSelectedPW,exportPWFoodics,editInventory,resetInventoryForm,saveInventorySession,deleteInventory,loadInventoryCounts,deleteSelectedInventoryCounts,exportInventoryFoodics,refreshInventoryResetOptions,resetInventorySubmission,editInfo,resetInfoForm,saveInfo,deleteInfo,saveSettings,changeAdminPin,handleUpload,downloadTemplate,toggleExportMonth,exportManagementData,adminLogout};

  document.addEventListener('DOMContentLoaded',()=>{ if(document.body.dataset.page==='staff'){state.cart=[];state.prodCart=[];state.wasteCart=[];renderOrderCart();renderStaffCart('production');renderStaffCart('wastage');} if(document.body.dataset.page==='admin'){const m=isoMonth();$('pwFrom').value=m+'-01';$('pwTo').value=new Date().toISOString().slice(0,10);$('invSessionMonth').value=m;$('invCountMonth').value=m;$('complaintMonth').value=m;$('exportMonth').value=m;$('staffPinNew').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,4));} });
})();
