(() => {
  const cfg = window.GOYA_CONFIG || {};
  let sb=null;
  const state={token:null,staff:[],settings:{},records:[],preview:[],history:[],monthly:[],daily:[],submissions:[],deviceFileBase64:null};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const pad=n=>String(n).padStart(2,'0');
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
  const monthNow=()=>today().slice(0,7);
  const toDateOnly=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const addDays=(s,n)=>{const d=new Date(`${s}T12:00:00`);d.setDate(d.getDate()+n);return toDateOnly(d)};
  const minsText=m=>{m=Math.max(0,Number(m)||0);return `${Math.floor(m/60)}h ${pad(m%60)}m`};
  const otBlockMin=m=>Math.floor(Math.max(0,Number(m)||0)/30)*30;
  const otText=m=>{m=otBlockMin(m);if(!m)return '0';if(m===30)return '30 min';const h=m/60;return `${Number.isInteger(h)?h:h.toFixed(1)} ${h===1?'hour':'hours'}`};
  const timeText=v=>{if(!v)return '—';const d=new Date(v.replace(' ','T'));if(Number.isNaN(d.getTime()))return String(v).slice(11,16);return d.toLocaleTimeString('en-AE',{hour:'numeric',minute:'2-digit'})};
  const toast=(msg,err=false)=>{const d=document.createElement('div');d.className='toast'+(err?' err':'');d.textContent=msg;$('toastHost').appendChild(d);setTimeout(()=>d.remove(),3500)};
  async function client(){if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY)throw new Error('Supabase config missing');if(!sb)sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}});return sb}
  async function rpc(name,args={}){await client();const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message);return data}
  function nav(btn,id){document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');document.querySelectorAll('[data-view]').forEach(x=>x.classList.add('hidden'));$(id)?.classList.remove('hidden');$('attSidebar').classList.remove('open');if(id==='attHistory')loadHistory();if(id==='attFiles')loadDocuments();if(id==='attStaffDetails')renderStaffDetails();if(id==='attSubmissions')loadSubmissions();if(id==='attUpload'){loadUploadHistory();loadFinalizedReportHistory()}}
  function mobileMenu(){$('attSidebar').classList.toggle('open')}
  async function login(){const pin=$('attAdminPin').value.trim();if(!/^\d{4,12}$/.test(pin)){toast('Enter Admin PIN',true);return}try{const d=await rpc('admin_login',{p_pin:pin});state.token=d.token;await bootstrap();$('attLogin').classList.add('hidden');$('attApp').classList.remove('hidden');toast('Attendance portal unlocked')}catch(e){toast(e.message,true)}}
  async function logout(){try{if(state.token)await rpc('logout',{p_token:state.token})}catch{}state.token=null;location.reload()}
  async function bootstrap(){const d=await rpc('attendance_bootstrap',{p_token:state.token});state.staff=d.staff||[];state.settings=d.settings||{};fillStaffSelects();fillSettings();const t=today();$('dashDate').value=t;$('manualDate').value=t;$('dailyDate').value=t;$('monthPick').value=monthNow();const first=`${monthNow()}-01`;$('histFrom').value=first;$('histTo').value=t;await loadDashboard()}
  function fillStaffSelects(){['manualStaff','fileStaff'].forEach(id=>{$(id).innerHTML=state.staff.map(s=>`<option value="${s.id}">${esc(s.name)}${s.employee_code?` · ${esc(s.employee_code)}`:''}</option>`).join('')});$('histStaff').innerHTML='<option value="">All Staff</option>'+state.staff.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}
  function fillSettings(){const s=state.settings;$('setStart').value=s.operational_start||'08:00';$('setCutoff').value=s.operational_cutoff||'02:00';$('setGrace').value=s.late_grace_minutes??15;$('setPresence').value=(s.default_presence_minutes??540)/60;$('setBreak').value=s.default_break_minutes??60}
  function recordStatus(r,date){if(!r)return 'No Record';if(r.day_off)return 'Day Off';if(r.split_shift&&(!r.punch_in||!r.punch_out||!r.shift2_in||!r.shift2_out))return date===today()?'On Duty':'Missing Punch';if(r.punch_in&&!r.punch_out)return date===today()?'On Duty':'Missing Punch';if(!r.punch_in&&r.punch_out)return 'Missing Punch';if(r.punch_in&&r.punch_out)return 'Completed';return 'No Record'}
  function rowForStaff(s,r,date){return {staff:s,record:r,status:recordStatus(r,date)}}
  async function getRange(start,end){const d=await rpc('attendance_records_range',{p_token:state.token,p_start:start,p_end:end});state.staff=d.staff||state.staff;fillStaffSelects();return d.records||[]}
  async function loadDashboard(){try{const date=$('dashDate').value||today();const rec=await getRange(date,date);const map=new Map(rec.map(r=>[r.attendance_staff_id,r]));const rows=state.staff.filter(s=>s.active!==false).map(s=>rowForStaff(s,map.get(s.id),date));state.daily=rows;const c={joined:0,completed:0,on:0,late:0,off:0,missing:0};rows.forEach(x=>{if(x.record?.punch_in)c.joined++;if(x.status==='Completed')c.completed++;if(x.status==='On Duty')c.on++;if((x.record?.late_minutes||0)>0)c.late++;if(x.status==='Day Off')c.off++;if(x.status==='Missing Punch')c.missing++});$('dJoined').textContent=c.joined;$('dCompleted').textContent=c.completed;$('dOnDuty').textContent=c.on;$('dLate').textContent=c.late;$('dOff').textContent=c.off;$('dMissing').textContent=c.missing;$('dashRows').innerHTML=rows.map(({staff:s,record:r,status})=>`<tr><td><strong>${esc(s.name)}</strong></td><td>${esc(s.employment_type)}</td><td>${timeText(r?.punch_in)}</td><td>${timeText(r?.punch_out)}</td><td>${r?minsText(r.presence_minutes):'—'}</td><td>${r?minsText(r.net_work_minutes):'—'}</td><td>${r&&r.additional_minutes?`+${otText(r.additional_minutes)}`:'—'}</td><td>${r&&r.late_minutes?`<span class="pill late">${r.late_minutes} min</span>`:'—'}</td><td>${r?(r.break_taken?'Yes':'No'):'—'}</td><td>${statusPill(status)}</td><td>${esc(r?.note||'')}</td></tr>`).join('')}catch(e){toast(e.message,true)}}
  function statusPill(s){const cls=s==='Completed'?'ok':s==='Day Off'?'off':s==='Missing Punch'?'missing':s==='On Duty'?'ok':'';return `<span class="pill ${cls}">${esc(s)}</span>`}

  // -------- DEVICE FILE PARSER --------
  const timeRegex=/(?:^|\D)([01]?\d|2[0-3]):([0-5]\d)(?::([0-5]\d))?(?:\D|$)/g;
  function parseTimes(v){if(v==null||v==='')return[];if(v instanceof Date)return [`${pad(v.getHours())}:${pad(v.getMinutes())}`];if(typeof v==='number'&&v>=0&&v<1){const mins=Math.round(v*1440)%1440;return [`${pad(Math.floor(mins/60))}:${pad(mins%60)}`]};const s=String(v);const out=[];let m;while((m=timeRegex.exec(s)))out.push(`${pad(+m[1])}:${m[2]}`);return out}
  function excelDate(v,yearHint,monthHint){if(v instanceof Date)return toDateOnly(v);if(typeof v==='number'&&v>30000){const d=XLSX.SSF.parse_date_code(v);if(d)return `${d.y}-${pad(d.m)}-${pad(d.d)}`};const s=String(v??'').trim();let m=s.match(/^(\d{4})[-\/.](\d{1,2})[-\/.](\d{1,2})$/);if(m)return `${m[1]}-${pad(+m[2])}-${pad(+m[3])}`;m=s.match(/^(\d{1,2})[-\/.](\d{1,2})(?:[-\/.](\d{2,4}))?$/);if(m){let y=m[3]?+m[3]:yearHint;if(y<100)y+=2000;return `${y}-${pad(+m[2])}-${pad(+m[1])}`};if(/^\d{1,2}$/.test(s)&&yearHint&&monthHint){const day=+s;if(day>=1&&day<=31)return `${yearHint}-${pad(monthHint)}-${pad(day)}`};return null}
  function combineLocal(date,time){return `${date}T${time}:00`}
  function normalizeEvents(events){const cutoff=$('setCutoff')?.value||state.settings.operational_cutoff||'02:00',cutM=toMin(cutoff);const grouped=new Map();events.forEach(e=>{const cleanName=String(e.name||'').trim();if(!cleanName||cleanName.toLowerCase()==='goya lounge')return;const tm=toMin(e.time),isMidnightOut=tm<=cutM,op=isMidnightOut?addDays(e.date,-1):e.date,key=`${cleanName.toLowerCase()}|${op}`;if(!grouped.has(key))grouped.set(key,{name:cleanName,employee_code:e.code||'',operational_date:op,events:[]});grouped.get(key).events.push({date:e.date,time:e.time,dt:combineLocal(e.date,e.time),isMidnightOut})});return [...grouped.values()].map(g=>{g.events.sort((a,b)=>a.dt.localeCompare(b.dt));const ev=g.events;let pin='',pout='',s2in='',s2out='',split=false,review=false;if(ev.length>=4){split=true;pin=ev[0].dt;pout=ev[1].dt;s2in=ev[2].dt;s2out=ev[ev.length-1].dt;if(ev.length!==4)review=true}else if(ev.length===3){pin=ev[0].dt;pout=ev[ev.length-1].dt;review=true}else if(ev.length===2){pin=ev[0].isMidnightOut?'':ev[0].dt;pout=ev[1].dt;if(!pin)review=true}else if(ev.length===1){if(ev[0].isMidnightOut)pout=ev[0].dt;else pin=ev[0].dt;review=true}return {name:g.name,employee_code:g.employee_code,operational_date:g.operational_date,punch_in:pin,punch_out:pout,split_shift:split,shift2_in:s2in,shift2_out:s2out,break_taken:true,note:'',review_needed:review||!pin||!pout||(split&&(!s2in||!s2out))};}).sort((a,b)=>a.operational_date.localeCompare(b.operational_date)||a.name.localeCompare(b.name))}
  function toMin(t){const [h,m]=String(t||'00:00').split(':').map(Number);return h*60+m}
  function detectTablePattern(aoa){const aliases={name:['name','employee name','staff','person name','enroll name'],code:['id','employee id','employee code','user id','enroll number','no.','no'],date:['date','punch date','attendance date'],time:['time','punch time','check time','datetime','date/time']};let best=null;aoa.slice(0,20).forEach((row,ri)=>{const low=row.map(x=>String(x??'').trim().toLowerCase());const find=arr=>low.findIndex(x=>arr.includes(x));const idx={name:find(aliases.name),code:find(aliases.code),date:find(aliases.date),time:find(aliases.time)};let score=Object.values(idx).filter(x=>x>=0).length;if(score>=(idx.name>=0&&idx.date>=0&&idx.time>=0?3:99)&&(!best||score>best.score))best={ri,idx,score}});return best}
  function parseFlat(aoa,pat){const ev=[];for(let i=pat.ri+1;i<aoa.length;i++){const r=aoa[i];const name=String(r[pat.idx.name]??'').trim();if(!name)continue;const code=pat.idx.code>=0?String(r[pat.idx.code]??'').trim():'';let dval=r[pat.idx.date],tval=r[pat.idx.time];let date=excelDate(dval,new Date().getFullYear(),new Date().getMonth()+1);if(!date&&tval instanceof Date)date=toDateOnly(tval);const times=parseTimes(tval);if(date)times.forEach(time=>ev.push({name,code,date,time}))}return ev}
  function parseDayView(aoa){let h=-1,idx={};for(let ri=0;ri<Math.min(20,aoa.length);ri++){const low=aoa[ri].map(x=>String(x??'').trim().toLowerCase());const name=low.indexOf('name'),date=low.indexOf('punch date'),p1=low.findIndex(x=>/^punch\s*1$/.test(x)||x==='punch1');if(name>=0&&date>=0&&p1>=0){h=ri;idx={name,date,code:low.indexOf('person code'),dept:low.indexOf('department'),punchCols:low.map((x,i)=>/^punch\s*\d+$/.test(x)||/^punch\d+$/.test(x)?i:-1).filter(i=>i>=0)};break}}if(h<0)return null;const ev=[];for(let i=h+1;i<aoa.length;i++){const r=aoa[i],name=String(r[idx.name]??'').trim();if(!name||name.toLowerCase()==='goya lounge')continue;const code=idx.code>=0?String(r[idx.code]??'').trim():'',date=excelDate(r[idx.date],new Date().getFullYear(),new Date().getMonth()+1);if(!date)continue;for(const ci of idx.punchCols)for(const time of parseTimes(r[ci]))ev.push({name,code,date,time})}return ev}
  function parseMatrix(aoa,fileName){const now=new Date();let year=now.getFullYear(),month=now.getMonth()+1;const fm=fileName.match(/(january|february|march|april|may|june|july|august|september|october|november|december)[^0-9]*(20\d{2})/i);if(fm){month=['january','february','march','april','may','june','july','august','september','october','november','december'].indexOf(fm[1].toLowerCase())+1;year=+fm[2]}const yhit=aoa.flat().map(x=>String(x??'')).join(' ').match(/20\d{2}/);if(yhit)year=+yhit[0];let best={ri:0,cols:[],score:0};for(let ri=0;ri<Math.min(25,aoa.length);ri++){const cols=[];aoa[ri].forEach((v,ci)=>{let d=null;const raw=String(v??'').trim(),md=raw.match(/^(\d{1,2})[-\/.](\d{1,2})$/);if(md&&+md[1]===month)d=`${year}-${pad(month)}-${pad(+md[2])}`;else d=excelDate(v,year,month);if(d)cols.push({ci,date:d})});if(cols.length>best.score)best={ri,cols,score:cols.length}}if(best.score<3)throw new Error('Could not identify the device report layout. Please use the original machine XLS/XLSX/CSV report.');const firstDateCol=Math.min(...best.cols.map(x=>x.ci));const ev=[];for(let i=best.ri+1;i<aoa.length;i++){const row=aoa[i];let name='',code='';for(let c=0;c<firstDateCol;c++){const s=String(row[c]??'').trim();if(!s)continue;if(!code&&/^\d{1,12}$/.test(s))code=s;else if(!name&&!/^\d+$/.test(s)&&s.length>1)name=s}if(!name)continue;best.cols.forEach(({ci,date})=>parseTimes(row[ci]).forEach(time=>ev.push({name,code,date,time})))}return ev}
  async function previewDeviceFile(){const f=$('deviceFile').files[0];if(!f){toast('Select a device report file',true);return}try{const buf=await f.arrayBuffer();const bytes=new Uint8Array(buf);let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));state.deviceFileBase64=btoa(bin);const wb=XLSX.read(buf,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const aoa=XLSX.utils.sheet_to_json(ws,{header:1,raw:true,defval:''});const dayView=parseDayView(aoa),pat=detectTablePattern(aoa);let events=dayView?.length?dayView:(pat?parseFlat(aoa,pat):parseMatrix(aoa,f.name));if(!events.length)throw new Error('No punch times were detected in this file.');state.preview=normalizeEvents(events);const dates=state.preview.map(x=>x.operational_date).filter(Boolean).sort();$('uploadInfo').textContent=`Detected ${state.preview.length} attendance records from ${dates[0]||'—'} to ${dates.at(-1)||'—'}. Midnight punches up to ${state.settings.operational_cutoff||'02:00'} are assigned to the previous operational day. Correct missing punches before final import.`;$('uploadPreview').innerHTML=state.preview.slice(0,500).map((r,i)=>`<tr class="${r.review_needed?'review-row':''}"><td>${r.operational_date}</td><td>${esc(r.name)}${r.split_shift?' <span class="split-badge">Split</span>':''}</td><td>${esc(r.employee_code)}</td><td><input type="time" value="${esc(timeOnly(r.punch_in))}" onchange="GoyaAttendance.setPreviewTime(${i},'punch_in',this.value)">${!r.punch_in?'<div class="small missing-text">Missing In</div>':''}</td><td><input type="time" value="${esc(timeOnly(r.punch_out))}" onchange="GoyaAttendance.setPreviewTime(${i},'punch_out',this.value)">${!r.punch_out?'<div class="small missing-text">Missing Out</div>':''}</td><td><input type="time" value="${esc(timeOnly(r.shift2_in))}" onchange="GoyaAttendance.setPreviewTime(${i},'shift2_in',this.value)"></td><td><input type="time" value="${esc(timeOnly(r.shift2_out))}" onchange="GoyaAttendance.setPreviewTime(${i},'shift2_out',this.value)"></td><td><select onchange="GoyaAttendance.setPreviewBreak(${i},this.value)"><option value="true" ${r.break_taken?'selected':''}>Yes</option><option value="false" ${!r.break_taken?'selected':''}>No</option></select></td><td><input value="${esc(r.note||'')}" placeholder="Optional note" onchange="GoyaAttendance.setPreviewNote(${i},this.value)"></td></tr>`).join('');$('importDeviceBtn').disabled=false;['previewPdfBtn','previewExcelBtn','previewExcelStaffBtn'].forEach(id=>{if($(id))$(id).disabled=false})}catch(e){state.preview=[];state.deviceFileBase64=null;$('importDeviceBtn').disabled=true;['previewPdfBtn','previewExcelBtn','previewExcelStaffBtn'].forEach(id=>{if($(id))$(id).disabled=true});toast(e.message,true)}}
  function timeOnly(v){return v?String(v).slice(11,16):''}
  function setPreviewTime(i,k,v){const r=state.preview[i];if(!r)return;const isOut=k==='punch_out'||k==='shift2_out';r[k]=v?timestampFromOperational(r.operational_date,v,isOut):'';r.split_shift=!!(r.shift2_in||r.shift2_out);r.review_needed=!r.punch_in||!r.punch_out||(r.split_shift&&(!r.shift2_in||!r.shift2_out));}
  function setPreviewBreak(i,v){if(state.preview[i])state.preview[i].break_taken=v==='true'}
  function setPreviewNote(i,v){if(state.preview[i])state.preview[i].note=v||''}
  async function importDeviceFile(){if(!state.preview.length)return;const bad=state.preview.filter(r=>r.review_needed);if(bad.length&&!confirm(`${bad.length} record(s) still need review. Save anyway?`))return;const f=$('deviceFile').files[0],dates=state.preview.map(x=>x.operational_date).filter(Boolean).sort();try{const d=await rpc('attendance_import_records_v11',{p_token:state.token,p_rows:state.preview,p_file_name:f?.name||'Device report',p_upload_type:$('uploadType').value,p_date_from:dates[0],p_date_to:dates.at(-1)});if(f&&state.deviceFileBase64)await rpc('attendance_archive_upload',{p_token:state.token,p_file_name:f.name,p_mime_type:f.type||'application/vnd.ms-excel',p_file_size:f.size,p_base64:state.deviceFileBase64,p_upload_type:$('uploadType').value,p_date_from:dates[0],p_date_to:dates.at(-1),p_rows_imported:d.imported||0});const reportRows=await deviceReportRowsFromPreview();const summary=deviceReportSummary(reportRows);const period=reportPeriodLabel(dates);await rpc('attendance_save_finalized_report_v10',{p_token:state.token,p_file_name:f?.name||'Device report',p_period_label:period,p_date_from:dates[0],p_date_to:dates.at(-1),p_rows:reportRows,p_summary:summary});toast(`Saved ${d.imported} raw device record(s). Final/admin corrections were preserved.`);await loadFinalizedReportHistory();downloadDevicePDF(reportRows,summary,period);downloadDeviceExcel(reportRows,summary,period);await bootstrap();await loadUploadHistory();$('dashDate').value=dates.at(-1);await loadDashboard()}catch(e){toast(e.message,true)}}
  async function loadUploadHistory(){if(!$('uploadHistoryList'))return;try{const rows=await rpc('attendance_upload_history',{p_token:state.token});$('uploadHistoryList').innerHTML=(rows||[]).map(x=>`<div class="doc-row"><div><strong>${esc(x.file_name)}</strong><div class="small muted">${esc(x.upload_type)} · ${esc(x.date_from||'')} → ${esc(x.date_to||'')} · ${x.rows_imported||0} rows · ${new Date(x.created_at).toLocaleString('en-AE')}</div></div><button class="btn secondary" onclick="GoyaAttendance.downloadUpload('${x.id}')">Download</button></div>`).join('')||'<div class="notice">No saved device files.</div>'}catch(e){toast(e.message,true)}}
  async function downloadUpload(id){try{const d=await rpc('attendance_get_upload',{p_token:state.token,p_id:id});if(!d?.base64)return toast('Original file is not available for this older upload.',true);const bin=atob(d.base64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([arr],{type:d.mime_type||'application/octet-stream'}));a.download=d.file_name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){toast(e.message,true)}}
  function reportPeriodLabel(dates){if(!dates?.length)return 'Attendance Report';const first=new Date(`${dates[0]}T12:00:00`),last=new Date(`${dates.at(-1)}T12:00:00`);if(first.getFullYear()===last.getFullYear()&&first.getMonth()===last.getMonth())return first.toLocaleDateString('en-AE',{month:'long',year:'numeric'});return `${formatDate(dates[0])} - ${formatDate(dates.at(-1))}`}
  async function deviceReportRowsFromPreview(){const out=[];for(const p of state.preview){const st=state.staff.find(s=>String(s.name||'').trim().toLowerCase()===String(p.name||'').trim().toLowerCase())||{};let seg1=0,seg2=0;if(p.punch_in&&p.punch_out)seg1=Math.max(0,Math.round((new Date(p.punch_out)-new Date(p.punch_in))/60000));if(p.split_shift&&p.shift2_in&&p.shift2_out)seg2=Math.max(0,Math.round((new Date(p.shift2_out)-new Date(p.shift2_in))/60000));const presence=seg1+seg2,breakMin=p.break_taken?(st.default_break_minutes??60):0,net=Math.max(0,presence-breakMin),expected=Math.max(0,(st.expected_presence_minutes??540)-(st.default_break_minutes??60)),ot=Math.max(0,net-expected);let late=0;if(p.punch_in){const sch=`${p.operational_date}T${String(st.default_start_time||'08:00').slice(0,5)}:00`,d=Math.round((new Date(p.punch_in)-new Date(sch))/60000),gr=state.settings.late_grace_minutes??15;if(d>gr)late=d}out.push({Date:p.operational_date,Staff:p.name,'Employee Code':p.employee_code||'', 'Working Time':p.split_shift?`${timeText(p.punch_in)} - ${timeText(p.punch_out)} / ${timeText(p.shift2_in)} - ${timeText(p.shift2_out)}`:`${timeText(p.punch_in)} - ${timeText(p.punch_out)}`,'Presence Minutes':presence,'Net Minutes':net,'OT Minutes':ot,'Late Minutes':late,'Break Taken':p.break_taken?'Yes':'No','Status':p.review_needed?'Review Needed':'Complete','Note':p.note||''})}return out}
  function deviceReportSummary(rows){const by={};for(const r of rows){const x=by[r.Staff]||(by[r.Staff]={staff:r.Staff,duty:0,presence:0,net:0,ot:0,lateDays:0,lateMinutes:0,review:0});x.duty++;x.presence+=r['Presence Minutes']||0;x.net+=r['Net Minutes']||0;x.ot+=otBlockMin(r['OT Minutes']||0);if(r['Late Minutes']>0){x.lateDays++;x.lateMinutes+=r['Late Minutes']}if(r.Status!=='Complete')x.review++}return {staff_count:Object.keys(by).length,row_count:rows.length,staff:Object.values(by)}}
  function deviceDetailRows(rows){return rows.map(r=>({'Date':r.Date,'Staff':r.Staff,'Device Code':r['Employee Code']||'','Working Time':r['Working Time'],'Presence':minsText(r['Presence Minutes']),'Net Work':minsText(r['Net Minutes']),'OT / Extra':otText(r['OT Minutes']),'OT Hours':otBlockMin(r['OT Minutes'])/60,'Late Minutes':r['Late Minutes']||0,'Break Taken':r['Break Taken'],'Status':r.Status,'Note':r.Note||''}))}
  function deviceSummaryRows(summary){return (summary.staff||[]).map(x=>({'Staff':x.staff,'Duty Records':x.duty,'Total Presence':minsText(x.presence),'Net Working Hours':minsText(x.net),'OT / Extra':otText(x.ot),'OT Hours':otBlockMin(x.ot)/60,'Late Days':x.lateDays,'Late Minutes':x.lateMinutes,'Review / Missing':x.review}))}
  function downloadDevicePDF(rows,summary,period,name=`Goya_Device_Attendance_${String(period).replace(/[^a-z0-9]+/gi,'_')}.pdf`){if(!window.jspdf?.jsPDF)return toast('PDF library is still loading.',true);const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape'});doc.setFontSize(18);doc.text('GOYA - Attendance Report',14,16);doc.setFontSize(10);doc.text(`Period: ${period}    Staff: ${summary.staff_count||0}    Records: ${summary.row_count||rows.length}`,14,24);doc.text('Missing punches are flagged for HR review and do not block this report.',14,30);doc.autoTable({startY:36,head:[['Staff','Duty Records','Presence','Net Work','OT','Late Days','Missing / Review']],body:(summary.staff||[]).map(x=>[x.staff,x.duty,minsText(x.presence),minsText(x.net),otText(x.ot),x.lateDays,x.review]),styles:{fontSize:9,cellPadding:3},headStyles:{fillColor:[38,59,52]}});const names=[...new Set(rows.map(r=>r.Staff))].sort((a,b)=>a.localeCompare(b));for(const nameStaff of names){const sr=rows.filter(r=>r.Staff===nameStaff);const ss=(summary.staff||[]).find(x=>x.staff===nameStaff)||{};doc.addPage('a4','landscape');doc.setFontSize(15);doc.text(nameStaff,14,16);doc.setFontSize(10);doc.text(`Period: ${period}    Duty Records: ${ss.duty||sr.length}    Net: ${minsText(ss.net||0)}    Total OT: ${otText(ss.ot||0)}`,14,24);doc.autoTable({startY:30,head:[['Date','Working Time','Net','OT','Late','Break','Status','Note']],body:sr.map(r=>[r.Date,r['Working Time'],minsText(r['Net Minutes']),otText(r['OT Minutes']),r['Late Minutes']?`${r['Late Minutes']} min`:'—',r['Break Taken'],r.Status,r.Note||'']),styles:{fontSize:8,cellPadding:2},headStyles:{fillColor:[38,59,52]},columnStyles:{1:{cellWidth:48},7:{cellWidth:45}}})}doc.save(name)}
  function downloadDeviceExcel(rows,summary,period,name=`Goya_Device_Attendance_${String(period).replace(/[^a-z0-9]+/gi,'_')}.xlsx`,separate=false){const detail=deviceDetailRows(rows),sum=deviceSummaryRows(summary),sheets={'Staff Summary':sum,'All Staff - Daily':detail};if(separate){const used=new Set(Object.keys(sheets).map(x=>x.toLowerCase()));for(const staff of [...new Set(detail.map(x=>x.Staff))]){let n=String(staff||'Staff').replace(/[\\/*?:\[\]]/g,' ').trim().slice(0,31)||'Staff';let base=n,i=2;while(used.has(n.toLowerCase()))n=(base.slice(0,27)+` ${i++}`).slice(0,31);used.add(n.toLowerCase());sheets[n]=detail.filter(x=>x.Staff===staff)}}writeWorkbook(sheets,name)}
  async function exportPreviewPDF(){if(!state.preview.length)return toast('Preview a device file first.',true);const dates=state.preview.map(x=>x.operational_date).filter(Boolean).sort(),rows=await deviceReportRowsFromPreview(),summary=deviceReportSummary(rows),period=reportPeriodLabel(dates);downloadDevicePDF(rows,summary,period)}
  async function exportPreviewExcel(separate=false){if(!state.preview.length)return toast('Preview a device file first.',true);const dates=state.preview.map(x=>x.operational_date).filter(Boolean).sort(),rows=await deviceReportRowsFromPreview(),summary=deviceReportSummary(rows),period=reportPeriodLabel(dates);downloadDeviceExcel(rows,summary,period,`Goya_Device_Attendance_${String(period).replace(/[^a-z0-9]+/gi,'_')}${separate?'_Staff_Sheets':''}.xlsx`,separate)}
  async function loadFinalizedReportHistory(){if(!$('finalizedReportList'))return;try{const rows=await rpc('attendance_finalized_report_history_v10',{p_token:state.token});$('finalizedReportList').innerHTML=(rows||[]).map(x=>`<div class="final-report-row"><div><strong>${esc(x.period_label||x.file_name||'Attendance Report')}</strong><div class="small muted">${esc(x.date_from||'')} → ${esc(x.date_to||'')} · ${x.summary?.staff_count||0} staff · ${new Date(x.created_at).toLocaleString('en-AE')}</div></div><div class="report-actions"><button class="btn secondary" onclick="GoyaAttendance.redownloadFinalizedReport('${x.id}','pdf')">PDF</button><button class="btn secondary" onclick="GoyaAttendance.redownloadFinalizedReport('${x.id}','excel')">Excel All</button><button class="btn secondary" onclick="GoyaAttendance.redownloadFinalizedReport('${x.id}','staffexcel')">Excel Staff Sheets</button><button class="btn success" onclick="GoyaAttendance.regenerateFinalizedReport('${x.id}')">Regenerate Latest</button></div></div>`).join('')||'<div class="notice">No finalized device reports yet.</div>'}catch(e){toast(e.message,true)}}
  async function redownloadFinalizedReport(id,type){try{const d=await rpc('attendance_get_finalized_report_v10',{p_token:state.token,p_id:id});if(!d)return;const rows=d.processed_rows||[],summary=d.summary||deviceReportSummary(rows),period=d.period_label||'Attendance Report';if(type==='pdf')downloadDevicePDF(rows,summary,period);else downloadDeviceExcel(rows,summary,period,undefined,type==='staffexcel')}catch(e){toast(e.message,true)}}
  async function regenerateFinalizedReport(id){try{const d=await rpc('attendance_get_finalized_report_v10',{p_token:state.token,p_id:id});if(!d)return;const rec=(await getRange(d.date_from,d.date_to)).filter(r=>String(r.entry_origin||r.source||'').toLowerCase()==='device');const rows=rec.map(r=>({Date:r.operational_date,Staff:r.staff_name||'', 'Employee Code':'','Working Time':workingTimeText(r),'Presence Minutes':r.presence_minutes||0,'Net Minutes':r.net_work_minutes||0,'OT Minutes':r.additional_minutes||0,'Late Minutes':r.late_minutes||0,'Break Taken':r.break_taken?'Yes':'No','Status':recordStatus(r,r.operational_date)==='Completed'?'Complete':'Review Needed','Note':r.note||''}));const summary=deviceReportSummary(rows),period=d.period_label||reportPeriodLabel([d.date_from,d.date_to]);await rpc('attendance_update_finalized_report_v11',{p_token:state.token,p_id:id,p_rows:rows,p_summary:summary});downloadDevicePDF(rows,summary,period);downloadDeviceExcel(rows,summary,period);toast('Saved report regenerated from the latest final device attendance.')}catch(e){toast(e.message,true)}}
  function subInput(id,field,val,disabled=false){return `<input class="sub-edit" type="time" id="sub_${field}_${id}" value="${esc(timeOnly(val))}" ${disabled?'disabled':''}>`}
  function selectedSubmissionIds(){return [...document.querySelectorAll('.sub-check:checked')].map(x=>x.value)}
  function updateSubSelected(){if($('subSelectedCount'))$('subSelectedCount').textContent=`Selected: ${selectedSubmissionIds().length}`}
  function toggleAllSubmissions(on){document.querySelectorAll('.sub-check').forEach(x=>x.checked=on);updateSubSelected()}
  function clockDiff(a,b){if(!a||!b)return null;return Math.round((new Date(a.replace(' ','T'))-new Date(b.replace(' ','T')))/60000)}
  function comparisonText(x){if(x.day_off)return x.device_punch_in||x.device_punch_out?'Staff marked Day Off but device has punches':'Day Off';const vals=[['In',x.punch_in,x.device_punch_in],['Out',x.punch_out,x.device_punch_out]];if(x.split_shift||x.device_split_shift){vals.push(['In 2',x.shift2_in,x.device_shift2_in],['Out 2',x.shift2_out,x.device_shift2_out])}const diffs=vals.map(([n,a,b])=>{if(!a&&!b)return null;if(!a||!b)return `${n}: missing`;const d=clockDiff(a,b);return `${n}: ${d===0?'match':`${d>0?'+':''}${d}m`}`}).filter(Boolean);const breakDiff=(x.break_taken!==x.device_break_taken)?'Break differs':null;if(breakDiff)diffs.push(breakDiff);return diffs.join(' · ')||'Match'}
  async function loadSubmissions(){if(!$('submissionRows'))return;try{state.submissions=await rpc('attendance_staff_device_compare_v10',{p_token:state.token,p_status:$('subStatus').value||null});$('submissionRows').innerHTML=state.submissions.length?state.submissions.map(x=>{const device=x.device_punch_in||x.device_punch_out?`${timeText(x.device_punch_in)} → ${timeText(x.device_punch_out)}${x.device_split_shift?` / ${timeText(x.device_shift2_in)} → ${timeText(x.device_shift2_out)}`:''}`:'No device record';const staff=x.day_off?'Day Off':`${timeText(x.punch_in)} → ${timeText(x.punch_out)}${x.split_shift?` / ${timeText(x.shift2_in)} → ${timeText(x.shift2_out)}`:''}`;const diff=comparisonText(x),finalized=x.status==='Finalized';return `<tr><td><input class="sub-check" type="checkbox" value="${x.id}" onchange="GoyaAttendance.updateSubSelected()"></td><td>${esc(x.operational_date)}</td><td><strong>${esc(x.staff_name)}</strong></td><td><div class="compare-stack">${esc(staff)}<small>Break: ${x.day_off?'—':(x.break_taken?'Yes':'No')}</small></div></td><td><div class="compare-stack">${esc(device)}<small>${x.device_punch_in||x.device_punch_out?`Break: ${x.device_break_taken?'Yes':'No'}`:''}</small></div></td><td class="${diff==='Match'?'diff-ok':'diff-warn'}">${esc(diff)}</td><td>${x.day_off?'—':subInput(x.id,'in1',x.punch_in,false)}</td><td>${x.day_off?'—':subInput(x.id,'out1',x.punch_out,false)}</td><td>${x.day_off?'—':subInput(x.id,'in2',x.shift2_in,false)}</td><td>${x.day_off?'—':subInput(x.id,'out2',x.shift2_out,false)}</td><td>${x.day_off?'—':`<select id="sub_break_${x.id}"><option value="true" ${x.break_taken?'selected':''}>Yes</option><option value="false" ${!x.break_taken?'selected':''}>No</option></select>`}</td><td><input id="sub_note_${x.id}" value="${esc(x.note||'')}"></td><td>${statusPill(finalized?'Finalized':'Submitted')}</td><td><button class="btn success" onclick="GoyaAttendance.saveSubmissionFinal('${x.id}')">Save Final</button></td></tr>`}).join(''):'<tr><td colspan="14">No staff submissions.</td></tr>';$('subSelectAll').checked=false;updateSubSelected()}catch(e){toast(e.message,true)}}
  function submissionEditPayload(row){if(row.day_off)return {pin:null,pout:null,s2in:null,s2out:null,split:false,breakTaken:true,note:$(`sub_note_${row.id}`)?.value||row.note||null};const get=f=>$(`sub_${f}_${row.id}`)?.value||'';const a=get('in1'),b=get('out1'),c=get('in2'),d=get('out2'),split=!!(c||d||row.split_shift);return {pin:a?timestampFromOperational(row.operational_date,a,false):null,pout:b?timestampFromOperational(row.operational_date,b,true):null,s2in:c?timestampFromOperational(row.operational_date,c,false):null,s2out:d?timestampFromOperational(row.operational_date,d,true):null,split,breakTaken:$(`sub_break_${row.id}`)?.value==='true',note:$(`sub_note_${row.id}`)?.value||null}}
  async function saveSubmissionFinal(id,skipConfirm=false){const row=state.submissions.find(x=>x.id===id);if(!row)return;if(!skipConfirm&&!confirm(`Save ${row.staff_name}'s ${row.operational_date} as final attendance?`))return;const e=submissionEditPayload(row);if(!row.day_off&&(!e.pin||!e.pout||(e.split&&(!e.s2in||!e.s2out))))return toast('Complete the required shift times first.',true);try{await rpc('attendance_save_final_submission_v10',{p_token:state.token,p_id:id,p_punch_in:e.pin,p_punch_out:e.pout,p_break_taken:e.breakTaken,p_day_off:row.day_off,p_split_shift:e.split,p_shift2_in:e.s2in,p_shift2_out:e.s2out,p_note:e.note});if(!skipConfirm){toast('Final attendance saved and recalculated.');await loadSubmissions();await loadDashboard()}}catch(e){toast(e.message,true);throw e}}
  async function finalizeSelectedSubmissions(){const ids=selectedSubmissionIds();if(!ids.length)return toast('Select at least one staff record.',true);if(!confirm(`Save ${ids.length} selected record(s) as final attendance?`))return;let ok=0;for(const id of ids){try{await saveSubmissionFinal(id,true);ok++}catch{}}toast(`Saved ${ok} final attendance record(s).`);await loadSubmissions();await loadDashboard()}
  function workingTimeText(r){if(r.day_off)return 'Day Off';const a=`${timeText(r.punch_in)} → ${timeText(r.punch_out)}`;return r.split_shift?`${a} / ${timeText(r.shift2_in)} → ${timeText(r.shift2_out)}`:a}
  async function loadHistory(){try{const start=$('histFrom').value||`${monthNow()}-01`,end=$('histTo').value||today();let rows=await getRange(start,end);const sf=$('histStaff').value,origin=$('histOrigin')?.value||'';if(sf)rows=rows.filter(r=>r.attendance_staff_id===sf);if(origin)rows=rows.filter(r=>(r.entry_origin||'device')===origin);state.history=rows;$('historyRows').innerHTML=rows.length?rows.map(r=>`<tr><td>${r.operational_date}</td><td>${esc(r.staff_name)}</td><td>${esc(r.employment_type)}</td><td>${esc(workingTimeText(r))}</td><td>${minsText(r.presence_minutes)}</td><td>${minsText(r.net_work_minutes)}</td><td>${r.additional_minutes?`+${otText(r.additional_minutes)}`:'—'}</td><td>${r.late_minutes?`${r.late_minutes} min`:'—'}</td><td>${r.day_off?'—':(r.break_taken?'Yes':'No')}</td><td>${statusPill(recordStatus(r,r.operational_date))}</td><td><span class="origin-pill">${esc((r.entry_origin||'device').replaceAll('_',' '))}</span></td><td>${esc(r.note||'')}</td><td><button class="btn secondary" onclick="GoyaAttendance.editRecord('${r.id}')">Edit</button> <button class="btn danger" onclick="GoyaAttendance.deleteRecord('${r.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="13">No records.</td></tr>'}catch(e){toast(e.message,true)}}
  function editRecord(id){const r=state.history.find(x=>x.id===id);if(!r)return;nav(document.querySelectorAll('.nav button')[4],'attManual');$('manualStaff').value=r.attendance_staff_id;$('manualDate').value=r.operational_date;$('manualIn').value=timeOnly(r.punch_in);$('manualOut').value=timeOnly(r.punch_out);$('manualBreak').value=String(!!r.break_taken);$('manualNote').value=r.note||''}
  async function deleteRecord(id){if(!confirm('Delete this attendance record?'))return;try{await rpc('attendance_delete_record',{p_token:state.token,p_id:id});toast('Record deleted');loadHistory()}catch(e){toast(e.message,true)}}
  function historyExportRows(){return state.history.map(r=>({'Date':r.operational_date,'Staff':r.staff_name,'Employment Type':r.employment_type,'Working Time':workingTimeText(r),'Presence':minsText(r.presence_minutes),'Net Work':minsText(r.net_work_minutes),'Additional/OT':minsText(r.additional_minutes),'Late Minutes':r.late_minutes,'Break Taken':r.day_off?'':(r.break_taken?'Yes':'No'),'Status':recordStatus(r,r.operational_date),'Note':r.note||''}))}
  function exportHistoryExcel(){if(!state.history.length){toast('Load history first',true);return}writeWorkbook({'Attendance History':historyExportRows()},`Goya_Attendance_History_${$('histFrom').value}_to_${$('histTo').value}.xlsx`)}

  async function saveManual(){const sid=$('manualStaff').value,date=$('manualDate').value;if(!sid||!date){toast('Staff and duty date are required',true);return}const tin=$('manualIn').value,tout=$('manualOut').value;try{await rpc('attendance_save_manual',{p_token:state.token,p_staff_id:sid,p_operational_date:date,p_punch_in:tin?timestampFromOperational(date,tin,false):null,p_punch_out:tout?timestampFromOperational(date,tout,true):null,p_break_taken:$('manualBreak').value==='true',p_note:$('manualNote').value||null});toast('Attendance saved and recalculated');$('dashDate').value=date;await loadDashboard()}catch(e){toast(e.message,true)}}
  async function saveStaff(){const name=$('staffName').value.trim();if(!name){toast('Staff name required',true);return}try{await rpc('attendance_save_staff',{p_token:state.token,p_id:$('staffEditId').value||null,p_name:name,p_employee_code:$('staffCode').value||null,p_employment_type:$('staffType').value,p_designation:$('staffDesignation').value||null,p_phone:$('staffPhone').value||null,p_default_start_time:$('staffStart').value||'08:00',p_expected_presence_minutes:Math.round((+$('staffHours').value||0)*60),p_default_break_minutes:+$('staffBreak').value||0,p_active:$('staffActive').value==='true',p_notes:$('staffNotes').value||null});toast('Staff saved');resetStaffForm();await bootstrap();renderStaffDetails()}catch(e){toast(e.message,true)}}
  function resetStaffForm(){['staffEditId','staffName','staffCode','staffDesignation','staffPhone','staffNotes'].forEach(id=>$(id).value='');$('staffType').value='Full Time';$('staffStart').value='08:00';$('staffHours').value='9';$('staffBreak').value='60';$('staffActive').value='true'}
  function editStaff(id){const s=state.staff.find(x=>x.id===id);if(!s)return;nav(document.querySelector('.nav button:nth-child(5)'),'attAddStaff');$('staffEditId').value=s.id;$('staffName').value=s.name||'';$('staffCode').value=s.employee_code||'';$('staffType').value=s.employment_type||'Full Time';$('staffDesignation').value=s.designation||'';$('staffPhone').value=s.phone||'';$('staffStart').value=String(s.default_start_time||'08:00').slice(0,5);$('staffHours').value=(s.expected_presence_minutes||540)/60;$('staffBreak').value=s.default_break_minutes??60;$('staffActive').value=String(s.active!==false);$('staffNotes').value=s.notes||''}
  function renderStaffDetails(){const q=($('staffSearch').value||'').toLowerCase(),typ=$('staffTypeFilter').value;const list=state.staff.filter(s=>(!q||`${s.name} ${s.employee_code||''}`.toLowerCase().includes(q))&&(!typ||s.employment_type===typ));$('staffCards').innerHTML=list.map(s=>`<div class="staff-card"><h3>${esc(s.name)}</h3><p>${esc(s.employment_type)}${s.designation?` · ${esc(s.designation)}`:''}</p><p>Device Code: ${esc(s.employee_code||'Not set')}</p><p>Shift: ${String(s.default_start_time||'08:00').slice(0,5)} · ${(s.expected_presence_minutes||540)/60}h presence · ${s.default_break_minutes??60}m break</p><p>${esc(s.phone||'')}</p><button class="btn secondary" onclick="GoyaAttendance.editStaff('${s.id}')">Edit Details</button></div>`).join('')}

  async function uploadDocument(){const sid=$('fileStaff').value,f=$('staffFile').files[0],title=$('fileTitle').value.trim();if(!sid||!f||!title){toast('Staff, title and file required',true);return}if(f.size>5242880){toast('Maximum file size is 5 MB',true);return}try{const b64=await fileBase64(f);await rpc('attendance_upload_document',{p_token:state.token,p_staff_id:sid,p_title:title,p_file_name:f.name,p_mime_type:f.type||'application/octet-stream',p_file_size:f.size,p_base64:b64,p_note:$('fileNote').value||null});toast('Document uploaded');$('fileTitle').value='';$('fileNote').value='';$('staffFile').value='';loadDocuments()}catch(e){toast(e.message,true)}}
  function fileBase64(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(f)})}
  async function loadDocuments(){const sid=$('fileStaff').value;if(!sid){$('documentList').innerHTML='';return}try{const docs=await rpc('attendance_list_documents',{p_token:state.token,p_staff_id:sid});$('documentList').innerHTML=(docs||[]).map(d=>`<div class="doc-row"><div><strong>${esc(d.title)}</strong><div class="small muted">${esc(d.file_name)} · ${Math.round((d.file_size||0)/1024)} KB · ${new Date(d.created_at).toLocaleDateString('en-AE')}</div>${d.note?`<div>${esc(d.note)}</div>`:''}</div><div><button class="btn secondary" onclick="GoyaAttendance.downloadDocument('${d.id}')">Download</button> <button class="btn danger" onclick="GoyaAttendance.deleteDocument('${d.id}')">Delete</button></div></div>`).join('')||'<div class="notice">No documents.</div>'}catch(e){toast(e.message,true)}}
  async function downloadDocument(id){try{const d=await rpc('attendance_get_document',{p_token:state.token,p_id:id});const bin=atob(d.base64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([arr],{type:d.mime_type||'application/octet-stream'}));a.download=d.file_name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){toast(e.message,true)}}
  async function deleteDocument(id){if(!confirm('Delete this staff document?'))return;try{await rpc('attendance_delete_document',{p_token:state.token,p_id:id});loadDocuments()}catch(e){toast(e.message,true)}}

  async function generateDailyReport(){const date=$('dailyDate').value||today();try{const rec=await getRange(date,date),map=new Map(rec.map(r=>[r.attendance_staff_id,r]));const rows=state.staff.filter(s=>s.active!==false).map(s=>rowForStaff(s,map.get(s.id),date));state.daily=rows;const joined=rows.filter(x=>x.record?.punch_in).length,completed=rows.filter(x=>x.status==='Completed').length,on=rows.filter(x=>x.status==='On Duty').length,off=rows.filter(x=>x.status==='Day Off').length,late=rows.filter(x=>x.record?.late_minutes>0).length,missing=rows.filter(x=>x.status==='Missing Punch').length;const full=rows.filter(x=>x.staff.employment_type==='Full Time'),part=rows.filter(x=>x.staff.employment_type!=='Full Time');const line=x=>{const r=x.record,s=x.staff;if(x.status==='Day Off')return `${s.name} — Day Off`;let z=`${s.name} — ${timeText(r?.punch_in)} → ${timeText(r?.punch_out)} | ${r?.presence_minutes?minsText(r.presence_minutes):'Incomplete'}`;if(r?.additional_minutes)z+=` | OT +${minsText(r.additional_minutes)}`;if(r?.late_minutes)z+=` | Late ${r.late_minutes} min`;if(x.status==='Missing Punch'||x.status==='On Duty')z+=` | ${x.status}`;if(r?.note)z+=` | Note: ${r.note}`;return z};let msg=`GOYA – Daily Staff Attendance\n${formatDate(date)}\n\nJoined: ${joined} | Completed: ${completed} | On Duty: ${on} | Late: ${late} | Day Off: ${off} | Missing Punch: ${missing}\n\nFull-Time Staff\n${full.map(line).join('\n')||'None'}`;if(part.length)msg+=`\n\nPart-Time / Temporary\n${part.map(line).join('\n')}`;$('dailyMessage').value=msg}catch(e){toast(e.message,true)}}
  function formatDate(s){const d=new Date(`${s}T12:00:00`);return d.toLocaleDateString('en-AE',{day:'numeric',month:'long',year:'numeric'})}
  function openDailyWhatsApp(){const msg=$('dailyMessage').value.trim();if(!msg){toast('Generate report first',true);return}window.open('https://wa.me/?text='+encodeURIComponent(msg),'_blank')}
  function dailyRowsExcel(){return state.daily.map(x=>({'Date':$('dailyDate').value,'Staff':x.staff.name,'Employment Type':x.staff.employment_type,'Punch In':timeText(x.record?.punch_in),'Punch Out':timeText(x.record?.punch_out),'Presence':x.record?minsText(x.record.presence_minutes):'','Net Work':x.record?minsText(x.record.net_work_minutes):'','OT':x.record?otText(x.record.additional_minutes):'','Late Minutes':x.record?.late_minutes||0,'Break Taken':x.record?(x.record.break_taken?'Yes':'No'):'','Status':x.status,'Note':x.record?.note||''}))}
  function exportDailyExcel(){if(!state.daily.length){toast('Generate report first',true);return}writeWorkbook({'Daily Attendance':dailyRowsExcel()},`Goya_Daily_Attendance_${$('dailyDate').value}.xlsx`)}

  async function buildPayrollMonth(m){const start=`${m}-01`,d=new Date(`${start}T12:00:00`);d.setMonth(d.getMonth()+1);d.setDate(0);const end=toDateOnly(d),days=d.getDate(),rec=await getRange(start,end),by=new Map();state.staff.filter(s=>s.active!==false).forEach(s=>by.set(s.id,{staff:s,records:[]}));rec.forEach(r=>{if(by.has(r.attendance_staff_id))by.get(r.attendance_staff_id).records.push(r)});const summary=[...by.values()].map(x=>{const dutyDates=new Set(x.records.filter(r=>!r.day_off&&(r.punch_in||r.punch_out)).map(r=>r.operational_date)),offDates=new Set(x.records.filter(r=>r.day_off).map(r=>r.operational_date)),duty=dutyDates.size,off=offDates.size,noRecord=Math.max(0,days-duty-off),presence=x.records.reduce((a,r)=>a+(r.presence_minutes||0),0),net=x.records.reduce((a,r)=>a+(r.net_work_minutes||0),0),ot=x.records.reduce((a,r)=>a+otBlockMin(r.additional_minutes||0),0),lateRows=x.records.filter(r=>(r.late_minutes||0)>0),late=lateRows.length,lateMinutes=lateRows.reduce((a,r)=>a+(r.late_minutes||0),0),breakDeduction=x.records.reduce((a,r)=>a+(!r.day_off&&r.break_taken?(r.break_minutes||x.staff.default_break_minutes||0):0),0),missing=x.records.filter(r=>recordStatus(r,r.operational_date)==='Missing Punch').length;let streak=0,maxStreak=0;for(let i=1;i<=days;i++){const ds=`${m}-${pad(i)}`;if(dutyDates.has(ds)){streak++;maxStreak=Math.max(maxStreak,streak)}else streak=0}return {...x.staff,duty,off,noRecord,presence,net,ot,late,lateMinutes,breakDeduction,missing,maxStreak,weekly:maxStreak>=7?'⚠ No Weekly Off':'OK'}});const staffMap=new Map(state.staff.map(s=>[s.id,s]));const details=[];rec.sort((a,b)=>a.operational_date.localeCompare(b.operational_date)||(a.staff_name||'').localeCompare(b.staff_name||'')).forEach(r=>{const st=staffMap.get(r.attendance_staff_id)||{};details.push({'Date':r.operational_date,'Staff':r.staff_name||st.name||'','Employment Type':r.employment_type||st.employment_type||'','Working Time':workingTimeText(r),'Presence':minsText(r.presence_minutes||0),'Net Work':minsText(r.net_work_minutes||0),'Break Taken':r.day_off?'':(r.break_taken?'Yes':'No'),'Break Deducted':r.day_off?'':(r.break_taken?minsText(r.break_minutes||st.default_break_minutes||0):'0h 00m'),'OT / Extra':otText(r.additional_minutes||0),'Late Minutes':r.late_minutes||0,'Status':recordStatus(r,r.operational_date),'Note':r.note||''})});return {start,end,summary,details}}
  async function generateMonthlySummary(){const m=$('monthPick').value||monthNow();try{const p=await buildPayrollMonth(m);state.monthly=p.summary;state.monthlyDetails=p.details;$('monthlyRows').innerHTML=state.monthly.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.employment_type)}</td><td>${x.duty}</td><td>${x.off}</td><td>${minsText(x.presence)}</td><td>${minsText(x.net)}</td><td>${x.ot?`+${otText(x.ot)}`:'—'}</td><td>${x.late}</td><td>${x.lateMinutes}</td><td>${minsText(x.breakDeduction)}</td><td>${x.missing}</td><td>${x.weekly}</td></tr>`).join('');return p}catch(e){toast(e.message,true);throw e}}
  function payrollSummaryRows(){return state.monthly.map(x=>({'Staff':x.name,'Employment Type':x.employment_type,'Duty Days':x.duty,'Day Off':x.off,'No Record Days':x.noRecord,'Total Presence':minsText(x.presence),'Net Working Hours':minsText(x.net),'OT / Extra Hours':otText(x.ot),'Late Days':x.late,'Late Minutes':x.lateMinutes,'Break Deducted':minsText(x.breakDeduction),'Missing Punch':x.missing,'Longest Duty Streak':x.maxStreak,'Weekly Off Compliance':x.weekly}))}
  async function exportMonthlyExcel(){if(!state.monthly.length)await generateMonthlySummary();writeWorkbook({'Monthly Summary':payrollSummaryRows(),'Daily Breakdown':state.monthlyDetails||[]},`Goya_HR_Attendance_${$('monthPick').value}.xlsx`)}
  async function exportHRRangeExcel(start,end,name){const rec=await getRange(start,end),staffMap=new Map(state.staff.map(s=>[s.id,s])),sumMap=new Map(),details=[];rec.forEach(r=>{const st=staffMap.get(r.attendance_staff_id)||{name:r.staff_name||'',employment_type:r.employment_type||''};if(!sumMap.has(r.attendance_staff_id))sumMap.set(r.attendance_staff_id,{Staff:st.name||r.staff_name||'','Employment Type':st.employment_type||r.employment_type||'','Duty Days':new Set(),'Total Presence Min':0,'Net Work Min':0,'OT Min':0,'Late Days':0,'Late Minutes':0,'Break Deduct Min':0,'Missing Punch':0});const x=sumMap.get(r.attendance_staff_id);x['Duty Days'].add(r.operational_date);x['Total Presence Min']+=r.presence_minutes||0;x['Net Work Min']+=r.net_work_minutes||0;x['OT Min']+=r.additional_minutes||0;if(r.late_minutes>0){x['Late Days']++;x['Late Minutes']+=r.late_minutes||0}if(r.break_taken)x['Break Deduct Min']+=r.break_minutes||st.default_break_minutes||0;if(recordStatus(r,r.operational_date)==='Missing Punch')x['Missing Punch']++;details.push({'Date':r.operational_date,'Staff':r.staff_name||st.name||'','Employment Type':r.employment_type||st.employment_type||'','Punch In':timeText(r.punch_in),'Punch Out':timeText(r.punch_out),'Presence':minsText(r.presence_minutes||0),'Net Work':minsText(r.net_work_minutes||0),'Break Taken':r.break_taken?'Yes':'No','OT / Extra':otText(r.additional_minutes||0),'Late Minutes':r.late_minutes||0,'Status':recordStatus(r,r.operational_date),'Note':r.note||''})});const summary=[...sumMap.values()].map(x=>({'Staff':x.Staff,'Employment Type':x['Employment Type'],'Duty Days':x['Duty Days'].size,'Total Presence':minsText(x['Total Presence Min']),'Net Working Hours':minsText(x['Net Work Min']),'OT / Extra Hours':otText(x['OT Min']),'Late Days':x['Late Days'],'Late Minutes':x['Late Minutes'],'Break Deducted':minsText(x['Break Deduct Min']),'Missing Punch':x['Missing Punch']}));writeWorkbook({'Staff Summary':summary,'Daily Breakdown':details},name)}
  async function exportManagementPDF(){if(!state.monthly.length)await generateMonthlySummary();if(!window.jspdf?.jsPDF)return toast('PDF library is still loading. Please try again.',true);const m=$('monthPick').value||monthNow(),{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(18);doc.text('GOYA - Monthly Staff Attendance',14,18);doc.setFontSize(10);doc.text(`Month: ${m}`,14,26);doc.autoTable({startY:32,head:[['Staff','Duty','Off','Net','OT','Late','Missing']],body:state.monthly.map(x=>[x.name,x.duty,x.off,minsText(x.net),otText(x.ot),x.late,x.missing]),styles:{fontSize:8,cellPadding:2},headStyles:{fillColor:[38,59,52]}});const detail=state.monthlyDetails||[];for(const st of state.monthly){doc.addPage();doc.setFontSize(16);doc.text(st.name,14,18);doc.setFontSize(10);doc.text(`Month: ${m}    Duty Days: ${st.duty}    Day Off: ${st.off}    Net: ${minsText(st.net)}    Total OT: ${otText(st.ot)}`,14,27);const rows=detail.filter(x=>x.Staff===st.name&&x.Status!=='No Record').map(x=>[x.Date,x['Working Time'],x.Status==='Day Off'?'—':x['OT / Extra']]);doc.autoTable({startY:34,head:[['Date','Working Time','Overtime']],body:rows,foot:[['','Total Overtime',otText(st.ot)]],styles:{fontSize:10,cellPadding:3},headStyles:{fillColor:[38,59,52]},footStyles:{fontStyle:'bold'}})}doc.save(`Goya_Management_Attendance_${m}.pdf`);toast('Management PDF downloaded')}
  async function finalizeMonthlyPayroll(){const m=$('monthPick').value||monthNow();try{await generateMonthlySummary();const summary=payrollSummaryRows(),details=state.monthlyDetails||[];await rpc('attendance_finalize_month',{p_token:state.token,p_month:`${m}-01`,p_summary:summary,p_details:details});writeWorkbook({'Monthly Summary':summary,'Daily Breakdown':details},`Goya_HR_Final_Attendance_${m}.xlsx`);toast(`Month ${m} finalized and HR Excel downloaded`)}catch(e){toast(e.message,true)}}
  function writeWorkbook(sheets,name){const wb=XLSX.utils.book_new();Object.entries(sheets).forEach(([n,rows])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),n.slice(0,31)));XLSX.writeFile(wb,name)}

  async function saveSettings(){const value={operational_start:$('setStart').value||'08:00',operational_cutoff:$('setCutoff').value||'02:00',late_grace_minutes:+$('setGrace').value||15,default_presence_minutes:Math.round((+$('setPresence').value||9)*60),default_break_minutes:+$('setBreak').value||60};try{await rpc('attendance_save_settings',{p_token:state.token,p_value:value});state.settings=value;toast('Attendance settings saved')}catch(e){toast(e.message,true)}}

  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!$('attLogin').classList.contains('hidden'))login()});
  window.GoyaAttendance={login,logout,nav,mobileMenu,loadDashboard,previewDeviceFile,setPreviewTime,setPreviewBreak,setPreviewNote,exportPreviewPDF,exportPreviewExcel,importDeviceFile,loadUploadHistory,downloadUpload,loadFinalizedReportHistory,redownloadFinalizedReport,regenerateFinalizedReport,loadSubmissions,saveSubmissionFinal,finalizeSelectedSubmissions,toggleAllSubmissions,updateSubSelected,loadHistory,exportHistoryExcel,editRecord,deleteRecord,saveManual,saveStaff,resetStaffForm,editStaff,renderStaffDetails,uploadDocument,loadDocuments,downloadDocument,deleteDocument,generateDailyReport,openDailyWhatsApp,exportDailyExcel,generateMonthlySummary,exportMonthlyExcel,exportManagementPDF,finalizeMonthlyPayroll,saveSettings};
})();
