(() => {
  const cfg = window.GOYA_CONFIG || {};
  let sb=null;
  const state={token:null,staff:[],settings:{},records:[],preview:[],history:[],monthly:[],daily:[]};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const pad=n=>String(n).padStart(2,'0');
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
  const monthNow=()=>today().slice(0,7);
  const toDateOnly=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const addDays=(s,n)=>{const d=new Date(`${s}T12:00:00`);d.setDate(d.getDate()+n);return toDateOnly(d)};
  const minsText=m=>{m=Math.max(0,Number(m)||0);return `${Math.floor(m/60)}h ${pad(m%60)}m`};
  const timeText=v=>{if(!v)return '—';const d=new Date(v.replace(' ','T'));if(Number.isNaN(d.getTime()))return String(v).slice(11,16);return d.toLocaleTimeString('en-AE',{hour:'numeric',minute:'2-digit'})};
  const toast=(msg,err=false)=>{const d=document.createElement('div');d.className='toast'+(err?' err':'');d.textContent=msg;$('toastHost').appendChild(d);setTimeout(()=>d.remove(),3500)};
  async function client(){if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY)throw new Error('Supabase config missing');if(!sb)sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}});return sb}
  async function rpc(name,args={}){await client();const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message);return data}
  function nav(btn,id){document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');document.querySelectorAll('[data-view]').forEach(x=>x.classList.add('hidden'));$(id)?.classList.remove('hidden');$('attSidebar').classList.remove('open');if(id==='attHistory')loadHistory();if(id==='attFiles')loadDocuments();if(id==='attStaffDetails')renderStaffDetails()}
  function mobileMenu(){$('attSidebar').classList.toggle('open')}
  async function login(){const pin=$('attAdminPin').value.trim();if(!/^\d{4,12}$/.test(pin)){toast('Enter Admin PIN',true);return}try{const d=await rpc('admin_login',{p_pin:pin});state.token=d.token;await bootstrap();$('attLogin').classList.add('hidden');$('attApp').classList.remove('hidden');toast('Attendance portal unlocked')}catch(e){toast(e.message,true)}}
  async function logout(){try{if(state.token)await rpc('logout',{p_token:state.token})}catch{}state.token=null;location.reload()}
  async function bootstrap(){const d=await rpc('attendance_bootstrap',{p_token:state.token});state.staff=d.staff||[];state.settings=d.settings||{};fillStaffSelects();fillSettings();const t=today();$('dashDate').value=t;$('manualDate').value=t;$('dailyDate').value=t;$('monthPick').value=monthNow();const first=`${monthNow()}-01`;$('histFrom').value=first;$('histTo').value=t;await loadDashboard()}
  function fillStaffSelects(){['manualStaff','fileStaff'].forEach(id=>{$(id).innerHTML=state.staff.map(s=>`<option value="${s.id}">${esc(s.name)}${s.employee_code?` · ${esc(s.employee_code)}`:''}</option>`).join('')});$('histStaff').innerHTML='<option value="">All Staff</option>'+state.staff.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}
  function fillSettings(){const s=state.settings;$('setStart').value=s.operational_start||'08:00';$('setCutoff').value=s.operational_cutoff||'02:00';$('setGrace').value=s.late_grace_minutes??15;$('setPresence').value=(s.default_presence_minutes??540)/60;$('setBreak').value=s.default_break_minutes??60}
  function recordStatus(r,date){if(!r)return 'Day Off';if(r.punch_in&&!r.punch_out)return date===today()?'On Duty':'Missing Punch';if(!r.punch_in&&r.punch_out)return 'Missing Punch';if(r.punch_in&&r.punch_out)return 'Completed';return 'Day Off'}
  function rowForStaff(s,r,date){return {staff:s,record:r,status:recordStatus(r,date)}}
  async function getRange(start,end){const d=await rpc('attendance_records_range',{p_token:state.token,p_start:start,p_end:end});state.staff=d.staff||state.staff;fillStaffSelects();return d.records||[]}
  async function loadDashboard(){try{const date=$('dashDate').value||today();const rec=await getRange(date,date);const map=new Map(rec.map(r=>[r.attendance_staff_id,r]));const rows=state.staff.filter(s=>s.active!==false).map(s=>rowForStaff(s,map.get(s.id),date));state.daily=rows;const c={joined:0,completed:0,on:0,late:0,off:0,missing:0};rows.forEach(x=>{if(x.record?.punch_in)c.joined++;if(x.status==='Completed')c.completed++;if(x.status==='On Duty')c.on++;if((x.record?.late_minutes||0)>0)c.late++;if(x.status==='Day Off')c.off++;if(x.status==='Missing Punch')c.missing++});$('dJoined').textContent=c.joined;$('dCompleted').textContent=c.completed;$('dOnDuty').textContent=c.on;$('dLate').textContent=c.late;$('dOff').textContent=c.off;$('dMissing').textContent=c.missing;$('dashRows').innerHTML=rows.map(({staff:s,record:r,status})=>`<tr><td><strong>${esc(s.name)}</strong></td><td>${esc(s.employment_type)}</td><td>${timeText(r?.punch_in)}</td><td>${timeText(r?.punch_out)}</td><td>${r?minsText(r.presence_minutes):'—'}</td><td>${r?minsText(r.net_work_minutes):'—'}</td><td>${r&&r.additional_minutes?`+${minsText(r.additional_minutes)}`:'—'}</td><td>${r&&r.late_minutes?`<span class="pill late">${r.late_minutes} min</span>`:'—'}</td><td>${r?(r.break_taken?'Yes':'No'):'—'}</td><td>${statusPill(status)}</td><td>${esc(r?.note||'')}</td></tr>`).join('')}catch(e){toast(e.message,true)}}
  function statusPill(s){const cls=s==='Completed'?'ok':s==='Day Off'?'off':s==='Missing Punch'?'missing':s==='On Duty'?'ok':'';return `<span class="pill ${cls}">${esc(s)}</span>`}

  // -------- DEVICE FILE PARSER --------
  const timeRegex=/(?:^|\D)([01]?\d|2[0-3]):([0-5]\d)(?::([0-5]\d))?(?:\D|$)/g;
  function parseTimes(v){if(v==null||v==='')return[];if(v instanceof Date)return [`${pad(v.getHours())}:${pad(v.getMinutes())}`];if(typeof v==='number'&&v>=0&&v<1){const mins=Math.round(v*1440)%1440;return [`${pad(Math.floor(mins/60))}:${pad(mins%60)}`]};const s=String(v);const out=[];let m;while((m=timeRegex.exec(s)))out.push(`${pad(+m[1])}:${m[2]}`);return out}
  function excelDate(v,yearHint,monthHint){if(v instanceof Date)return toDateOnly(v);if(typeof v==='number'&&v>30000){const d=XLSX.SSF.parse_date_code(v);if(d)return `${d.y}-${pad(d.m)}-${pad(d.d)}`};const s=String(v??'').trim();let m=s.match(/^(\d{4})[-\/.](\d{1,2})[-\/.](\d{1,2})$/);if(m)return `${m[1]}-${pad(+m[2])}-${pad(+m[3])}`;m=s.match(/^(\d{1,2})[-\/.](\d{1,2})(?:[-\/.](\d{2,4}))?$/);if(m){let y=m[3]?+m[3]:yearHint;if(y<100)y+=2000;return `${y}-${pad(+m[2])}-${pad(+m[1])}`};if(/^\d{1,2}$/.test(s)&&yearHint&&monthHint){const day=+s;if(day>=1&&day<=31)return `${yearHint}-${pad(monthHint)}-${pad(day)}`};return null}
  function combineLocal(date,time){return `${date}T${time}:00`}
  function normalizeEvents(events){const cutoff=$('setCutoff')?.value||state.settings.operational_cutoff||'02:00';const cutM=toMin(cutoff);const grouped=new Map();events.forEach(e=>{const tm=toMin(e.time);const op=tm<=cutM?addDays(e.date,-1):e.date;const key=`${e.name.toLowerCase()}|${e.code||''}|${op}`;if(!grouped.has(key))grouped.set(key,{name:e.name,employee_code:e.code||'',operational_date:op,events:[]});grouped.get(key).events.push({date:e.date,time:e.time,dt:combineLocal(e.date,e.time)})});return [...grouped.values()].map(g=>{g.events.sort((a,b)=>a.dt.localeCompare(b.dt));const first=g.events[0],last=g.events[g.events.length-1];return {name:g.name,employee_code:g.employee_code,operational_date:g.operational_date,punch_in:first?.dt||'',punch_out:g.events.length>1?last.dt:'',break_taken:true,note:''}}).sort((a,b)=>a.operational_date.localeCompare(b.operational_date)||a.name.localeCompare(b.name))}
  function toMin(t){const [h,m]=String(t||'00:00').split(':').map(Number);return h*60+m}
  function detectTablePattern(aoa){const aliases={name:['name','employee name','staff','person name','enroll name'],code:['id','employee id','employee code','user id','enroll number','no.','no'],date:['date','punch date','attendance date'],time:['time','punch time','check time','datetime','date/time']};let best=null;aoa.slice(0,20).forEach((row,ri)=>{const low=row.map(x=>String(x??'').trim().toLowerCase());const find=arr=>low.findIndex(x=>arr.includes(x));const idx={name:find(aliases.name),code:find(aliases.code),date:find(aliases.date),time:find(aliases.time)};let score=Object.values(idx).filter(x=>x>=0).length;if(score>=(idx.name>=0&&idx.date>=0&&idx.time>=0?3:99)&&(!best||score>best.score))best={ri,idx,score}});return best}
  function parseFlat(aoa,pat){const ev=[];for(let i=pat.ri+1;i<aoa.length;i++){const r=aoa[i];const name=String(r[pat.idx.name]??'').trim();if(!name)continue;const code=pat.idx.code>=0?String(r[pat.idx.code]??'').trim():'';let dval=r[pat.idx.date],tval=r[pat.idx.time];let date=excelDate(dval,new Date().getFullYear(),new Date().getMonth()+1);if(!date&&tval instanceof Date)date=toDateOnly(tval);const times=parseTimes(tval);if(date)times.forEach(time=>ev.push({name,code,date,time}))}return ev}
  function parseMatrix(aoa,fileName){const now=new Date();let year=now.getFullYear(),month=now.getMonth()+1;const fm=fileName.match(/(january|february|march|april|may|june|july|august|september|october|november|december)[^0-9]*(20\d{2})/i);if(fm){month=['january','february','march','april','may','june','july','august','september','october','november','december'].indexOf(fm[1].toLowerCase())+1;year=+fm[2]}const yhit=aoa.flat().map(x=>String(x??'')).join(' ').match(/20\d{2}/);if(yhit)year=+yhit[0];let best={ri:0,cols:[],score:0};for(let ri=0;ri<Math.min(25,aoa.length);ri++){const cols=[];aoa[ri].forEach((v,ci)=>{const d=excelDate(v,year,month);if(d)cols.push({ci,date:d})});if(cols.length>best.score)best={ri,cols,score:cols.length}}if(best.score<3)throw new Error('Could not identify the device report layout. Please use the original machine XLS/XLSX/CSV report.');const firstDateCol=Math.min(...best.cols.map(x=>x.ci));const ev=[];for(let i=best.ri+1;i<aoa.length;i++){const row=aoa[i];let name='',code='';for(let c=0;c<firstDateCol;c++){const s=String(row[c]??'').trim();if(!s)continue;if(!code&&/^\d{1,12}$/.test(s))code=s;else if(!name&&!/^\d+$/.test(s)&&s.length>1)name=s}if(!name)continue;best.cols.forEach(({ci,date})=>parseTimes(row[ci]).forEach(time=>ev.push({name,code,date,time})))}return ev}
  async function previewDeviceFile(){const f=$('deviceFile').files[0];if(!f){toast('Select a device report file',true);return}try{const buf=await f.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const aoa=XLSX.utils.sheet_to_json(ws,{header:1,raw:true,defval:''});const pat=detectTablePattern(aoa);let events=pat?parseFlat(aoa,pat):parseMatrix(aoa,f.name);if(!events.length)throw new Error('No punch times were detected in this file.');state.preview=normalizeEvents(events);const dates=state.preview.map(x=>x.operational_date);$('uploadInfo').textContent=`Detected ${state.preview.length} staff-day records · ${Math.min(...dates.map(Number))||''}`;$('uploadInfo').textContent=`Detected ${state.preview.length} normalized attendance records from ${dates.sort()[0]} to ${dates.sort().at(-1)}. Midnight punches up to ${state.settings.operational_cutoff||'02:00'} are attached to the previous operational day.`;$('uploadPreview').innerHTML=state.preview.slice(0,500).map((r,i)=>`<tr><td>${r.operational_date}</td><td>${esc(r.name)}</td><td>${esc(r.employee_code)}</td><td>${timeText(r.punch_in)}</td><td>${timeText(r.punch_out)}</td><td><select onchange="GoyaAttendance.setPreviewBreak(${i},this.value)"><option value="true" selected>Yes</option><option value="false">No</option></select></td><td><input value="${esc(r.note||'')}" placeholder="Optional note" onchange="GoyaAttendance.setPreviewNote(${i},this.value)"></td></tr>`).join('');$('importDeviceBtn').disabled=false}catch(e){state.preview=[];$('importDeviceBtn').disabled=true;toast(e.message,true)}}

  function setPreviewBreak(i,v){if(state.preview[i])state.preview[i].break_taken=v==='true'}
  function setPreviewNote(i,v){if(state.preview[i])state.preview[i].note=v||''}
  async function importDeviceFile(){if(!state.preview.length)return;const f=$('deviceFile').files[0];const dates=state.preview.map(x=>x.operational_date).sort();try{const d=await rpc('attendance_import_records',{p_token:state.token,p_rows:state.preview,p_file_name:f?.name||'Device report',p_upload_type:$('uploadType').value,p_date_from:dates[0],p_date_to:dates.at(-1)});toast(`Imported/updated ${d.imported} records${d.manual_preserved?` · preserved ${d.manual_preserved} manual corrections`:''}`);await bootstrap();$('dashDate').value=dates.at(-1);await loadDashboard()}catch(e){toast(e.message,true)}}

  async function loadHistory(){try{const start=$('histFrom').value||`${monthNow()}-01`,end=$('histTo').value||today();let rows=await getRange(start,end);const sf=$('histStaff').value;if(sf)rows=rows.filter(r=>r.attendance_staff_id===sf);state.history=rows;$('historyRows').innerHTML=rows.length?rows.map(r=>`<tr><td>${r.operational_date}</td><td>${esc(r.staff_name)}</td><td>${esc(r.employment_type)}</td><td>${timeText(r.punch_in)}</td><td>${timeText(r.punch_out)}</td><td>${minsText(r.presence_minutes)}</td><td>${minsText(r.net_work_minutes)}</td><td>${r.additional_minutes?`+${minsText(r.additional_minutes)}`:'—'}</td><td>${r.late_minutes?`${r.late_minutes} min`:'—'}</td><td>${r.break_taken?'Yes':'No'}</td><td>${statusPill(recordStatus(r,r.operational_date))}</td><td>${esc(r.note||'')}</td><td><button class="btn secondary" onclick="GoyaAttendance.editRecord('${r.id}')">Edit</button> <button class="btn danger" onclick="GoyaAttendance.deleteRecord('${r.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="13">No records.</td></tr>'}catch(e){toast(e.message,true)}}
  function editRecord(id){const r=state.history.find(x=>x.id===id);if(!r)return;nav(document.querySelector('.nav button:nth-child(4)'),'attManual');$('manualStaff').value=r.attendance_staff_id;$('manualDate').value=r.operational_date;$('manualIn').value=r.punch_in?String(r.punch_in).slice(0,16):'';$('manualOut').value=r.punch_out?String(r.punch_out).slice(0,16):'';$('manualBreak').value=String(!!r.break_taken);$('manualNote').value=r.note||''}
  async function deleteRecord(id){if(!confirm('Delete this attendance record?'))return;try{await rpc('attendance_delete_record',{p_token:state.token,p_id:id});toast('Record deleted');loadHistory()}catch(e){toast(e.message,true)}}
  function historyExportRows(){return state.history.map(r=>({'Date':r.operational_date,'Staff':r.staff_name,'Employment Type':r.employment_type,'Punch In':timeText(r.punch_in),'Punch Out':timeText(r.punch_out),'Presence':minsText(r.presence_minutes),'Net Work':minsText(r.net_work_minutes),'Additional/OT':minsText(r.additional_minutes),'Late Minutes':r.late_minutes,'Break Taken':r.break_taken?'Yes':'No','Status':recordStatus(r,r.operational_date),'Note':r.note||''}))}
  function exportHistoryExcel(){if(!state.history.length){toast('Load history first',true);return}writeWorkbook({'Attendance History':historyExportRows()},`Goya_Attendance_History_${$('histFrom').value}_to_${$('histTo').value}.xlsx`)}

  async function saveManual(){const sid=$('manualStaff').value,date=$('manualDate').value;if(!sid||!date){toast('Staff and duty date are required',true);return}try{await rpc('attendance_save_manual',{p_token:state.token,p_staff_id:sid,p_operational_date:date,p_punch_in:$('manualIn').value||null,p_punch_out:$('manualOut').value||null,p_break_taken:$('manualBreak').value==='true',p_note:$('manualNote').value||null});toast('Attendance saved');$('dashDate').value=date;await loadDashboard()}catch(e){toast(e.message,true)}}
  async function saveStaff(){const name=$('staffName').value.trim();if(!name){toast('Staff name required',true);return}try{await rpc('attendance_save_staff',{p_token:state.token,p_id:$('staffEditId').value||null,p_name:name,p_employee_code:$('staffCode').value||null,p_employment_type:$('staffType').value,p_designation:$('staffDesignation').value||null,p_phone:$('staffPhone').value||null,p_default_start_time:$('staffStart').value||'08:00',p_expected_presence_minutes:Math.round((+$('staffHours').value||0)*60),p_default_break_minutes:+$('staffBreak').value||0,p_active:$('staffActive').value==='true',p_notes:$('staffNotes').value||null});toast('Staff saved');resetStaffForm();await bootstrap();renderStaffDetails()}catch(e){toast(e.message,true)}}
  function resetStaffForm(){['staffEditId','staffName','staffCode','staffDesignation','staffPhone','staffNotes'].forEach(id=>$(id).value='');$('staffType').value='Full Time';$('staffStart').value='08:00';$('staffHours').value='9';$('staffBreak').value='60';$('staffActive').value='true'}
  function editStaff(id){const s=state.staff.find(x=>x.id===id);if(!s)return;nav(document.querySelector('.nav button:nth-child(5)'),'attAddStaff');$('staffEditId').value=s.id;$('staffName').value=s.name||'';$('staffCode').value=s.employee_code||'';$('staffType').value=s.employment_type||'Full Time';$('staffDesignation').value=s.designation||'';$('staffPhone').value=s.phone||'';$('staffStart').value=String(s.default_start_time||'08:00').slice(0,5);$('staffHours').value=(s.expected_presence_minutes||540)/60;$('staffBreak').value=s.default_break_minutes??60;$('staffActive').value=String(s.active!==false);$('staffNotes').value=s.notes||''}
  function renderStaffDetails(){const q=($('staffSearch').value||'').toLowerCase(),typ=$('staffTypeFilter').value;const list=state.staff.filter(s=>(!q||`${s.name} ${s.employee_code||''}`.toLowerCase().includes(q))&&(!typ||s.employment_type===typ));$('staffCards').innerHTML=list.map(s=>`<div class="staff-card"><h3>${esc(s.name)}</h3><p>${esc(s.employment_type)}${s.designation?` · ${esc(s.designation)}`:''}</p><p>Device Code: ${esc(s.employee_code||'Not set')}</p><p>Shift: ${String(s.default_start_time||'08:00').slice(0,5)} · ${(s.expected_presence_minutes||540)/60}h presence · ${s.default_break_minutes??60}m break</p><p>${esc(s.phone||'')}</p><button class="btn secondary" onclick="GoyaAttendance.editStaff('${s.id}')">Edit Details</button></div>`).join('')}

  async function uploadDocument(){const sid=$('fileStaff').value,f=$('staffFile').files[0],title=$('fileTitle').value.trim();if(!sid||!f||!title){toast('Staff, title and file required',true);return}if(f.size>5242880){toast('Maximum file size is 5 MB',true);return}try{const b64=await fileBase64(f);await rpc('attendance_upload_document',{p_token:state.token,p_staff_id:sid,p_title:title,p_file_name:f.name,p_mime_type:f.type||'application/octet-stream',p_file_size:f.size,p_base64:b64,p_note:$('fileNote').value||null});toast('Document uploaded');$('fileTitle').value='';$('fileNote').value='';$('staffFile').value='';loadDocuments()}catch(e){toast(e.message,true)}}
  function fileBase64(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(f)})}
  async function loadDocuments(){const sid=$('fileStaff').value;if(!sid){$('documentList').innerHTML='';return}try{const docs=await rpc('attendance_list_documents',{p_token:state.token,p_staff_id:sid});$('documentList').innerHTML=(docs||[]).map(d=>`<div class="doc-row"><div><strong>${esc(d.title)}</strong><div class="small muted">${esc(d.file_name)} · ${Math.round((d.file_size||0)/1024)} KB · ${new Date(d.created_at).toLocaleDateString('en-AE')}</div>${d.note?`<div>${esc(d.note)}</div>`:''}</div><div><button class="btn secondary" onclick="GoyaAttendance.downloadDocument('${d.id}')">Download</button> <button class="btn danger" onclick="GoyaAttendance.deleteDocument('${d.id}')">Delete</button></div></div>`).join('')||'<div class="notice">No documents.</div>'}catch(e){toast(e.message,true)}}
  async function downloadDocument(id){try{const d=await rpc('attendance_get_document',{p_token:state.token,p_id:id});const bin=atob(d.base64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([arr],{type:d.mime_type||'application/octet-stream'}));a.download=d.file_name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){toast(e.message,true)}}
  async function deleteDocument(id){if(!confirm('Delete this staff document?'))return;try{await rpc('attendance_delete_document',{p_token:state.token,p_id:id});loadDocuments()}catch(e){toast(e.message,true)}}

  async function generateDailyReport(){const date=$('dailyDate').value||today();try{const rec=await getRange(date,date),map=new Map(rec.map(r=>[r.attendance_staff_id,r]));const rows=state.staff.filter(s=>s.active!==false).map(s=>rowForStaff(s,map.get(s.id),date));state.daily=rows;const joined=rows.filter(x=>x.record?.punch_in).length,completed=rows.filter(x=>x.status==='Completed').length,on=rows.filter(x=>x.status==='On Duty').length,off=rows.filter(x=>x.status==='Day Off').length,late=rows.filter(x=>x.record?.late_minutes>0).length,missing=rows.filter(x=>x.status==='Missing Punch').length;const full=rows.filter(x=>x.staff.employment_type==='Full Time'),part=rows.filter(x=>x.staff.employment_type!=='Full Time');const line=x=>{const r=x.record,s=x.staff;if(x.status==='Day Off')return `${s.name} — Day Off`;let z=`${s.name} — ${timeText(r?.punch_in)} → ${timeText(r?.punch_out)} | ${r?.presence_minutes?minsText(r.presence_minutes):'Incomplete'}`;if(r?.additional_minutes)z+=` | OT +${minsText(r.additional_minutes)}`;if(r?.late_minutes)z+=` | Late ${r.late_minutes} min`;if(x.status==='Missing Punch'||x.status==='On Duty')z+=` | ${x.status}`;if(r?.note)z+=` | Note: ${r.note}`;return z};let msg=`GOYA – Daily Staff Attendance\n${formatDate(date)}\n\nJoined: ${joined} | Completed: ${completed} | On Duty: ${on} | Late: ${late} | Day Off: ${off} | Missing Punch: ${missing}\n\nFull-Time Staff\n${full.map(line).join('\n')||'None'}`;if(part.length)msg+=`\n\nPart-Time / Temporary\n${part.map(line).join('\n')}`;$('dailyMessage').value=msg}catch(e){toast(e.message,true)}}
  function formatDate(s){const d=new Date(`${s}T12:00:00`);return d.toLocaleDateString('en-AE',{day:'numeric',month:'long',year:'numeric'})}
  function openDailyWhatsApp(){const msg=$('dailyMessage').value.trim();if(!msg){toast('Generate report first',true);return}window.open('https://wa.me/?text='+encodeURIComponent(msg),'_blank')}
  function dailyRowsExcel(){return state.daily.map(x=>({'Date':$('dailyDate').value,'Staff':x.staff.name,'Employment Type':x.staff.employment_type,'Punch In':timeText(x.record?.punch_in),'Punch Out':timeText(x.record?.punch_out),'Presence':x.record?minsText(x.record.presence_minutes):'','Net Work':x.record?minsText(x.record.net_work_minutes):'','OT':x.record?minsText(x.record.additional_minutes):'','Late Minutes':x.record?.late_minutes||0,'Break Taken':x.record?(x.record.break_taken?'Yes':'No'):'','Status':x.status,'Note':x.record?.note||''}))}
  function exportDailyExcel(){if(!state.daily.length){toast('Generate report first',true);return}writeWorkbook({'Daily Attendance':dailyRowsExcel()},`Goya_Daily_Attendance_${$('dailyDate').value}.xlsx`)}

  async function generateMonthlySummary(){const m=$('monthPick').value||monthNow();const start=`${m}-01`,d=new Date(`${start}T12:00:00`);d.setMonth(d.getMonth()+1);d.setDate(0);const end=toDateOnly(d);try{const rec=await getRange(start,end);const days=d.getDate(),by=new Map();state.staff.filter(s=>s.active!==false).forEach(s=>by.set(s.id,{staff:s,records:[]}));rec.forEach(r=>{if(by.has(r.attendance_staff_id))by.get(r.attendance_staff_id).records.push(r)});state.monthly=[...by.values()].map(x=>{const workedDates=new Set(x.records.filter(r=>r.punch_in).map(r=>r.operational_date));const duty=workedDates.size,off=Math.max(0,days-duty),presence=x.records.reduce((a,r)=>a+(r.presence_minutes||0),0),net=x.records.reduce((a,r)=>a+(r.net_work_minutes||0),0),ot=x.records.reduce((a,r)=>a+(r.additional_minutes||0),0),late=x.records.filter(r=>r.late_minutes>0).length,missing=x.records.filter(r=>recordStatus(r,r.operational_date)==='Missing Punch').length;let streak=0,maxStreak=0;for(let i=1;i<=days;i++){const ds=`${m}-${pad(i)}`;if(workedDates.has(ds)){streak++;maxStreak=Math.max(maxStreak,streak)}else streak=0}return {...x.staff,duty,off,presence,net,ot,late,missing,weekly:maxStreak>=7?'⚠ No Weekly Off':'OK'}});$('monthlyRows').innerHTML=state.monthly.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.employment_type)}</td><td>${x.duty}</td><td>${x.off}</td><td>${minsText(x.presence)}</td><td>${minsText(x.net)}</td><td>${x.ot?`+${minsText(x.ot)}`:'—'}</td><td>${x.late}</td><td>${x.missing}</td><td>${x.weekly}</td></tr>`).join('')}catch(e){toast(e.message,true)}}
  function exportMonthlyExcel(){if(!state.monthly.length){toast('Generate monthly summary first',true);return}const summary=state.monthly.map(x=>({'Staff':x.name,'Employment Type':x.employment_type,'Duty Days':x.duty,'Day Off':x.off,'Total Presence':minsText(x.presence),'Net Work':minsText(x.net),'OT':minsText(x.ot),'Late Days':x.late,'Missing Punch':x.missing,'Weekly Off':x.weekly}));writeWorkbook({'Monthly Summary':summary},`Goya_Attendance_Summary_${$('monthPick').value}.xlsx`)}
  function writeWorkbook(sheets,name){const wb=XLSX.utils.book_new();Object.entries(sheets).forEach(([n,rows])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),n.slice(0,31)));XLSX.writeFile(wb,name)}

  async function saveSettings(){const value={operational_start:$('setStart').value||'08:00',operational_cutoff:$('setCutoff').value||'02:00',late_grace_minutes:+$('setGrace').value||15,default_presence_minutes:Math.round((+$('setPresence').value||9)*60),default_break_minutes:+$('setBreak').value||60};try{await rpc('attendance_save_settings',{p_token:state.token,p_value:value});state.settings=value;toast('Attendance settings saved')}catch(e){toast(e.message,true)}}

  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!$('attLogin').classList.contains('hidden'))login()});
  window.GoyaAttendance={login,logout,nav,mobileMenu,loadDashboard,previewDeviceFile,setPreviewBreak,setPreviewNote,importDeviceFile,loadHistory,exportHistoryExcel,editRecord,deleteRecord,saveManual,saveStaff,resetStaffForm,editStaff,renderStaffDetails,uploadDocument,loadDocuments,downloadDocument,deleteDocument,generateDailyReport,openDailyWhatsApp,exportDailyExcel,generateMonthlySummary,exportMonthlyExcel,saveSettings};
})();
