(() => {
  const cfg=window.GOYA_CONFIG||{};let sb=null,liveState={dashboard:null,history:[],rules:{},settingsLocations:[],serverOffset:0,timer:null};
  const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0'),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const ctx=()=>window.GoyaAttendance?._liveContext?.()||{};
  async function client(){if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY)throw new Error('Supabase config missing');if(!sb)sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}});return sb}
  async function rpc(name,args={}){const c=ctx();if(!c.token)throw new Error('Admin session expired. Please login again.');await client();const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message);return data}
  function toast(msg,err=false){const host=$('toastHost')||document.body,d=document.createElement('div');d.className='toast'+(err?' err':'');d.textContent=msg;host.appendChild(d);setTimeout(()=>d.remove(),3800)}
  const fmtTime=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString('en-AE',{hour:'numeric',minute:'2-digit'})};
  const fmtDate=v=>{const d=new Date(v+'T12:00:00');return d.toLocaleDateString('en-AE',{day:'2-digit',month:'short',year:'numeric'})};
  const mins=m=>{m=Math.max(0,Math.floor(Number(m)||0));return `${Math.floor(m/60)}h ${pad(m%60)}m`};
  const otText=m=>{m=Math.floor(Math.max(0,Number(m)||0)/30)*30;if(!m)return '0';if(m===30)return '30 min';const h=m/60;return `${Number.isInteger(h)?h:h.toFixed(1)} ${h===1?'hour':'hours'}`};
  function calc(row,serverNow=null){const rules=liveState.rules||{},sessions=Array.isArray(row.sessions)?row.sessions:[];let sec=0;const now=serverNow?new Date(serverNow).getTime():Date.now()+liveState.serverOffset;sessions.forEach((s,i)=>{let st=new Date(s.check_in_at).getTime();if(i===0&&row.scheduled_start){const sch=new Date(`${row.operational_date}T${String(row.scheduled_start).slice(0,5)}:00+04:00`).getTime();if(Number.isFinite(sch)&&st<sch)st=sch}const en=s.check_out_at?new Date(s.check_out_at).getTime():now;if(Number.isFinite(st)&&Number.isFinite(en)&&en>st)sec+=(en-st)/1000});const breakTaken=row.break_taken!==false,target=breakTaken?(Number(rules.duty_presence_minutes)||540):(Number(rules.regular_net_minutes)||480),net=Math.max(0,sec/60-(breakTaken?(Number(rules.break_minutes)||60):0)),ot=Math.floor(Math.max(0,net-(Number(rules.regular_net_minutes)||480))/30)*30;return {sec,net,ot,target,remaining:Math.max(0,target-sec/60),liveOt:Math.max(0,sec/60-target)}}
  function groupDashboard(d){const dayMap=new Map((d.days||[]).map(x=>[x.staff_id,x])),sessMap=new Map();for(const s of d.sessions||[]){if(!sessMap.has(s.staff_id))sessMap.set(s.staff_id,[]);sessMap.get(s.staff_id).push(s)}return (d.staff||[]).map(st=>{const day=dayMap.get(st.id)||{operational_date:d.operational_date,break_taken:true,classification:'Day Off - Pending Review',late_minutes:0},sessions=sessMap.get(st.id)||[];return {...day,staff_id:st.id,staff_name:st.name,sections:st.sections||[],sessions}})}
  function status(row){const ss=row.sessions||[],open=ss.some(s=>!s.check_out_at);if(open)return 'On Duty';if(ss.length)return 'Completed';return row.classification||'Day Off - Pending Review'}
  function verification(row){const ss=row.sessions||[];if(!ss.length)return '—';const last=ss[ss.length-1],okIn=ss.every(s=>s.check_in_verified),okOut=ss.filter(s=>s.check_out_at).every(s=>s.check_out_verified);return okIn&&okOut?'Verified':'Review'}
  function locationText(row){const ss=row.sessions||[];const s=ss[ss.length-1];return s?.check_out_location_name||s?.check_in_location_name||'—'}
  function renderDashboard(){const d=liveState.dashboard;if(!d)return;const rows=groupDashboard(d),serverNow=d.server_now;let on=0,completed=0,late=0,pending=0;rows.forEach(r=>{const st=status(r);if(st==='On Duty')on++;if(st==='Completed')completed++;if((r.late_minutes||0)>0)late++;if(st==='Day Off - Pending Review')pending++});$('liveDOn').textContent=on;$('liveDCompleted').textContent=completed;$('liveDLate').textContent=late;$('liveDPending').textContent=pending;$('liveDashboardRows').innerHTML=rows.map(r=>{const c=calc(r,serverNow),ss=r.sessions||[],first=ss[0],open=ss.find(s=>!s.check_out_at),remain=c.remaining>0?mins(c.remaining):`OT ${mins(c.liveOt)}`;return `<tr><td><strong>${esc(r.staff_name)}</strong><div class="small muted">${esc((r.sections||[]).join(', ')||'—')}</div></td><td>${esc(status(r))}</td><td>${fmtTime(first?.check_in_at)}</td><td>${mins(c.sec/60)}</td><td>${open?remain:'—'}</td><td>${r.late_minutes?`${r.late_minutes} min`:'—'}</td><td>${ss.length}</td><td>${esc(locationText(r))}</td><td>${verification(r)==='Verified'?'<span class="live-verify ok">Verified</span>':'<span class="live-verify bad">Review</span>'}</td></tr>`}).join('')}
  async function loadDashboard(){try{const date=$('liveDashDate')?.value||new Date().toISOString().slice(0,10),d=await rpc('attendance_live_admin_dashboard',{p_token:ctx().token,p_date:date});liveState.dashboard=d;liveState.rules=d.rules||{};liveState.serverOffset=new Date(d.server_now).getTime()-Date.now();renderDashboard();clearInterval(liveState.timer);liveState.timer=setInterval(renderDashboard,1000)}catch(e){toast(e.message,true)}}
  function classificationOptions(cur){return ['Day Off - Pending Review','Weekly Off','Leave','Sick Leave','Unpaid Leave','Absent','Public Holiday','Other Approved','Duty'].map(x=>`<option${x===cur?' selected':''}>${x}</option>`).join('')}
  async function loadHistory(){try{const from=$('liveHistFrom').value,to=$('liveHistTo').value,staff=$('liveHistStaff').value||null;if(!from||!to)return toast('Select From and To dates.',true);const d=await rpc('attendance_live_admin_history',{p_token:ctx().token,p_start:from,p_end:to,p_staff_id:staff});liveState.rules=d.rules||liveState.rules;liveState.serverOffset=new Date(d.server_now).getTime()-Date.now();liveState.history=d.rows||[];renderHistory()}catch(e){toast(e.message,true)}}
  function renderHistory(){const filter=$('liveHistStatus')?.value||'',rows=(liveState.history||[]).filter(r=>!filter||status(r)===filter||r.classification===filter);$('liveHistoryAdminRows').innerHTML=rows.length?rows.map(r=>{const c=calc(r),ss=r.sessions||[],first=ss[0],last=ss[ss.length-1],st=status(r),isNo=!ss.length;return `<tr><td>${esc(r.operational_date)}</td><td><strong>${esc(r.staff_name)}</strong><div class="small muted">${esc((r.sections||[]).join(', ')||'')}</div></td><td>${ss.length?`${fmtTime(first?.check_in_at)} → ${fmtTime(last?.check_out_at)}`:'—'}</td><td>${ss.length}</td><td>${ss.length?mins(c.sec/60):'—'}</td><td>${ss.length?mins(c.net):'—'}</td><td>${c.ot?otText(c.ot):'—'}</td><td>${r.late_minutes?`${r.late_minutes} min`:'—'}</td><td>${isNo?`<select class="live-classify" data-staff="${r.staff_id}" data-date="${r.operational_date}">${classificationOptions(r.classification||'Day Off - Pending Review')}</select>`:esc(st)}</td><td>${isNo?`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.saveClassification('${r.staff_id}','${r.operational_date}',this)">Save</button>`:`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.editDay('${r.staff_id}','${r.operational_date}')">Edit</button>`}</td></tr>`}).join(''):'<tr><td colspan="10" class="empty">No records for selected filters.</td></tr>'}
  async function saveClassification(staffId,date,btn){const sel=btn.closest('tr').querySelector('.live-classify'),val=sel.value,note=prompt('Optional admin note for this day:','')||null;try{await rpc('attendance_live_admin_classify_day',{p_token:ctx().token,p_staff_id:staffId,p_date:date,p_classification:val,p_note:note});toast('Day classification saved.');await loadHistory()}catch(e){toast(e.message,true)}}
  function toLocalInput(v){if(!v)return '';const d=new Date(v),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
  async function editDay(staffId,date){const r=(liveState.history||[]).find(x=>x.staff_id===staffId&&x.operational_date===date);if(!r||!(r.sessions||[]).length)return;const modal=$('liveEditModal'),list=$('liveEditSessions');list.innerHTML=r.sessions.map(s=>`<div class="live-edit-session"><strong>Session ${s.session_no}</strong><label>Check In<input type="datetime-local" data-id="${s.id}" data-field="in" value="${toLocalInput(s.check_in_at)}"></label><label>Check Out<input type="datetime-local" data-id="${s.id}" data-field="out" value="${toLocalInput(s.check_out_at)}"></label><button class="btn secondary tiny" onclick="GoyaLiveAdmin.saveSessionEdit('${s.id}',this)">Save Session</button></div>`).join('');$('liveEditTitle').textContent=`${r.staff_name} · ${date}`;modal.classList.remove('hidden')}
  function localInputToIso(v){if(!v)return null;const d=new Date(v);return d.toISOString()}
  async function saveSessionEdit(id,btn){const box=btn.closest('.live-edit-session'),pin=box.querySelector('[data-field="in"]').value,pout=box.querySelector('[data-field="out"]').value;try{await rpc('attendance_live_admin_update_session',{p_token:ctx().token,p_session_id:id,p_check_in:localInputToIso(pin),p_check_out:localInputToIso(pout)});toast('Live session corrected and audit saved.');await loadHistory();$('liveEditModal').classList.add('hidden')}catch(e){toast(e.message,true)}}
  function closeEdit(){$('liveEditModal')?.classList.add('hidden')}
  function excelRows(){return (liveState.history||[]).map(r=>{const c=calc(r),ss=r.sessions||[],first=ss[0],last=ss[ss.length-1];return {'Date':r.operational_date,'Staff':r.staff_name,'Section':(r.sections||[]).join(', '),'Working Time':ss.length?`${fmtTime(first?.check_in_at)} - ${fmtTime(last?.check_out_at)}`:'','Sessions':ss.length,'Working Hours':ss.length?mins(c.sec/60):'','Net Hours':ss.length?mins(c.net):'','OT':c.ot?otText(c.ot):'','Late Minutes':r.late_minutes||0,'Break Taken':ss.length?(r.break_taken!==false?'Yes':'No'):'','Status':status(r),'Verification':verification(r),'Location':locationText(r),'Note':r.classification_note||''}})}
  function exportExcel(){if(!liveState.history.length)return toast('Load history first.',true);const wb=XLSX.utils.book_new(),rows=excelRows();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Live Attendance');XLSX.writeFile(wb,`Goya_Live_Attendance_${$('liveHistFrom').value}_${$('liveHistTo').value}.xlsx`)}
  function exportPDF(){if(!liveState.history.length)return toast('Load history first.',true);if(!window.jspdf?.jsPDF)return toast('PDF library is still loading.',true);const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape'}),rows=excelRows();doc.setFontSize(18);doc.text('GOYA - Live Attendance Report',14,16);doc.setFontSize(10);doc.text(`Period: ${$('liveHistFrom').value} to ${$('liveHistTo').value}`,14,24);doc.autoTable({startY:30,head:[['Date','Staff','Section','Working Time','Sessions','Working','Net','OT','Late','Break','Status','Verification']],body:rows.map(x=>[x.Date,x.Staff,x.Section,x['Working Time'],x.Sessions,x['Working Hours'],x['Net Hours'],x.OT,x['Late Minutes']||'—',x['Break Taken'],x.Status,x.Verification]),styles:{fontSize:7,cellPadding:2},headStyles:{fillColor:[38,59,52]}});doc.save(`Goya_Live_Attendance_${$('liveHistFrom').value}_${$('liveHistTo').value}.pdf`)}
  async function getPublicIp(){for(const url of ['https://api.ipify.org?format=json','https://api64.ipify.org?format=json']){try{const r=await fetch(url,{cache:'no-store'});if(r.ok){const j=await r.json();if(j.ip)return j.ip}}catch{}}throw new Error('Could not detect public IP.')}
  function getGps(){return new Promise((resolve,reject)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy}),e=>reject(new Error(e.code===1?'Allow location permission first.':'Could not get GPS.')),{enableHighAccuracy:true,timeout:15000}):reject(new Error('GPS unsupported.')))}
  function renderLocations(){const host=$('liveLocationList');if(!host)return;host.innerHTML=liveState.settingsLocations.length?liveState.settingsLocations.map((l,i)=>`<div class="live-location-row"><div><strong>${esc(l.name||'Workplace')}</strong><span>${Number(l.lat).toFixed(6)}, ${Number(l.lon).toFixed(6)} · ${l.radius_m||150}m</span></div><button class="btn danger tiny" onclick="GoyaLiveAdmin.removeLocation(${i})">Remove</button></div>`).join(''):'<div class="live-empty">No workplace location configured yet.</div>'}
  async function loadSettings(){try{const r=await rpc('attendance_live_admin_settings',{p_token:ctx().token});liveState.rules=r||{};liveState.settingsLocations=Array.isArray(r.locations)?r.locations:[];$('liveRequireLocation').checked=r.require_location!==false;$('liveRequireNetwork').checked=r.require_network!==false;$('liveDutyHours').value=(Number(r.duty_presence_minutes)||540)/60;$('liveBreakMinutes').value=Number(r.break_minutes)||60;$('liveApprovedIps').value=(Array.isArray(r.approved_public_ips)?r.approved_public_ips:[]).join('\n');renderLocations()}catch(e){toast(e.message,true)}}
  async function detectLocation(){try{const g=await getGps();$('liveLocLat').value=g.lat.toFixed(7);$('liveLocLon').value=g.lon.toFixed(7);toast(`GPS captured ±${Math.round(g.accuracy||0)}m`)}catch(e){toast(e.message,true)}}
  async function detectIp(){try{const ip=await getPublicIp(),box=$('liveApprovedIps'),ips=box.value.split(/\s+/).filter(Boolean);if(!ips.includes(ip))ips.push(ip);box.value=ips.join('\n');toast(`Current public IP added: ${ip}`)}catch(e){toast(e.message,true)}}
  function addLocation(){const name=$('liveLocName').value.trim()||'Workplace',lat=+$('liveLocLat').value,lon=+$('liveLocLon').value,radius=+$('liveLocRadius').value||150;if(!Number.isFinite(lat)||!Number.isFinite(lon))return toast('Capture or enter valid GPS coordinates.',true);liveState.settingsLocations.push({name,lat,lon,radius_m:radius,active:true});$('liveLocName').value='';renderLocations()}
  function removeLocation(i){liveState.settingsLocations.splice(i,1);renderLocations()}
  async function saveSettings(){const ips=[...new Set($('liveApprovedIps').value.split(/\s+/).map(x=>x.trim()).filter(Boolean))],value={require_location:$('liveRequireLocation').checked,require_network:$('liveRequireNetwork').checked,duty_presence_minutes:Math.round((+$('liveDutyHours').value||9)*60),regular_net_minutes:480,break_minutes:+$('liveBreakMinutes').value||60,late_grace_minutes:15,operational_cutoff:'02:00',shift_start_times:['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00'],locations:liveState.settingsLocations,approved_public_ips:ips};try{liveState.rules=await rpc('attendance_live_admin_save_settings',{p_token:ctx().token,p_value:value});toast('Live Attendance settings saved.')}catch(e){toast(e.message,true)}}
  function fillStaffFilter(){const sel=$('liveHistStaff'),staff=ctx().staff||[];if(sel&&!sel.dataset.ready){sel.innerHTML='<option value="">All Staff</option>'+staff.map(s=>`<option value="${s.portal_staff_id||s.id}">${esc(s.name)}</option>`).join('');sel.dataset.ready='1'}}
  function openDashboard(){fillStaffFilter();if(!$('liveDashDate').value)$('liveDashDate').value=new Date().toISOString().slice(0,10);loadDashboard()}
  function openHistory(){fillStaffFilter();const d=new Date(),end=d.toISOString().slice(0,10),start=`${end.slice(0,7)}-01`;if(!$('liveHistFrom').value)$('liveHistFrom').value=start;if(!$('liveHistTo').value)$('liveHistTo').value=end;loadHistory()}
  function openSettings(){loadSettings()}
  window.GoyaLiveAdmin={openDashboard,loadDashboard,openHistory,loadHistory,renderHistory,saveClassification,editDay,saveSessionEdit,closeEdit,exportExcel,exportPDF,openSettings,loadSettings,detectLocation,detectIp,addLocation,removeLocation,saveSettings};
  if(window.GoyaAttendance){window.GoyaAttendance.openLiveDashboard=openDashboard;window.GoyaAttendance.openLiveHistory=openHistory;window.GoyaAttendance.openLiveSettings=openSettings;}
})();
