(() => {
  const cfg=window.GOYA_CONFIG||{};
  let sb=null,liveState={dashboard:null,history:[],rules:{},settingsLocations:[],serverOffset:0,timer:null};
  const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0'),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const ctx=()=>window.GoyaAttendance?._liveContext?.()||{};
  async function client(){if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY)throw new Error('Supabase config missing');if(!sb)sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}});return sb}
  async function rpc(name,args={}){const c=ctx();if(!c.token)throw new Error('Admin session expired. Please login again.');await client();const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message);return data}
  function toast(msg,err=false){const host=$('toastHost')||document.body,d=document.createElement('div');d.className='toast'+(err?' err':'');d.textContent=msg;host.appendChild(d);setTimeout(()=>d.remove(),3800)}
  const fmtTime=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString('en-AE',{hour:'numeric',minute:'2-digit'})};
  const fmtDate=v=>{const d=new Date(v+'T12:00:00');return d.toLocaleDateString('en-AE',{day:'2-digit',month:'short',year:'numeric'})};
  const mins=m=>{m=Math.max(0,Math.floor(Number(m)||0));return `${Math.floor(m/60)}h ${pad(m%60)}m`};
  const otText=m=>{m=Math.floor(Math.max(0,Number(m)||0)/30)*30;if(!m)return '0';if(m===30)return '30 min';const h=m/60;return `${Number.isInteger(h)?h:h.toFixed(1)} ${h===1?'hour':'hours'}`};
  function calc(row,serverNow=null){const rules=liveState.rules||{},sessions=Array.isArray(row.sessions)?row.sessions:[];let sec=0;const now=serverNow?new Date(serverNow).getTime():Date.now()+liveState.serverOffset;sessions.forEach((s,i)=>{let st=new Date(s.check_in_at).getTime();if(i===0&&row.scheduled_start){const sch=new Date(`${row.operational_date}T${String(row.scheduled_start).slice(0,5)}:00+04:00`).getTime();if(Number.isFinite(sch)&&st<sch)st=sch}const en=s.check_out_at?new Date(s.check_out_at).getTime():now;if(Number.isFinite(st)&&Number.isFinite(en)&&en>st)sec+=(en-st)/1000});const breakTaken=row.break_taken!==false,target=breakTaken?(Number(rules.duty_presence_minutes)||540):(Number(rules.regular_net_minutes)||480),net=Math.max(0,sec/60-(breakTaken?(Number(rules.break_minutes)||60):0)),ot=Math.floor(Math.max(0,net-(Number(rules.regular_net_minutes)||480))/30)*30;return {sec,net,ot,target,remaining:Math.max(0,target-sec/60),liveOt:Math.max(0,sec/60-target)}}
  function groupDashboard(d){const dayMap=new Map((d.days||[]).map(x=>[x.staff_id,x])),sessMap=new Map();for(const s of d.sessions||[]){if(!sessMap.has(s.staff_id))sessMap.set(s.staff_id,[]);sessMap.get(s.staff_id).push(s)}return (d.staff||[]).map(st=>{const day=dayMap.get(st.id)||{operational_date:d.operational_date,break_taken:true,classification:'Day Off - Pending Review',late_minutes:0},sessions=sessMap.get(st.id)||[];return {...day,staff_id:st.id,staff_name:st.name,sections:st.sections||[],sessions}})}
  function status(row){const ss=row.sessions||[],open=ss.some(s=>!s.check_out_at);if(open)return 'On Duty';if(ss.length)return row.classification&&row.classification!=='Day Off - Pending Review'?row.classification:'Completed';return row.classification||'Day Off - Pending Review'}
  function verification(row){const ss=row.sessions||[];if(!ss.length)return '—';const okIn=ss.every(s=>s.check_in_verified),okOut=ss.filter(s=>s.check_out_at).length===ss.length&&ss.filter(s=>s.check_out_at).every(s=>s.check_out_verified);return okIn&&okOut?'Verified':'Review'}
  function locationText(row){const ss=row.sessions||[],s=ss[ss.length-1];return s?.check_out_location_name||s?.check_in_location_name||'—'}
  function verificationBadge(r){return verification(r)==='Verified'?'<span class="live-verify ok">✓ Verified</span>':'<span class="live-verify bad">! Review</span>'}
  function renderDashboard(){const d=liveState.dashboard;if(!d)return;const rows=groupDashboard(d),serverNow=d.server_now;let on=0,completed=0,late=0,pending=0;rows.forEach(r=>{const st=status(r);if(st==='On Duty')on++;if(st==='Completed'||(r.sessions||[]).length&&!r.sessions.some(s=>!s.check_out_at))completed++;if((r.late_minutes||0)>0)late++;if(st==='Day Off - Pending Review')pending++});$('liveDOn').textContent=on;$('liveDCompleted').textContent=completed;$('liveDLate').textContent=late;$('liveDPending').textContent=pending;
    const rowHtml=rows.map(r=>{const c=calc(r,serverNow),ss=r.sessions||[],first=ss[0],open=ss.find(s=>!s.check_out_at),remain=c.remaining>0?mins(c.remaining):`OT ${mins(c.liveOt)}`,act=ss.length?`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.editDay('${r.staff_id}','${r.operational_date}')">${open?'Fix Checkout':'Edit'}</button>`:'—';return `<tr><td><strong>${esc(r.staff_name)}</strong><div class="small muted">${esc((r.sections||[]).join(', ')||'—')}</div></td><td>${esc(status(r))}</td><td>${fmtTime(first?.check_in_at)}</td><td>${mins(c.sec/60)}</td><td>${open?remain:'—'}</td><td>${r.late_minutes?`${r.late_minutes} min`:'—'}</td><td>${ss.length}</td><td>${esc(locationText(r))}</td><td>${verificationBadge(r)}</td><td>${act}</td></tr>`}).join('');
    $('liveDashboardRows').innerHTML=rowHtml;
    const cards=$('liveDashboardCards');if(cards)cards.innerHTML=rows.map(r=>{const c=calc(r,serverNow),ss=r.sessions||[],first=ss[0],open=ss.find(s=>!s.check_out_at);return `<article class="live-duty-card ${open?'active':''}"><header><div><strong>${esc(r.staff_name)}</strong><span>${esc((r.sections||[]).join(', ')||'—')}</span></div><b>${esc(status(r))}</b></header><div class="live-duty-grid"><span>Check In<b>${fmtTime(first?.check_in_at)}</b></span><span>Working<b>${mins(c.sec/60)}</b></span><span>${open?(c.remaining>0?'Remaining':'OT'):'Sessions'}<b>${open?(c.remaining>0?mins(c.remaining):mins(c.liveOt)):ss.length}</b></span><span>Late<b>${r.late_minutes?`${r.late_minutes}m`:'—'}</b></span></div><footer>${verificationBadge(r)}${ss.length?`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.editDay('${r.staff_id}','${r.operational_date}')">${open?'Fix Checkout':'Edit'}</button>`:''}</footer></article>`}).join('');
  }
  async function loadDashboard(){try{const date=$('liveDashDate')?.value||new Date().toISOString().slice(0,10),d=await rpc('attendance_live_admin_dashboard',{p_token:ctx().token,p_date:date});liveState.dashboard=d;liveState.rules=d.rules||{};liveState.serverOffset=new Date(d.server_now).getTime()-Date.now();renderDashboard();clearInterval(liveState.timer);liveState.timer=setInterval(renderDashboard,1000)}catch(e){toast(e.message,true)}}
  function classificationOptions(cur){return ['Day Off - Pending Review','Weekly Off','Leave','Sick Leave','Unpaid Leave','Absent','Public Holiday','Other Approved','Duty'].map(x=>`<option${x===cur?' selected':''}>${x}</option>`).join('')}
  function applyMonth(){const m=$('liveHistMonth')?.value;if(!m)return;const [y,mo]=m.split('-').map(Number),end=new Date(y,mo,0).getDate();$('liveHistFrom').value=`${m}-01`;$('liveHistTo').value=`${m}-${pad(end)}`}
  async function loadHistory(){try{const from=$('liveHistFrom').value,to=$('liveHistTo').value,staff=$('liveHistStaff').value||null;if(!from||!to)return toast('Select From and To dates.',true);const d=await rpc('attendance_live_admin_history',{p_token:ctx().token,p_start:from,p_end:to,p_staff_id:staff});liveState.rules=d.rules||liveState.rules;liveState.serverOffset=new Date(d.server_now).getTime()-Date.now();liveState.history=d.rows||[];renderHistory()}catch(e){toast(e.message,true)}}
  function filteredRows(){const filter=$('liveHistStatus')?.value||'';return (liveState.history||[]).filter(r=>!filter||status(r)===filter||r.classification===filter)}
  function summaryFor(rows){const o={days:rows.length,duty:0,weekly:0,leave:0,sick:0,unpaid:0,absent:0,holiday:0,other:0,pending:0,work:0,net:0,ot:0,lateDays:0,lateMin:0,noBreak:0,split:0,review:0};rows.forEach(r=>{const c=calc(r),ss=r.sessions||[],st=status(r);if(ss.length){o.duty++;o.work+=c.sec/60;o.net+=c.net;o.ot+=c.ot;if(r.break_taken===false)o.noBreak++;if(ss.length>1)o.split++;if(verification(r)!=='Verified'||ss.some(s=>!s.check_out_at))o.review++}if(r.late_minutes){o.lateDays++;o.lateMin+=Number(r.late_minutes)||0}if(st==='Weekly Off')o.weekly++;else if(st==='Leave')o.leave++;else if(st==='Sick Leave')o.sick++;else if(st==='Unpaid Leave')o.unpaid++;else if(st==='Absent')o.absent++;else if(st==='Public Holiday')o.holiday++;else if(st==='Other Approved')o.other++;else if(st==='Day Off - Pending Review')o.pending++});return o}
  function renderSummary(rows){const s=summaryFor(rows),host=$('liveReportSummary');if(host)host.innerHTML=[['Duty Days',s.duty],['Weekly Off',s.weekly],['Leave',s.leave+s.sick+s.unpaid],['Working',mins(s.work)],['Net',mins(s.net)],['OT',otText(s.ot)],['Late Days',s.lateDays],['Split Shift',s.split],['Pending',s.pending],['Review',s.review]].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');
    const by=new Map();rows.forEach(r=>{if(!by.has(r.staff_id))by.set(r.staff_id,[]);by.get(r.staff_id).push(r)});const ph=$('livePersonSummary');if(ph)ph.innerHTML=[...by.values()].map(rs=>{const x=summaryFor(rs),r=rs[0];return `<article><header><strong>${esc(r.staff_name)}</strong><span>${esc((r.sections||[]).join(', ')||'—')}</span></header><div><span>Duty <b>${x.duty}</b></span><span>Net <b>${mins(x.net)}</b></span><span>OT <b>${otText(x.ot)}</b></span><span>Late <b>${x.lateDays}</b></span><span>Off/Leave <b>${x.weekly+x.leave+x.sick+x.unpaid+x.holiday+x.other+x.pending}</b></span></div></article>`}).join('')}
  function renderHistory(){const rows=filteredRows();renderSummary(rows);$('liveHistoryAdminRows').innerHTML=rows.length?rows.map(r=>{const c=calc(r),ss=r.sessions||[],first=ss[0],last=ss[ss.length-1],st=status(r),isNo=!ss.length;return `<tr><td>${esc(r.operational_date)}</td><td><strong>${esc(r.staff_name)}</strong><div class="small muted">${esc((r.sections||[]).join(', ')||'')}</div></td><td>${ss.length?ss.map(s=>`${fmtTime(s.check_in_at)} → ${fmtTime(s.check_out_at)}`).join('<br>'):'—'}</td><td>${ss.length}</td><td>${ss.length?mins(c.sec/60):'—'}</td><td>${ss.length?mins(c.net):'—'}</td><td>${c.ot?otText(c.ot):'—'}</td><td>${r.late_minutes?`${r.late_minutes} min`:'—'}</td><td>${ss.length?(r.break_taken!==false?'Yes':'No'):'—'}</td><td>${isNo?`<select class="live-classify" data-staff="${r.staff_id}" data-date="${r.operational_date}">${classificationOptions(r.classification||'Day Off - Pending Review')}</select>`:esc(st)}</td><td>${ss.length?verificationBadge(r):'—'}</td><td>${isNo?`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.saveClassification('${r.staff_id}','${r.operational_date}',this)">Save</button>`:`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.editDay('${r.staff_id}','${r.operational_date}')">Edit</button>`}</td></tr>`}).join(''):'<tr><td colspan="12" class="empty">No records for selected filters.</td></tr>'}
  async function saveClassification(staffId,date,btn){const sel=btn.closest('tr').querySelector('.live-classify'),val=sel.value,note=prompt('Optional admin note for this day:','')||null;try{await rpc('attendance_live_admin_classify_day',{p_token:ctx().token,p_staff_id:staffId,p_date:date,p_classification:val,p_note:note});toast('Day classification saved.');await loadHistory()}catch(e){toast(e.message,true)}}
  function toLocalInput(v){if(!v)return '';const d=new Date(v),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
  async function ensureDayInHistory(staffId,date){let r=(liveState.history||[]).find(x=>x.staff_id===staffId&&x.operational_date===date);if(r)return r;try{const d=await rpc('attendance_live_admin_history',{p_token:ctx().token,p_start:date,p_end:date,p_staff_id:staffId});r=(d.rows||[])[0];return r}catch{return null}}
  async function editDay(staffId,date){const r=await ensureDayInHistory(staffId,date);if(!r||!(r.sessions||[]).length)return toast('No live session exists for this day.',true);const modal=$('liveEditModal'),list=$('liveEditSessions');list.innerHTML=r.sessions.map(s=>`<div class="live-edit-session"><strong>Session ${s.session_no}</strong><label>Check In<input type="datetime-local" data-id="${s.id}" data-field="in" value="${toLocalInput(s.check_in_at)}"></label><label>Check Out<input type="datetime-local" data-id="${s.id}" data-field="out" value="${toLocalInput(s.check_out_at)}"></label><button class="btn secondary tiny" onclick="GoyaLiveAdmin.saveSessionEdit('${s.id}',this)">${s.check_out_at?'Save Session':'Set Checkout'}</button></div>`).join('');$('liveEditTitle').textContent=`${r.staff_name} · ${date}`;modal.classList.remove('hidden')}
  function localInputToIso(v){if(!v)return null;const d=new Date(v);return d.toISOString()}
  async function saveSessionEdit(id,btn){const box=btn.closest('.live-edit-session'),pin=box.querySelector('[data-field="in"]').value,pout=box.querySelector('[data-field="out"]').value;if(!pout&&!confirm('Check Out is blank. Save this session as incomplete?'))return;try{await rpc('attendance_live_admin_update_session',{p_token:ctx().token,p_session_id:id,p_check_in:localInputToIso(pin),p_check_out:localInputToIso(pout)});toast('Session corrected. Original values remain in audit history.');closeEdit();if(!$('attLiveHistory')?.classList.contains('hidden'))await loadHistory();if(!$('attLiveDashboard')?.classList.contains('hidden'))await loadDashboard()}catch(e){toast(e.message,true)}}
  function closeEdit(){$('liveEditModal')?.classList.add('hidden')}
  function detailRows(rows=filteredRows()){return rows.map(r=>{const c=calc(r),ss=r.sessions||[];return {'Date':r.operational_date,'Staff':r.staff_name,'Section':(r.sections||[]).join(', '),'Shift Sessions':ss.length,'Session Details':ss.map(s=>`Shift ${s.session_no}: ${fmtTime(s.check_in_at)} - ${fmtTime(s.check_out_at)}`).join(' | '),'Worked':ss.length?mins(c.sec/60):'','Net':ss.length?mins(c.net):'','OT':c.ot?otText(c.ot):'','Late Minutes':r.late_minutes||0,'Break Taken':ss.length?(r.break_taken!==false?'Yes':'No'):'','Status':status(r),'Verification':verification(r),'Location':locationText(r),'Note':r.classification_note||''}})}
  function safeName(v){return String(v||'All_Staff').replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'')||'All_Staff'}
  function reportFileBase(ext){const staffSel=$('liveHistStaff'),staff=staffSel?.value?staffSel.options[staffSel.selectedIndex]?.text:'All_Staff',from=$('liveHistFrom').value,to=$('liveHistTo').value;return `Goya_Live_Attendance_${safeName(staff)}_${from}_to_${to}.${ext}`}
  function summarySheetRows(rows){const by=new Map();rows.forEach(r=>{if(!by.has(r.staff_id))by.set(r.staff_id,[]);by.get(r.staff_id).push(r)});return [...by.values()].map(rs=>{const s=summaryFor(rs),r=rs[0];return {'Staff':r.staff_name,'Section':(r.sections||[]).join(', '),'Duty Days':s.duty,'Weekly Off':s.weekly,'Leave':s.leave,'Sick Leave':s.sick,'Unpaid Leave':s.unpaid,'Absent':s.absent,'Public Holiday':s.holiday,'Other Approved':s.other,'Pending Review':s.pending,'Working Hours':mins(s.work),'Net Hours':mins(s.net),'OT':otText(s.ot),'Late Days':s.lateDays,'Late Minutes':s.lateMin,'No Break Days':s.noBreak,'Split Shift Days':s.split,'Verification Review':s.review}})}
  function exportExcel(){const rows=filteredRows();if(!rows.length)return toast('Load history first.',true);if(!window.XLSX)return toast('Excel library is still loading.',true);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(summarySheetRows(rows)),'Summary');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(detailRows(rows)),'Daily Details');const by=new Map();rows.forEach(r=>{if(!by.has(r.staff_id))by.set(r.staff_id,[]);by.get(r.staff_id).push(r)});for(const rs of by.values()){let nm=safeName(rs[0].staff_name).slice(0,31)||'Staff';if(wb.SheetNames.includes(nm))nm=(nm.slice(0,27)+'_'+Math.random().toString(36).slice(2,5)).slice(0,31);XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(detailRows(rs)),nm)}XLSX.writeFile(wb,reportFileBase('xlsx'))}
  function exportPDF(){const rows=filteredRows();if(!rows.length)return toast('Load history first.',true);if(!window.jspdf?.jsPDF)return toast('PDF library is still loading.',true);const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape'}),from=$('liveHistFrom').value,to=$('liveHistTo').value,by=new Map();rows.forEach(r=>{if(!by.has(r.staff_id))by.set(r.staff_id,[]);by.get(r.staff_id).push(r)});let firstPage=true;for(const rs of by.values()){if(!firstPage)doc.addPage();firstPage=false;const r0=rs[0],s=summaryFor(rs);doc.setFontSize(18);doc.text('GOYA - Live Attendance Report',14,15);doc.setFontSize(12);doc.text(`${r0.staff_name}  |  ${(r0.sections||[]).join(', ')||'—'}`,14,23);doc.setFontSize(9);doc.text(`Period: ${from} to ${to}`,14,29);doc.text(`Duty: ${s.duty}   Weekly Off: ${s.weekly}   Leave: ${s.leave+s.sick+s.unpaid}   Absent: ${s.absent}   Working: ${mins(s.work)}   Net: ${mins(s.net)}   OT: ${otText(s.ot)}   Late: ${s.lateDays} day(s) / ${s.lateMin} min   Split: ${s.split}`,14,35);doc.autoTable({startY:40,head:[['Date','Sessions','Working Time','Worked','Net','OT','Late','Break','Status','Verification']],body:rs.map(r=>{const c=calc(r),ss=r.sessions||[];return [r.operational_date,ss.length,ss.length?ss.map(x=>`${fmtTime(x.check_in_at)}-${fmtTime(x.check_out_at)}`).join(' | '):'—',ss.length?mins(c.sec/60):'—',ss.length?mins(c.net):'—',c.ot?otText(c.ot):'—',r.late_minutes?`${r.late_minutes} min`:'—',ss.length?(r.break_taken!==false?'Yes':'No'):'—',status(r),verification(r)]}),styles:{fontSize:7.5,cellPadding:2},headStyles:{fillColor:[36,57,49]}})}doc.save(reportFileBase('pdf'))}
  async function getPublicIp(){for(const url of ['https://api.ipify.org?format=json','https://api64.ipify.org?format=json']){try{const r=await fetch(url,{cache:'no-store'});if(r.ok){const j=await r.json();if(j.ip)return j.ip}}catch{}}throw new Error('Could not detect public IP.')}
  function getGps(){return new Promise((resolve,reject)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy}),e=>reject(new Error(e.code===1?'Allow location permission first.':'Could not get GPS.')),{enableHighAccuracy:true,timeout:15000}):reject(new Error('GPS unsupported.')))}
  function renderLocations(){const host=$('liveLocationList');if(!host)return;host.innerHTML=liveState.settingsLocations.length?liveState.settingsLocations.map((l,i)=>`<div class="live-location-row"><div><strong>${esc(l.name||'Workplace')}</strong><span>${Number(l.lat).toFixed(6)}, ${Number(l.lon).toFixed(6)} · ${l.radius_m||150}m</span></div><button class="btn danger tiny" onclick="GoyaLiveAdmin.removeLocation(${i})">Remove</button></div>`).join(''):'<div class="live-empty">No workplace location configured yet.</div>'}
  async function loadSettings(){try{const r=await rpc('attendance_live_admin_settings',{p_token:ctx().token});liveState.rules=r||{};liveState.settingsLocations=Array.isArray(r.locations)?r.locations:[];$('liveRequireLocation').checked=r.require_location!==false;$('liveRequireNetwork').checked=r.require_network!==false;$('liveDutyHours').value=(Number(r.duty_presence_minutes)||540)/60;$('liveBreakMinutes').value=Number(r.break_minutes)||60;$('liveApprovedIps').value=(Array.isArray(r.approved_public_ips)?r.approved_public_ips:[]).join('\n');renderLocations()}catch(e){toast(e.message,true)}}
  async function detectLocation(){try{const g=await getGps();$('liveLocLat').value=g.lat.toFixed(7);$('liveLocLon').value=g.lon.toFixed(7);toast(`GPS captured ±${Math.round(g.accuracy||0)}m`)}catch(e){toast(e.message,true)}}
  async function detectIp(){try{const ip=await getPublicIp(),box=$('liveApprovedIps'),ips=box.value.split(/\s+/).filter(Boolean);if(!ips.includes(ip))ips.push(ip);box.value=ips.join('\n');toast(`Current public IP added: ${ip}`)}catch(e){toast(e.message,true)}}
  function addLocation(){const name=$('liveLocName').value.trim()||'Workplace',lat=+$('liveLocLat').value,lon=+$('liveLocLon').value,radius=+$('liveLocRadius').value||150;if(!Number.isFinite(lat)||!Number.isFinite(lon))return toast('Capture or enter valid GPS coordinates.',true);liveState.settingsLocations.push({name,lat,lon,radius_m:radius,active:true});$('liveLocName').value='';renderLocations()}
  function removeLocation(i){liveState.settingsLocations.splice(i,1);renderLocations()}
  async function saveSettings(){const ips=[...new Set($('liveApprovedIps').value.split(/\s+/).map(x=>x.trim()).filter(Boolean))],value={require_location:$('liveRequireLocation').checked,require_network:$('liveRequireNetwork').checked,duty_presence_minutes:Math.round((+$('liveDutyHours').value||9)*60),regular_net_minutes:480,break_minutes:+$('liveBreakMinutes').value||60,late_grace_minutes:15,operational_cutoff:'02:00',shift_start_times:['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00'],locations:liveState.settingsLocations,approved_public_ips:ips};try{liveState.rules=await rpc('attendance_live_admin_save_settings',{p_token:ctx().token,p_value:value});toast('Live Attendance settings saved.')}catch(e){toast(e.message,true)}}
  function fillStaffFilter(){const sel=$('liveHistStaff'),staff=ctx().staff||[];if(sel&&!sel.dataset.ready){sel.innerHTML='<option value="">All Staff</option>'+staff.map(s=>`<option value="${s.portal_staff_id||s.id}">${esc(s.name)}</option>`).join('');sel.dataset.ready='1'}}
  function openDashboard(){fillStaffFilter();if(!$('liveDashDate').value)$('liveDashDate').value=new Date().toISOString().slice(0,10);loadDashboard()}
  function openHistory(){fillStaffFilter();const d=new Date(),end=d.toISOString().slice(0,10),month=end.slice(0,7),start=`${month}-01`;if(!$('liveHistMonth').value)$('liveHistMonth').value=month;if(!$('liveHistFrom').value)$('liveHistFrom').value=start;if(!$('liveHistTo').value)$('liveHistTo').value=end;loadHistory()}
  function openSettings(){loadSettings()}
  window.GoyaLiveAdmin={openDashboard,loadDashboard,openHistory,loadHistory,renderHistory,applyMonth,saveClassification,editDay,saveSessionEdit,closeEdit,exportExcel,exportPDF,openSettings,loadSettings,detectLocation,detectIp,addLocation,removeLocation,saveSettings};
  if(window.GoyaAttendance){window.GoyaAttendance.openLiveDashboard=openDashboard;window.GoyaAttendance.openLiveHistory=openHistory;window.GoyaAttendance.openLiveSettings=openSettings;}
})();
