(() => {
  const cfg=window.GOYA_CONFIG||{};
  let sb=null,liveState={dashboard:null,history:[],rules:{},settingsLocations:[],serverOffset:0,timer:null},dashboardFilter='',controlFilter='',controlTarget=null;
  const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0'),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const ctx=()=>window.GoyaAttendance?._liveContext?.()||{};
  async function client(){if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY)throw new Error('Supabase config missing');if(!sb)sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}});return sb}
  async function rpc(name,args={}){const c=ctx();if(!c.token)throw new Error('Admin session expired. Please login again.');await client();const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message);return data}
  function toast(msg,err=false){const host=$('toastHost')||document.body,d=document.createElement('div');d.className='toast'+(err?' err':'');d.textContent=msg;host.appendChild(d);setTimeout(()=>d.remove(),3800)}
  const fmtTime=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString('en-AE',{hour:'numeric',minute:'2-digit'})};
  const fmtDate=v=>{const d=new Date(v+'T12:00:00');return d.toLocaleDateString('en-AE',{day:'2-digit',month:'short',year:'numeric'})};
  const mins=m=>{m=Math.max(0,Math.floor(Number(m)||0));return `${Math.floor(m/60)}h ${pad(m%60)}m`};
  const otText=m=>{m=Math.floor(Math.max(0,Number(m)||0)/30)*30;if(!m)return '0';if(m===30)return '30 min';const h=m/60;return `${Number.isInteger(h)?h:h.toFixed(1)} ${h===1?'hour':'hours'}`};
  function calc(row,serverNow=null){const rules=liveState.rules||{},sessions=Array.isArray(row.sessions)?row.sessions:[];let sec=0;const now=serverNow?new Date(serverNow).getTime():Date.now()+liveState.serverOffset;sessions.forEach((s,i)=>{let st=new Date(s.check_in_at).getTime();if(i===0&&row.scheduled_start){const sch=new Date(`${row.operational_date}T${String(row.scheduled_start).slice(0,5)}:00+04:00`).getTime();if(Number.isFinite(sch)&&st<sch)st=sch}const en=s.check_out_at?new Date(s.check_out_at).getTime():now;if(Number.isFinite(st)&&Number.isFinite(en)&&en>st)sec+=(en-st)/1000});const breakTaken=row.break_taken!==false,target=breakTaken?(Number(rules.duty_presence_minutes)||540):(Number(rules.regular_net_minutes)||480),net=Math.max(0,sec/60-(breakTaken?(Number(rules.break_minutes)||60):0)),ot=Math.floor(Math.max(0,net-(Number(rules.regular_net_minutes)||480))/30)*30;return {sec,net,ot,target,remaining:Math.max(0,target-sec/60),liveOt:Math.max(0,sec/60-target)}}
  function groupDashboard(d){const dayMap=new Map((d.days||[]).map(x=>[x.staff_id,x])),sessMap=new Map();for(const s of d.sessions||[]){if(!sessMap.has(s.staff_id))sessMap.set(s.staff_id,[]);sessMap.get(s.staff_id).push(s)}return (d.staff||[]).map(st=>{const day=dayMap.get(st.id)||{operational_date:d.operational_date,break_taken:true,classification:'Day Off - Pending Review',late_minutes:0},sessions=sessMap.get(st.id)||[];return {...day,staff_id:st.id,staff_name:st.name,sections:st.sections||[],sessions}})}
  function status(row){const ss=row.sessions||[],open=ss.some(s=>!s.check_out_at);if(open)return 'On Duty';if(ss.length)return row.classification&&row.classification!=='Day Off - Pending Review'?row.classification:'Completed';return row.classification||'Day Off - Pending Review'}
  function verification(row){const ss=row.sessions||[];if(!ss.length)return '—';const okIn=ss.every(s=>s.check_in_verified),okOut=ss.filter(s=>s.check_out_at).length===ss.length&&ss.filter(s=>s.check_out_at).every(s=>s.check_out_verified);return okIn&&okOut?'Verified':'Review'}
  function locationText(){return '—'}
  function verificationBadge(r){return verification(r)==='Verified'?'<span class="live-verify ok">✓ Verified</span>':'<span class="live-verify bad">! Review</span>'}
  function isCompleted(r){const ss=r.sessions||[];return ss.length>0&&!ss.some(x=>!x.check_out_at)}
  function rowMatches(r,filter){if(!filter)return true;if(filter==='Late')return Number(r.late_minutes||0)>0;if(filter==='Completed'||filter==='Shift Done')return isCompleted(r);if(filter==='Pending Review')return status(r)==='Day Off - Pending Review';return status(r)===filter}
  function renderDashboard(){
    const d=liveState.dashboard;if(!d)return;const all=groupDashboard(d);
    let on=0,completed=0,late=0,pending=0;
    all.forEach(r=>{const st=status(r);if(st==='On Duty')on++;if(isCompleted(r))completed++;if((r.late_minutes||0)>0)late++;if(st==='Day Off - Pending Review')pending++});
    if($('liveDOn'))$('liveDOn').textContent=on;if($('liveDCompleted'))$('liveDCompleted').textContent=completed;if($('liveDLate'))$('liveDLate').textContent=late;if($('liveDPending'))$('liveDPending').textContent=pending;
    const rows=all.filter(r=>rowMatches(r,dashboardFilter));
    const rowHtml=rows.map(r=>{const c=calc(r),ss=r.sessions||[],first=ss[0],open=ss.some(x=>!x.check_out_at),remain=c.remaining>0?mins(c.remaining):`OT ${mins(c.liveOt)}`,act=ss.length?`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.editDay('${r.staff_id}','${r.operational_date}')">${open?'Fix Checkout':'Edit'}</button>`:'—';return `<tr><td><strong>${esc(r.staff_name)}</strong></td><td><span class="live-status-pill ${open?'on':''}">${open?'<i class="live-dot"></i>':''}${esc(open?'On Duty':isCompleted(r)?'Shift Done':status(r))}</span></td><td>${fmtTime(first?.check_in_at)}</td><td>${mins(c.sec/60)}</td><td>${open?remain:'—'}</td><td>${r.late_minutes?`${r.late_minutes} min`:'—'}</td><td>${ss.length}</td><td>${ss.length?verificationBadge(r):'—'}</td><td>${act}</td></tr>`}).join('');
    if($('liveDashboardRows'))$('liveDashboardRows').innerHTML=rowHtml||'<tr><td colspan="9" class="empty">No staff match this filter.</td></tr>';
    const cards=$('liveDashboardCards');if(cards)cards.innerHTML=rows.map(r=>{const c=calc(r),ss=r.sessions||[],first=ss[0],open=ss.some(x=>!x.check_out_at),st=open?'On Duty':isCompleted(r)?'Shift Done':status(r);return `<article class="live-duty-card ${open?'active':''}"><header><strong>${open?'<i class="live-dot"></i>':''}${esc(r.staff_name)}</strong><b>${esc(st)}</b></header><div class="live-duty-grid"><span>Check In<b>${fmtTime(first?.check_in_at)}</b></span><span>Working<b>${mins(c.sec/60)}</b></span><span>${open?(c.remaining>0?'Remaining':'OT'):'Sessions'}<b>${open?(c.remaining>0?mins(c.remaining):mins(c.liveOt)):ss.length}</b></span><span>Late<b>${r.late_minutes?`${r.late_minutes}m`:'—'}</b></span></div><footer>${ss.length?verificationBadge(r):''}${ss.length?`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.editDay('${r.staff_id}','${r.operational_date}')">${open?'Fix Checkout':'Edit'}</button>`:''}</footer></article>`}).join('');
    const label=$('liveDashboardFilterLabel');if(label)label.textContent=dashboardFilter?`Filtered: ${dashboardFilter==='Day Off - Pending Review'?'Pending Review':dashboardFilter}`:'Showing all staff';
    document.querySelectorAll('.live-stat-btn').forEach(x=>x.classList.toggle('active-filter',!!dashboardFilter&&x.dataset.filter===dashboardFilter));
  }
  async function loadDashboard(){try{const date=$('liveDashDate')?.value||new Date().toISOString().slice(0,10),d=await rpc('attendance_live_admin_dashboard',{p_token:ctx().token,p_date:date});liveState.dashboard=d;liveState.rules=d.rules||{};liveState.serverOffset=new Date(d.server_now).getTime()-Date.now();renderDashboard();applyDashboardFilter();clearInterval(liveState.timer);liveState.timer=setInterval(renderDashboard,1000)}catch(e){toast(e.message,true)}}
  function classificationOptions(cur){return ['Day Off - Pending Review','Weekly Off','Leave','Sick Leave','Unpaid Leave','Absent','Public Holiday','Other Approved','Duty'].map(x=>`<option${x===cur?' selected':''}>${x}</option>`).join('')}
  function applyMonth(){const m=$('liveHistMonth')?.value;if(!m)return;const [y,mo]=m.split('-').map(Number),end=new Date(y,mo,0).getDate();$('liveHistFrom').value=`${m}-01`;$('liveHistTo').value=`${m}-${pad(end)}`}
  async function loadHistory(){try{const from=$('liveHistFrom').value,to=$('liveHistTo').value,staff=$('liveHistStaff').value||null;if(!from||!to)return toast('Select From and To dates.',true);const d=await rpc('attendance_live_admin_history',{p_token:ctx().token,p_start:from,p_end:to,p_staff_id:staff});liveState.rules=d.rules||liveState.rules;liveState.serverOffset=new Date(d.server_now).getTime()-Date.now();liveState.history=d.rows||[];renderHistory()}catch(e){toast(e.message,true)}}
  function filteredRows(){const filter=$('liveHistStatus')?.value||'';return (liveState.history||[]).filter(r=>{if(!filter)return true;if(filter==='Completed')return isCompleted(r);if(filter==='On Duty')return status(r)==='On Duty';return status(r)===filter||r.classification===filter})}
  function summaryFor(rows){const o={days:rows.length,duty:0,weekly:0,leave:0,sick:0,unpaid:0,absent:0,holiday:0,other:0,pending:0,work:0,net:0,ot:0,lateDays:0,lateMin:0,noBreak:0,split:0,review:0};rows.forEach(r=>{const c=calc(r),ss=r.sessions||[],st=status(r);if(ss.length){o.duty++;o.work+=c.sec/60;o.net+=c.net;o.ot+=c.ot;if(r.break_taken===false)o.noBreak++;if(ss.length>1)o.split++;if(verification(r)!=='Verified'||ss.some(s=>!s.check_out_at))o.review++}if(r.late_minutes){o.lateDays++;o.lateMin+=Number(r.late_minutes)||0}if(st==='Weekly Off')o.weekly++;else if(st==='Leave')o.leave++;else if(st==='Sick Leave')o.sick++;else if(st==='Unpaid Leave')o.unpaid++;else if(st==='Absent')o.absent++;else if(st==='Public Holiday')o.holiday++;else if(st==='Other Approved')o.other++;else if(st==='Day Off - Pending Review')o.pending++});return o}
  function renderSummary(rows){const s=summaryFor(rows),host=$('liveReportSummary');if(host)host.innerHTML=[['Duty Days',s.duty],['Weekly Off',s.weekly],['Leave',s.leave+s.sick+s.unpaid],['Working',mins(s.work)],['Net',mins(s.net)],['OT',otText(s.ot)],['Late Days',s.lateDays],['Split Shift',s.split],['Pending',s.pending],['Review',s.review]].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');const by=new Map();rows.forEach(r=>{if(!by.has(r.staff_id))by.set(r.staff_id,[]);by.get(r.staff_id).push(r)});const ph=$('livePersonSummary');if(ph)ph.innerHTML=[...by.values()].map(rs=>{const x=summaryFor(rs),r=rs[0];return `<article><header><strong>${esc(r.staff_name)}</strong></header><div><span>Duty <b>${x.duty}</b></span><span>Net <b>${mins(x.net)}</b></span><span>OT <b>${otText(x.ot)}</b></span><span>Late <b>${x.lateDays}</b></span><span>Off/Leave <b>${x.weekly+x.leave+x.sick+x.unpaid+x.holiday+x.other+x.pending}</b></span></div></article>`}).join('')}
  function renderHistory(){const rows=filteredRows();renderSummary(rows);if($('liveHistoryAdminRows'))$('liveHistoryAdminRows').innerHTML=rows.length?rows.map(r=>{const c=calc(r),ss=r.sessions||[],st=status(r),isNo=!ss.length;const primary=isNo?`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.saveClassification('${r.staff_id}','${r.operational_date}',this)">Save</button>`:`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.editDay('${r.staff_id}','${r.operational_date}')">Edit</button>`;return `<tr><td>${esc(r.operational_date)}</td><td><strong>${esc(r.staff_name)}</strong></td><td>${ss.length?ss.map(s=>`${fmtTime(s.check_in_at)} → ${fmtTime(s.check_out_at)}`).join('<br>'):'—'}</td><td>${ss.length}</td><td>${ss.length?mins(c.sec/60):'—'}</td><td>${ss.length?mins(c.net):'—'}</td><td>${c.ot?otText(c.ot):'—'}</td><td>${r.late_minutes?`${r.late_minutes} min`:'—'}</td><td>${ss.length?(r.break_taken!==false?'Yes':'No'):'—'}</td><td>${isNo?`<select class="live-classify" data-staff="${r.staff_id}" data-date="${r.operational_date}">${classificationOptions(r.classification||'Day Off - Pending Review')}</select>`:esc(st)}</td><td>${ss.length?verificationBadge(r):'—'}</td><td><div class="live-row-actions">${primary}<button class="btn danger tiny" onclick="GoyaLiveAdmin.deleteHistoryDay('${r.staff_id}','${r.operational_date}','${esc(r.staff_name)}')">Delete</button></div></td></tr>`}).join(''):'<tr><td colspan="12" class="empty">No records for selected filters.</td></tr>'}
  async function deleteHistoryDay(staffId,date,staffName){if(!confirm(`Delete ${staffName} attendance for ${date} from active history/reports?\n\nThe record will be archived in Supabase audit history and can be restored later.`))return;try{await rpc('attendance_live_admin_delete_day',{p_token:ctx().token,p_staff_id:staffId,p_date:date,p_reason:null});toast('Attendance archived and removed from active reports.');await loadHistory();if(!$('attLiveDashboard')?.classList.contains('hidden'))await loadDashboard()}catch(e){toast(e.message,true)}}
  async function saveClassification(staffId,date,btn){const sel=btn.closest('tr').querySelector('.live-classify'),val=sel.value,note=prompt('Optional admin note for this day:','')||null;try{await rpc('attendance_live_admin_classify_day',{p_token:ctx().token,p_staff_id:staffId,p_date:date,p_classification:val,p_note:note});toast('Day classification saved.');await loadHistory()}catch(e){toast(e.message,true)}}
  function toLocalInput(v){if(!v)return '';const d=new Date(v),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
  async function ensureDayInHistory(staffId,date){let r=(liveState.history||[]).find(x=>x.staff_id===staffId&&x.operational_date===date);if(r)return r;try{const d=await rpc('attendance_live_admin_history',{p_token:ctx().token,p_start:date,p_end:date,p_staff_id:staffId});r=(d.rows||[])[0];return r}catch{return null}}
  async function editDay(staffId,date){const r=await ensureDayInHistory(staffId,date);if(!r||!(r.sessions||[]).length)return toast('No live session exists for this day.',true);const modal=$('liveEditModal'),list=$('liveEditSessions');list.innerHTML=r.sessions.map(s=>`<div class="live-edit-session"><strong>Session ${s.session_no}</strong><label>Check In<input type="datetime-local" data-id="${s.id}" data-field="in" value="${toLocalInput(s.check_in_at)}"></label><label>Check Out<input type="datetime-local" data-id="${s.id}" data-field="out" value="${toLocalInput(s.check_out_at)}"></label><button class="btn secondary tiny" onclick="GoyaLiveAdmin.saveSessionEdit('${s.id}',this)">${s.check_out_at?'Save Session':'Set Checkout'}</button></div>`).join('');$('liveEditTitle').textContent=`${r.staff_name} · ${date}`;modal.classList.remove('hidden')}
  function localInputToIso(v){if(!v)return null;const d=new Date(v);return d.toISOString()}
  async function saveSessionEdit(id,btn){const box=btn.closest('.live-edit-session'),pin=box.querySelector('[data-field="in"]').value,pout=box.querySelector('[data-field="out"]').value;if(!pout&&!confirm('Check Out is blank. Save this session as incomplete?'))return;try{await rpc('attendance_live_admin_update_session',{p_token:ctx().token,p_session_id:id,p_check_in:localInputToIso(pin),p_check_out:localInputToIso(pout)});toast('Session corrected. Original values remain in audit history.');closeEdit();if(!$('attLiveHistory')?.classList.contains('hidden'))await loadHistory();if(!$('attLiveDashboard')?.classList.contains('hidden'))await loadDashboard()}catch(e){toast(e.message,true)}}
  function closeEdit(){$('liveEditModal')?.classList.add('hidden')}
  function detailRows(rows=filteredRows()){return rows.map(r=>{const c=calc(r),ss=r.sessions||[];return {'Date':r.operational_date,'Staff':r.staff_name,'Shift Sessions':ss.length,'Session Details':ss.map(s=>`Shift ${s.session_no}: ${fmtTime(s.check_in_at)} - ${fmtTime(s.check_out_at)}`).join(' | '),'Worked':ss.length?mins(c.sec/60):'','Net':ss.length?mins(c.net):'','OT':c.ot?otText(c.ot):'','Late Minutes':r.late_minutes||0,'Break Taken':ss.length?(r.break_taken!==false?'Yes':'No'):'','Status':status(r),'Verification':verification(r),'Note':r.classification_note||''}})}
  function safeName(v){return String(v||'All_Staff').replace(/[^a-z0-9]+/gi,'_').replace(/^_|_$/g,'')||'All_Staff'}
  function reportFileBase(ext){const staffSel=$('liveHistStaff'),staff=staffSel?.value?staffSel.options[staffSel.selectedIndex]?.text:'All_Staff',from=$('liveHistFrom').value,to=$('liveHistTo').value;return `Goya_Live_Attendance_${safeName(staff)}_${from}_to_${to}.${ext}`}
  function summarySheetRows(rows){const by=new Map();rows.forEach(r=>{if(!by.has(r.staff_id))by.set(r.staff_id,[]);by.get(r.staff_id).push(r)});return [...by.values()].map(rs=>{const s=summaryFor(rs),r=rs[0];return {'Staff':r.staff_name,'Duty Days':s.duty,'Weekly Off':s.weekly,'Leave':s.leave,'Sick Leave':s.sick,'Unpaid Leave':s.unpaid,'Absent':s.absent,'Public Holiday':s.holiday,'Other Approved':s.other,'Pending Review':s.pending,'Working Hours':mins(s.work),'Net Hours':mins(s.net),'OT':otText(s.ot),'Late Days':s.lateDays,'Late Minutes':s.lateMin,'No Break Days':s.noBreak,'Split Shift Days':s.split,'Verification Review':s.review}})}
  function exportExcel(){const rows=filteredRows();if(!rows.length)return toast('Load history first.',true);if(!window.XLSX)return toast('Excel library is still loading.',true);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(summarySheetRows(rows)),'Summary');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(detailRows(rows)),'Daily Details');const by=new Map();rows.forEach(r=>{if(!by.has(r.staff_id))by.set(r.staff_id,[]);by.get(r.staff_id).push(r)});for(const rs of by.values()){let nm=safeName(rs[0].staff_name).slice(0,31)||'Staff';if(wb.SheetNames.includes(nm))nm=(nm.slice(0,27)+'_'+Math.random().toString(36).slice(2,5)).slice(0,31);XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(detailRows(rs)),nm)}XLSX.writeFile(wb,reportFileBase('xlsx'))}
  function exportPDF(){const rows=filteredRows();if(!rows.length)return toast('Load history first.',true);if(!window.jspdf?.jsPDF)return toast('PDF library is still loading.',true);const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape'}),from=$('liveHistFrom').value,to=$('liveHistTo').value,by=new Map();rows.forEach(r=>{if(!by.has(r.staff_id))by.set(r.staff_id,[]);by.get(r.staff_id).push(r)});let firstPage=true;for(const rs of by.values()){if(!firstPage)doc.addPage();firstPage=false;const r0=rs[0],s=summaryFor(rs);doc.setFontSize(18);doc.text('GOYA - Live Attendance Report',14,15);doc.setFontSize(12);doc.text(`${r0.staff_name}`,14,23);doc.setFontSize(9);doc.text(`Period: ${from} to ${to}`,14,29);doc.text(`Duty: ${s.duty}   Weekly Off: ${s.weekly}   Leave: ${s.leave+s.sick+s.unpaid}   Absent: ${s.absent}   Working: ${mins(s.work)}   Net: ${mins(s.net)}   OT: ${otText(s.ot)}   Late: ${s.lateDays} day(s) / ${s.lateMin} min   Split: ${s.split}`,14,35);doc.autoTable({startY:40,head:[['Date','Sessions','Working Time','Worked','Net','OT','Late','Break','Status','Verification']],body:rs.map(r=>{const c=calc(r),ss=r.sessions||[];return [r.operational_date,ss.length,ss.length?ss.map(x=>`${fmtTime(x.check_in_at)}-${fmtTime(x.check_out_at)}`).join(' | '):'—',ss.length?mins(c.sec/60):'—',ss.length?mins(c.net):'—',c.ot?otText(c.ot):'—',r.late_minutes?`${r.late_minutes} min`:'—',ss.length?(r.break_taken!==false?'Yes':'No'):'—',status(r),verification(r)]}),styles:{fontSize:7.5,cellPadding:2},headStyles:{fillColor:[23,63,53]}})}doc.save(reportFileBase('pdf'))}
  function overtimeSummaryRows(){const rows=filteredRows(),by=new Map();rows.forEach(r=>{const c=calc(r);if(c.ot<=0)return;if(!by.has(r.staff_id))by.set(r.staff_id,{staff:r.staff_name,ot:0,days:0});const x=by.get(r.staff_id);x.ot+=c.ot;x.days+=1});return [...by.values()].sort((a,b)=>b.ot-a.ot)}
  function overtimeFileBase(ext){const staffSel=$('liveHistStaff'),staff=staffSel?.value?staffSel.options[staffSel.selectedIndex]?.text:'All_Staff',from=$('liveHistFrom').value,to=$('liveHistTo').value;return `Goya_Overtime_Only_${safeName(staff)}_${from}_to_${to}.${ext}`}
  function exportOvertimeExcel(){const data=overtimeSummaryRows();if(!data.length)return toast('No overtime found for the selected period.',true);if(!window.XLSX)return toast('Excel library is still loading.',true);const rows=data.map(x=>({'Staff':x.staff,'OT Days':x.days,'Total OT':otText(x.ot),'OT Minutes':x.ot}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Overtime Summary');XLSX.writeFile(wb,overtimeFileBase('xlsx'))}
  function exportOvertimePDF(){const data=overtimeSummaryRows();if(!data.length)return toast('No overtime found for the selected period.',true);if(!window.jspdf?.jsPDF)return toast('PDF library is still loading.',true);const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'portrait'}),from=$('liveHistFrom').value,to=$('liveHistTo').value,total=data.reduce((a,x)=>a+x.ot,0);doc.setFontSize(18);doc.text('GOYA - Overtime Summary',14,16);doc.setFontSize(10);doc.text(`Period: ${from} to ${to}`,14,24);doc.text(`Staff with OT: ${data.length}   Total OT: ${otText(total)}`,14,30);doc.autoTable({startY:36,head:[['Staff','OT Days','Total OT']],body:data.map(x=>[x.staff,x.days,otText(x.ot)]),styles:{fontSize:9,cellPadding:2.5},headStyles:{fillColor:[23,63,53]},margin:{left:14,right:14}});doc.save(overtimeFileBase('pdf'))}
  async function getPublicIp(){for(const url of ['https://api.ipify.org?format=json','https://api64.ipify.org?format=json']){try{const r=await fetch(url,{cache:'no-store'});if(r.ok){const j=await r.json();if(j.ip)return j.ip}}catch{}}throw new Error('Could not detect public IP.')}
  function getGps(){return new Promise((resolve,reject)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:p.timestamp}),e=>reject(new Error(e.code===1?'Allow location permission first.':'Could not get fresh GPS.')),{enableHighAccuracy:true,timeout:20000,maximumAge:0}):reject(new Error('GPS unsupported.')))}
  function renderLocations(){const host=$('liveLocationList');if(!host)return;host.innerHTML=liveState.settingsLocations.length?liveState.settingsLocations.map((l,i)=>`<div class="live-location-row"><div><strong>${esc(l.name||'Workplace')}</strong><span>${Number(l.lat).toFixed(6)}, ${Number(l.lon).toFixed(6)} · ${l.radius_m||150}m</span></div><button class="btn danger tiny" onclick="GoyaLiveAdmin.removeLocation(${i})">Remove</button></div>`).join(''):'<div class="live-empty">No workplace location configured yet.</div>'}
  async function loadSettings(){try{const r=await rpc('attendance_live_admin_settings',{p_token:ctx().token});liveState.rules=r||{};liveState.settingsLocations=Array.isArray(r.locations)?r.locations:[];$('liveRequireLocation').checked=r.require_location!==false;$('liveRequireNetwork').checked=r.require_network!==false;$('liveDutyHours').value=(Number(r.duty_presence_minutes)||540)/60;$('liveBreakMinutes').value=Number(r.break_minutes)||60;$('liveApprovedIps').value=(Array.isArray(r.approved_public_ips)?r.approved_public_ips:[]).join('\n');renderLocations()}catch(e){toast(e.message,true)}}
  async function detectLocation(){try{const g=await getGps();$('liveLocLat').value=g.lat.toFixed(7);$('liveLocLon').value=g.lon.toFixed(7);toast(`GPS captured ±${Math.round(g.accuracy||0)}m`)}catch(e){toast(e.message,true)}}
  async function detectIp(){try{const ip=await getPublicIp(),box=$('liveApprovedIps'),ips=box.value.split(/\s+/).filter(Boolean);if(!ips.includes(ip))ips.push(ip);box.value=ips.join('\n');toast(`Current public IP added: ${ip}`)}catch(e){toast(e.message,true)}}
  function addLocation(){const name=$('liveLocName').value.trim()||'Workplace',lat=+$('liveLocLat').value,lon=+$('liveLocLon').value,radius=+$('liveLocRadius').value||150;if(!Number.isFinite(lat)||!Number.isFinite(lon))return toast('Capture or enter valid GPS coordinates.',true);liveState.settingsLocations.push({name,lat,lon,radius_m:radius,active:true});$('liveLocName').value='';renderLocations()}
  function removeLocation(i){liveState.settingsLocations.splice(i,1);renderLocations()}
  async function saveSettings(){const ips=[...new Set($('liveApprovedIps').value.split(/\s+/).map(x=>x.trim()).filter(Boolean))],value={require_location:$('liveRequireLocation').checked,require_network:$('liveRequireNetwork').checked,duty_presence_minutes:Math.round((+$('liveDutyHours').value||9)*60),regular_net_minutes:480,break_minutes:+$('liveBreakMinutes').value||60,late_grace_minutes:15,operational_cutoff:'02:00',shift_start_times:['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00'],locations:liveState.settingsLocations,approved_public_ips:ips};try{liveState.rules=await rpc('attendance_live_admin_save_settings',{p_token:ctx().token,p_value:value});toast('Live Attendance settings saved.')}catch(e){toast(e.message,true)}}
  function fillStaffFilter(){const sel=$('liveHistStaff'),staff=ctx().staff||[];if(sel&&!sel.dataset.ready){sel.innerHTML='<option value="">All Staff</option>'+staff.map(s=>`<option value="${s.portal_staff_id||s.id}">${esc(s.name)}</option>`).join('');sel.dataset.ready='1'}}

  function setDashboardFilter(filter){dashboardFilter=dashboardFilter===filter?'':(filter||'');renderDashboard()}
  function applyDashboardFilter(){if(liveState.dashboard)renderDashboard()}
  function setControlFilter(filter){controlFilter=controlFilter===filter?'':(filter||'');renderControl()}
  function renderControl(){const d=liveState.dashboard;if(!d)return;const all=groupDashboard(d),host=$('liveControlCards');let on=0,done=0,pending=0;all.forEach(r=>{const st=status(r);if(st==='On Duty')on++;else if(isCompleted(r))done++;if(st==='Day Off - Pending Review')pending++});const sum=$('liveControlSummary');if(sum)sum.innerHTML=`<button class="live-control-stat ${controlFilter==='On Duty'?'active-filter':''}" onclick="GoyaLiveAdmin.setControlFilter('On Duty')"><span>On Duty</span><strong>${on}</strong></button><button class="live-control-stat ${controlFilter==='Completed'?'active-filter':''}" onclick="GoyaLiveAdmin.setControlFilter('Completed')"><span>Shift Done</span><strong>${done}</strong></button><button class="live-control-stat ${controlFilter==='Pending Review'?'active-filter':''}" onclick="GoyaLiveAdmin.setControlFilter('Pending Review')"><span>Review</span><strong>${pending}</strong></button><button class="live-control-clear" onclick="GoyaLiveAdmin.setControlFilter('')">All Staff</button>`;const rows=all.filter(r=>rowMatches(r,controlFilter));if(host)host.innerHTML=`<div class="live-control-list"><div class="live-control-head"><span>Staff</span><span>Status</span><span>Check In</span><span>Working</span><span>Remaining / OT</span><span>Sessions</span><span>Late</span><span>Verification</span><span>Actions</span></div>${rows.map(r=>{const c=calc(r),ss=r.sessions||[],open=ss.some(x=>!x.check_out_at),st=open?'On Duty':isCompleted(r)?'Shift Done':status(r);const timeLabel=open?(c.remaining>0?mins(c.remaining):`OT ${mins(c.liveOt)}`):'—';return `<div class="live-control-row ${open?'is-live':''}"><div class="live-control-name"><strong>${open?'<i class="live-dot"></i>':''}${esc(r.staff_name)}</strong>${open?'<small>LIVE</small>':''}</div><span class="live-status-pill ${open?'on':''}">${esc(st)}</span><span>${fmtTime(ss[0]?.check_in_at)}</span><b>${mins(c.sec/60)}</b><b>${timeLabel}</b><span>${ss.length}</span><span>${r.late_minutes?`${r.late_minutes}m`:'—'}</span><span>${ss.length?verificationBadge(r):'—'}</span><div class="live-control-actions"><button class="btn success tiny" ${open?'disabled':''} onclick="GoyaLiveAdmin.openManualControl('${r.staff_id}','${esc(r.staff_name)}','${ss.length?'REJOIN':'CHECK_IN'}')">${ss.length?'Rejoin':'Check In'}</button><button class="btn danger tiny" ${open?'':'disabled'} onclick="GoyaLiveAdmin.openManualControl('${r.staff_id}','${esc(r.staff_name)}','CHECK_OUT')">Check Out</button>${ss.length?`<button class="btn secondary tiny" onclick="GoyaLiveAdmin.editDay('${r.staff_id}','${r.operational_date}')">Edit</button>`:''}</div></div>`}).join('')||'<div class="live-empty">No staff match this filter.</div>'}</div>`}
  async function loadControl(){
    try{const date=$('liveControlDate')?.value||new Date().toISOString().slice(0,10),d=await rpc('attendance_live_admin_dashboard',{p_token:ctx().token,p_date:date});liveState.dashboard=d;liveState.rules=d.rules||{};liveState.serverOffset=new Date(d.server_now).getTime()-Date.now();renderControl();clearInterval(liveState.timer);liveState.timer=setInterval(renderControl,1000)}catch(e){toast(e.message,true)}
  }
  function openControl(){if(!$('liveControlDate').value)$('liveControlDate').value=new Date().toISOString().slice(0,10);loadControl()}
  function openManualControl(staffId,staffName,action){
    controlTarget={staffId,staffName};
    $('liveControlModalTitle').textContent=`${staffName} · Manual Attendance`;
    $('liveControlAction').value=action||'CHECK_IN';
    const now=new Date(Date.now()+liveState.serverOffset);now.setMinutes(now.getMinutes()-now.getTimezoneOffset());$('liveControlTime').value=now.toISOString().slice(0,16);
    $('liveControlBreak').value='true';$('liveControlNote').value='';
    $('liveControlModal').classList.remove('hidden');
  }
  function closeControlModal(){$('liveControlModal')?.classList.add('hidden');controlTarget=null}
  async function saveManualControl(){
    if(!controlTarget)return;
    const action=$('liveControlAction').value,when=$('liveControlTime').value,note=$('liveControlNote').value.trim();
    if(!when)return toast('Select attendance date and time.',true);
    if(!confirm(`Save manual ${action.replace('_',' ')} for ${controlTarget.staffName}?`))return;
    try{
      const d=new Date(when);if(Number.isNaN(d.getTime()))throw new Error('Invalid date/time.');
      await rpc('attendance_live_admin_manual_action',{p_token:ctx().token,p_staff_id:controlTarget.staffId,p_action:action,p_at:d.toISOString(),p_break_taken:$('liveControlBreak').value==='true',p_note:note});
      toast('Manual attendance saved and audit history updated.');closeControlModal();await loadControl();
    }catch(e){toast(e.message,true)}
  }
  function openDashboard(){fillStaffFilter();if(!$('liveDashDate').value)$('liveDashDate').value=new Date().toISOString().slice(0,10);loadDashboard()}
  function openHistory(){fillStaffFilter();const d=new Date(),end=d.toISOString().slice(0,10),month=end.slice(0,7),start=`${month}-01`;if(!$('liveHistMonth').value)$('liveHistMonth').value=month;if(!$('liveHistFrom').value)$('liveHistFrom').value=start;if(!$('liveHistTo').value)$('liveHistTo').value=end;loadHistory()}
  function openSettings(){loadSettings()}
  window.GoyaLiveAdmin={openDashboard,loadDashboard,setDashboardFilter,openControl,loadControl,setControlFilter,openManualControl,closeControlModal,saveManualControl,openHistory,loadHistory,renderHistory,applyMonth,saveClassification,deleteHistoryDay,editDay,saveSessionEdit,closeEdit,exportExcel,exportPDF,exportOvertimeExcel,exportOvertimePDF,openSettings,loadSettings,detectLocation,detectIp,addLocation,removeLocation,saveSettings};
  if(window.GoyaAttendance){window.GoyaAttendance.openLiveDashboard=openDashboard;window.GoyaAttendance.openLiveHistory=openHistory;window.GoyaAttendance.openLiveSettings=openSettings;}
})();
